### ISSUE TITLE
Private group disappeared from chats 

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#10030]
# Bug Report

## Description

After migration from 0.10.0 to 0.11.0 RC1 private group disappeared from chats. It appeared again after someone mentioned me there.

## Steps to reproduce

1. Be a member of private group on 0.10.0
2. Migrate to 0.11.0 RC1

#### Expected behavior
The group is visible on chat list

#### Actual behavior
The group is NOT visible on chat list

### Additional Information

- Status desktop version: 0.11.0 RC1
- Operating System: Ubuntu

**Comment by caybro** [comment]
Same for me; it reappeared as soon as I got a new message though. Also, the history there is lost

**Comment by caybro** [comment]
And it happens on _every_ app restart

**Comment by caybro** [comment]
I noticed a possible pattern here:

![image](https://user-images.githubusercontent.com/5377645/228175865-ea1994fb-0ac2-4ba2-bc64-3518840576fc.png)

It doesn't appear because it doesn't belong to any category, much like inside our community. There are far more uncategorized channels here than just "memes", this one just got some messages
