### ISSUE TITLE
Various collectibles errors

### ISSUE THREAD

**Issue by dlipicar** [status-im/status-desktop#10063]
# Bug Report

## Description

1) The "loading" collectibles have a wrong color

They look like this: 
![image](https://user-images.githubusercontent.com/11161531/228288368-9927d050-036b-434d-a660-1f7ef80d74bb.png)

They should look like this:

![image](https://user-images.githubusercontent.com/11161531/228288797-8019d612-2e9e-4184-a724-9c56496ecbb2.png)

2) The "loading" collectibles are not shown for the first fetch, only for the 2nd and following "pages"

3) If the fetch fails for whatever reason it keeps retrying infinite times.
Implement an "Error" state and don't attempt to fetch more until the reset.

**Comment by Khushboo-dev-cpp** [comment]
Hey here for 1st one I have already fixed it. 

fir 2. There is an issue that Ive observed as well, we get a 403 error when we first call opensea for collectibles and anthony mentioned it could because of API not being set for opensea on dev but only on ci builds. @alaibe correct me if I am wrong.

3. Definitely a miss from in understanding the implementation. thanks for adding it
