### ISSUE TITLE
Onboarding: spaces before and after username are not trimmed which leads to message loss

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10120]
### Description

1. open status
2. as user name enter `<whitespace>Bob<whitespace>`
3. set up account
4. send a contact request to someone
5. send a message

As result, having a name with total length of 5 symbols having whitespaces before and after leads to message loss

<img width="1512" alt="Screenshot 2023-04-03 at 10 39 45" src="https://user-images.githubusercontent.com/82375995/229443650-73f25beb-680b-4915-a0d0-21d5106a0d85.png">

**Comment by anastasiyaig** [comment]
@benjthayer @John-44 would it be possible to clarify once again the requirements for display name? I think it is a good moment to check it for both platforms and align if needed.

**Current state for desktop:**
- 5 chars min
- letters, numbers, underscores, and hyphens only allowed

**Questions:**
- why the limitation is to 5 chars? How about the short names like Jo, Anna, Bob , John? :) 
- Cyrillic is not allowed - expected?

@VladimrLitvinenko adding u as well for transparency

**Comment by John-44** [comment]
> @benjthayer @John-44 would it be possible to clarify once again the requirements for display name? I think it is a good moment to check it for both platforms and align if needed.
> 
> **Current state for desktop:**
> 
> * 5 chars min
> * letters, numbers, underscores, and hyphens only allowed
> 
> **Questions:**
> 
> * why the limitation is to 5 chars? How about the short names like Jo, Anna, Bob , John? :)
> * Cyrillic is not allowed - expected?
> 
> @VladimrLitvinenko adding u as well for transparency

@anastasiyaig requirements for display names are:
- min 5 characters
- max 24 characters
- Only characters allowed are: A-Z, a-Z, 0-9, -, _, and spaces between words
- display name cannot end in "_eth" or "-eth"             

To answer questions:

Q. Why 5 character minimum?
A. We have no way of detecting identical usernames, but identical usernames are bad.  Likelihood of users choosing identical usernames goes up if we allow usernames of less than 5 characters e.g. many people will choose Bob, Anna, John, etc....  People (like myself) with short names can add something on the end e.g. I use "John_", this will slightly reduce the chance of users picking identical usernames

Q.  Cyrillic is not allowed - expected?
A. Yes, we only support A-Z, a-Z, 0-9, -, _, and spaces between words in usernames.  We utilize this to achieve a better compression ratio in our new URL format, and it's safer from a security prospective because if we allowed the full UTF-8 set then many characters can be used to impersonate other characters.

**Comment by alexandraB99** [comment]
@caybro actually a tab key falls into the existing regex "/^[a-zA-Z0-9\-_ ]+$/"
<img width="517" alt="s" src="https://user-images.githubusercontent.com/31625338/234328827-4939191f-1d3a-424c-8d79-9abc1db8fdd9.png">
