### ISSUE TITLE
Chat: scrolling does not always scroll to the correct message from reply

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10131]
### Description

https://user-images.githubusercontent.com/82375995/229508527-5c63f224-7c33-4786-afb7-f219bf31e0a2.mp4

**Comment by caybro** [comment]
Yup... this one is hard to fix. It happens when you have image/link previews in between the current one and the one being jumped to. We are scrolling the message view but at the same time it changes its height -> so it's highlighted but not always correctly positioned (scrolled to)

cc @alexjba should know more details :)
