### ISSUE TITLE
Wrong timestamp

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#10408]
See https://github.com/status-im/status-desktop/issues/10406#issuecomment-1520082399

![image](https://user-images.githubusercontent.com/5377645/234024570-168385e7-e6f5-4909-87e1-2a7d3490de17.png)

**Comment by caybro** [comment]
@John-44 can you pls share your Settings/Language & Currency screenshot (and your OS locale settings too)

**Comment by caybro** [comment]
@John-44 also noticed the wrong timestamp is part of a discord message; does it happen for regular messages too?

**Comment by Cuteivist** [comment]
@caybro  I had same issue, but in wallet section.
Issue was because on WIndows local date format have already `yyyy`, so by replacing `yy` with `yyyy` it created `yyyyyy` (6*y) in timestamp format.

I fixed it here https://github.com/status-im/status-desktop/pull/10580/files#diff-2c8f8d3f414b86095699323cdc038ee52271706708b1a1bc0c64f905fb6ff4b6R304
