### ISSUE TITLE
Optimise nb queries made by owner node when checking member tokens 

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#10481]
As an owner node of a community that has token permissions, every membership request and every membership needs to be (regularly) checked to ensure they still own the necessary funds to be part of the community.

This includes checking ERC20 token balances and ERC721 token ownership on all supported chains.
At the moment we always check every supported chain always.

One way to improve this would be to have members tell the owner on which chains they'll find which funds. 
Based on that information, the owner node can then specifically query a subset of chains to check funds.

To make this work a few things will be needed:

1. We need to change the protocol to support chain information (e.g. requirement is 200 USDC; chainID 1 => 20 USDC, chainID 1337 => 120 USDC)
2. We need to figure out how we decide which chains will be used for that information, if the necessary funds live on multiple chains
3. We also need to decide what the "split" going to be in case the funds live on multiple chains.

re: 3): here's what I mean:

Say the requirement to request access to a community is 2000 SNT.
A user owns a wallet with 2000 SNT on Ethereum and 5000 SNT Arbitrum.

Now there are various configurations that would fulfill the requirement

=> ETH: 2000 SNT
=> ARB: 2000 SNT
=> ETH: 1000 SNT, ARB: 1000 SNT
... // all other combinations that make 2000 SNT across supported chains

^ In such a scenario, how do we decide which chain info will be attached to the membership request (and later preserved in the membership data) ?

/cc @John-44 if you have thoughts on this, let me know

**Comment by jrainville** [comment]
Another question @0x-r4bbit and I had in our meeting is whether or not we want this to be backwards compatible.

Since this will create a new field in the community description's permission list (for the chain ID), older versions would not have it.

---

### Option 1: Keep the old code that checks all chains

For accounts that have not updated yet, ie they do not have the chain IDs listed, we use the old code where we check all chains.
Once they update, we create a "migration" that sends the chains to the owner to update.

#### Pros:
- Good experience for users since they do not have anything to do

#### Cons:
- Keeps old code
  - It's possible to incorporate the new code with that old one, but it would still be more logic that is needed
  - We still have the problem that if users don't update, we will poll all chains

---

### Option 2: Kick out users that are using the old version

Break backwards compatibility. We just kick the users and don't accept new ones if they do not send the chain IDs.

It forces the users to update

#### Pros:
- Only uses the new code (least effort option)
- Only polls the right chains

#### Cons:
- Confusing for users, since they will be kicked without info
  - Might be acceptable since we are only using it for Status CCs)

---

### Option 3: Have the owner node migrate the users

When the Owner updates to the new version, they are the one that performs a migration while doing the token checks.

What this means is that while doing the loops of all chains, the owner notes which chain has the wanted token and adds them in the new `chainId`s field for that user.

This would be necessary only for accounts that didn't send their chain ids.

#### Pros:
- User has nothing to do
- We would only poll all chains once, then we use the new approach for all account

#### Cons:
- A bit more code is needed on the admin side

---

### Conclusion

IMO, the solution 2 and 3 are the best ones. Option 3 is better for users, as it migrates more intuitively and the owner node is already the source of truth. Option 2 is the simpler one for us devs, but we need to communicate why it doesn't work for those that haven't updated.

Feel free to add other options and discuss the ones I brought up.

**Comment by 0x-r4bbit** [comment]
@cammellos curious to hear your thoughts on this as well, especially re: how do we decide which chain IDs to attach to a community membership request, given that multiple chain ID configurations would yield proof of enough funds to fulfill token permission requirements.

@jrainville as for migration/backwards compatibility:

I even tend to go with option 1). If we have a Status version in the near future that only performs these optimized membership requests, then future communities will all end up in that code path (where checking all chains is only done when there's no chain ID info to check for).

If the argument is that we don't want that, because for our Status community specifically that'd mean owner nodes will always check all chains, then I'd argue that we might as well create a new community that Status-CC need to request access to.

If we go with option 2), they'd be kicked and need to sent a request again anyways.

Only thing that just comes into my mind is that the entire discord / archive story will have to be redone as well (which we probably don't want). So that'd be a strong argument to keep the current Status community and find a backwards compatible path forward (or migration).

**Comment by cammellos** [comment]
> @cammellos curious to hear your thoughts on this as well, especially re: how do we decide which chain IDs to attach to a community membership request, given that multiple chain ID configurations would yield proof of enough funds to fulfill token permission requirements.

I would agree with @jrainville , I suppose most of the people don't own the same requirement over multiple chains, so most of the times we'll be in the optimal case (we disclose as fewer chain-id/wallet combinations as possible), so disclosing wallets/chain-ids (maybe up to a fixed `n`) that fullfills the requirements seems reasonable.

Otherwise you'll let the user decide, but that's much more work.

With regard of backward compatibility, is this used anywhere at the moment?
From what I gather (asking around), there's not actually any community that is using this, so I would try to avoid any extra effort if that's not really used. But up to us to be honest, no strong opinion on the matter.

**Comment by 0x-r4bbit** [comment]
> With regard of backward compatibility, is this used anywhere at the moment?
From what I gather (asking around), there's not actually any community that is using this, so I would try to avoid any extra effort if that's not really used. But up to us to be honest, no strong opinion on the matter.

Apart from test communities there's indeed none that makes use of this. So we can introduce a breaking change.

> I would agree with @jrainville , I suppose most of the people don't own the same requirement over multiple chains, so most of the times we'll be in the optimal case (we disclose as fewer chain-id/wallet combinations as possible), so disclosing wallets/chain-ids (maybe up to a fixed n) that fullfills the requirements seems reasonable.

Thank you for your feedback!

**Comment by John-44** [comment]
> > @cammellos curious to hear your thoughts on this as well, especially re: how do we decide which chain IDs to attach to a community membership request, given that multiple chain ID configurations would yield proof of enough funds to fulfill token permission requirements.
> 
> I would agree with @jrainville , I suppose most of the people don't own the same requirement over multiple chains, so most of the times we'll be in the optimal case (we disclose as fewer chain-id/wallet combinations as possible), so disclosing wallets/chain-ids (maybe up to a fixed `n`) that fullfills the requirements seems reasonable.
> 
> Otherwise you'll let the user decide, but that's much more work.
> 
> With regard of backward compatibility, is this used anywhere at the moment? From what I gather (asking around), there's not actually any community that is using this, so I would try to avoid any extra effort if that's not really used. But up to us to be honest, no strong opinion on the matter.

@cammellos @0x-r4bbit I don't think we need to worry about backwards compatibility *if* we get this implemented before the end of the 0.13 release cycle.

**Comment by jrainville** [comment]
@0x-r4bbit is this issue being fixed by https://github.com/status-im/status-go/pull/3494?

It's not linked

**Comment by 0x-r4bbit** [comment]
It's not linked there because this is a different repository.
I'll have to rebase this stuff anyways. But yes, that PR is supposed to improve things.

**Comment by jrainville** [comment]
Ok, I'll still link it, since you can link cross repo
