### ISSUE TITLE
Rollout expanded set of Link Unfurl Cards for desktop

### ISSUE THREAD

**Issue by benjthayer** [status-im/status-desktop#10585]
Dependent on https://github.com/status-im/status-desktop/issues/10852

New designs have been created to complete the set of unfurl cards for desktop.

The designs now include the unfurl cards for:

- YouTube
- GitHub
- Twitter
- External links
- Internal Communities
- Internal Community Channels
- Internal Profiles
- GIFs

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=21932-655154&t=i3leEXxXB1cWXfuL-4

Also worth noting that there a loading/fetch state for the Community banner for the internal Community and channel cards:

<img width="708" alt="Screenshot 2023-05-08 at 18 16 53" src="https://user-images.githubusercontent.com/110033914/236888262-96dca1a3-fc3f-4601-8f86-55fc2ca6c01e.png">

The designs aim to be as close to the mobile implementation @ilmotta is currently working on so whoever picks this task up, please do set up a call with @ilmotta (and myself if helpful) to discuss what work has already been undertaken on the dev side to limit duplication. 

cc @John-44

**Comment by ilmotta** [comment]
Thanks @benjthayer! For the moment, I would say the best for the desktop team is to wait until the status-go implementation stabilizes this month, since it's still highly susceptible to changes, even at the protocol layer (I'll open the first PR this week in status-go).

I'll make sure to make another comment in this issue once I think the status-go implementation is solid enough to be used.

**Comment by benjthayer** [comment]
> Thanks @benjthayer! For the moment, I would say the best for the desktop team is to wait until the status-go implementation stabilizes this month, since it's still highly susceptible to changes, even at the protocol layer (I'll open the first PR this week in status-go).
> 
> I'll make sure to make another comment in this issue once I think the status-go implementation is solid enough to be used.

Thanks @ilmotta !

**Comment by caybro** [comment]
@benjthayer ping, how much do you think the Figma design will change? We should not imho wait that long and should start working on the UI components right _now_ (even if it's going to be fed with dummy data for now, until the status-go backend stabilizes)

**Comment by ilmotta** [comment]
Hi @caybro. At this very moment I'm working on the mobile side and just yesterday me and a couple other designers, including Ben and John, discussed a bunch of details, but the designs are pretty stable as far as I understand.

I believe you'll be able to start working on the desktop side _without_ dummy data as early as next week, since I'm going to open the status-go PR this week (it may be a bit rough on the edges, but totally usable). But as you said, I started with dummy data on the client in the beginning too, so that works of course.

Let's keep in touch since the new link unfurling code will still evolve a couple PRs down the road. Thanks

>  Then when @ilmotta let's folks know here that the status-go implementation has stabilised, the UI components can then be wired to the backed at that point.

Will do :+1:  @John-44

**Comment by ilmotta** [comment]
@benjthayer, @John-44, @pedro-et: FYI Link previews are being tested by QAs already. If you want, you can test right now the PR builds https://github.com/status-im/status-mobile/pull/15891#issuecomment-1546074981.

I was going to initially implement the whole feature behind a feature flag, but since we're aiming to include it in the next mobile release this week, it'll be open for all of us.

There's much to improve behind the scenes (status-go), but it should be enough for the desktop team to start the work if they can/desire (@caybro).

Cheers!

**Comment by igor-sirotin** [comment]
Want to add some new requirements:
1. After https://github.com/status-im/status-go/issues/3761 we should be able to show an image preview in the same way. 
We should also add some UI like `Open original URL in Browser` to be able to see the original size image.
2. After https://github.com/status-im/status-go/issues/3762 we should be able to show the link preview in the same way.
We should also fetch the latest link data from waku when the link previews appears in the viewport. We could do this automatically in status-go on preview reception, but it might lead to ddos attacks 🙂 
2. Opening any preview should open a popup asking `Do you trust <hostname>?`: cancel/open. And a checkbox `never ask about <hostname>

**Comment by alexjba** [comment]
@igor-sirotin Do you know if there's a backend task to provide the favicon of the unfurled URL? I see it's currently missing

**Comment by alexjba** [comment]
@ilmotta Thank you for the info. Helps a lot!

One thing I see missing from the new APIs is the domain name (we have the hostName which includes the prefix) needed for the image previews. Is it something that will be implemented in status-go as part of this task https://github.com/status-im/status-mobile/issues/17073? I see both mobile and desktop designs are using a logo for the image preview containing the first letter of the domain name.

<img width="310" alt="Screenshot 2023-09-13 at 11 36 58" src="https://github.com/status-im/status-desktop/assets/47811206/077e8567-ec24-4195-8011-d2d36c2db8b8">

<img width="348" alt="Screenshot 2023-09-13 at 11 50 38" src="https://github.com/status-im/status-desktop/assets/47811206/42b5739b-9c86-4c58-a9e4-ecf4858ba13f">



Desktop: [https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?type=design&node-id=22347-219483&mode=design&t=Pzn7RybClrTp2eUF-0](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&node-id=22347-219483&mode=design&t=Pzn7RybClrTp2eUF-0)
Mobile: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=9598-551920&mode=design&t=ruX4jUgKgJQaFxd8-0

**Comment by benjthayer** [comment]
> About the `S` prefix shown in the following image, I don't understand the value for the user, at least in the Figma example. @benjthayer, could you help us understand this requirement? We are already showing the hostname `i.seadn.io`, so what does `S` convey?

Hey @ilmotta the `S` is a dynamic representation of the URL if there is no favicon - the `S` in this case is an abbreviation of `seadn` - much like how we use letters for user's pfp when they have not uploaded an image. While it can be considered duplicative of the URL, it is in place as much to standardise the design for all cards - so there is the same layout and margins etc between previews with and without favicons.

cc @mariocnovoa

**Comment by ilmotta** [comment]
Thanks @benjthayer, yeah consistency is important too. I still find `S` redundant because the hostname is there already and it's a reliable information to the user, whereas `S` is an abbreviation that can happen for many different hostnames.

**Comment by alexjba** [comment]
Wrongfully closed
