### ISSUE TITLE
[release 0.12.0] application startup time takes more than minute when upgrading to 0.12.0

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10610]
### Description

1. having DB with 0.11.0 release, upgrade to 0.12.0
2. launch the app

**As result,** it took me 1 minute 11 seconds to login to the application

3. send a message in group chat

**As result,** the message is being sent in more than 2 minutes (app is not responding, bench ball appears)

**Comment by jrainville** [comment]
I've tried the migration from 0.11 to 0.12 seven times now with the shared dev account that contains the Status community and I can't reproduce anymore.

It was fairly fast each time. I used Patryk's script here https://github.com/status-im/status-desktop/issues/10588#issuecomment-1540023049 to measure the time and it was decent.
Indeed, the migrations are the longest operations on the DB with about 2 seconds for each of them, but that's nothing compared to the minute we experienced before.

The store node store make the app unusable for a couple of seconds/minute afterwards because there are a lot of messages to fetch, but still, I was fully logged in and inside the app at that point.

I'll keep trying some other ways, but so far, it seems hard to reproduce.
