### ISSUE TITLE
Settings -> Keycard: Copy of keycard settings could be improved

### ISSUE THREAD

**Issue by guylouis** [status-im/status-desktop#10647]
using 0.11.1

**here's our current copy for keycard settings** 
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=199%3A2653&t=OJFATDkeg77doQal-1
![image](https://github.com/status-im/status-desktop/assets/11461437/2f19c6ee-40fc-4f16-8633-d9ff52e73c7d)

for new users, these different wordings create significant cognitive load to understand. 

**here's a suggestion for your review of a simpler copy** @xAlisher @benjthayer 

Migrate an existing account to a new keycard
**Create a new keycard account**
Generate mnemonic words
Import mnemonic words
From an existing keycard
**Other**
Check what’s on a keycard
Factory reset a keycard

------

@saledjenic please do not implement before review and confirmation from @benjthayer & @xAlisher

**Comment by alaibe** [comment]
@benjthayer any update on that one?

**Comment by benjthayer** [comment]
Hey @alaibe we will be putting in effort to optimise the usability of the Keycard flows when we look at them for mobile so we were thinking then would be a good time to review the copy here. 

A couple of thoughts on the proposed copy in the meantime:

- Its generally best to make each menu item fully comprehensible without the context of the subtitle. So copy that leads on from the subtitle may not be optimal - the user may read the option first then have to track back to the subtitle (which they likely skipped over in the first instance) in order to understand the option - for eg with the option `From an existing Keycard`

- We are using `seed phrase` throughout the desktop app as opposed to `mnemonic phrase` so it would be best to stick to that phrasing for now for consistency perhaps. I believe the mobile app is using `recovery phrase` so as we approach the launch of the new mobile app it would be worth us auditing and aligning the desktop terminology in this regard with the mobile app.

I'd need a bit of dedicated time to look at the rewording so may need to look at prioritisation with @John-44

**Comment by saledjenic** [comment]
Just want to mention one other aspect we've discussed which @guylouis pointed out during that meeting. There are some flows where we're considering the keycard as an empty keycard if it has no metadata even it has seed phrase stored and in such cases we just don't let user to proceed further. I don't know by heart what are those flows and we surely need to review them all what @guylouis will do after 0.13.0 release.

Some examples we've discussed then:
- "Factory reset a Keycard" flow should be accessible for all non empty keycards (regardless they contain only seed phrase or seed phrase + metadata) - it's like that now
- "Check what’s on a Keycard" flow should be accessible only for all keycards which contain metadata, no point in proceeding with this flow for other keycards' states (empty or without metadata) - it's like that now
- "Create a backup copy of this Keycard" flow should be accessible for all non empty keycards, but at the moment we don't let user to create a copy of a Keycard if that keycard has no metadata.

Though I am not sure for the last case that we should allow user to make a copy of a Keycard without metadata, even that's kinda expected by the keycard team, cause that ruins the design. How would this look if we would allow keycards without metadata (somehow incomplete)?

![a3](https://github.com/status-im/status-desktop/assets/86303051/85e58a16-6a31-40f1-a00f-e7c74c2ae91b)
