### ISSUE TITLE
Communities -> Permissions: missing counter when adding requirement with 1 minted token

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10660]
### Description

1. create community
2. mint a token
3. add a permission that requires to hold **1** minted token to join the community
4. check Edit permission screen
5. check Permissions screen

**As result**, on both mentioned screens the digit 1 is missing , which is potential confusion. I indicated clearly that i want a member to hold 1 specific token , not any amount of mentioned token

<img width="1551" alt="Screenshot 2023-05-12 at 11 38 37" src="https://github.com/status-im/status-desktop/assets/82375995/5af023da-0d22-445e-b92b-f7d9d8fc8ef4">

<img width="1551" alt="Screenshot 2023-05-12 at 11 38 33" src="https://github.com/status-im/status-desktop/assets/82375995/9af0d854-e111-482c-85c0-0feb07a42045">

<img width="1551" alt="Screenshot 2023-05-12 at 11 37 02" src="https://github.com/status-im/status-desktop/assets/82375995/f72cf530-4b47-4409-8089-cd8238dcc628">

**Comment by noeliaSD** [comment]
This is on propose. It is a design decision. When there is only one collectible, the number `1` is missing, and it is only applicable for collectibles, for assets, number `1` is shown.

However, looking again into figma.. And after some refactors in the design file, I cannot see the explicit behavior of hidding number `1` for collectibles. Here, and [example](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=22772%3A496682&t=hWx7mk1jWKPwJtFu-1).

@benjthayer  could you confirm which is the expected behavior?

**Comment by anastasiyaig** [comment]
sorry about that @noeliaSD ! i was not able to find it in figma as well. Lets wait for @benjthayer to clarify !

**Comment by noeliaSD** [comment]
> sorry about that @noeliaSD ! i was not able to find it in figma as well. Lets wait for @benjthayer to clarify !

No problem at all!! It was clearly specified in some point but it is true that now, it isn't, or I can't find it!

**Comment by benjthayer** [comment]
Hey @anastasiyaig @noeliaSD I think whether we show the number or not is down to whether the token is a 1:1 (1 of a kind). When selecting `Furbeard` in the flows, the user is opting for the permission to be tied to the owner of a specific, 1 of a kind NFT. The alternate route is to select `Any Cryptokitties` and select a number of `Cryptokitties` the user must hold for the permission to apply to them.

<img width="791" alt="Any of the collection" src="https://github.com/status-im/status-desktop/assets/110033914/4b81ebf8-9210-4bc7-93eb-a72a765faf7c">

VS.

<img width="1876" alt="A specific collectible" src="https://github.com/status-im/status-desktop/assets/110033914/e4155f9e-ac1e-41e3-a27e-c5e84dd54d2a">


So if the user has gone down the path of selecting `Any` of a collectible collection and input a number, when they review the permission the collectible should have that number prefixed to it. But if they go down the route of selecting a specific 1 of a kind collectible, there is no need to enter a number and no number will appear when they review the permission.

Hope that makes sense! Looping in @xAlisher who designed the flows to confirm.

**Comment by anastasiyaig** [comment]
okay for now there is no `Any` condition implemented, as u can see on the screen. We specifically set amount of NFT (1 or 15 or 77). Thats why i think having this specific digit matters. For the permission with `Any condition` we dont need to show counter assuming user has to have at least 1 NFT
@noeliaSD what do u think?

**Comment by noeliaSD** [comment]
We do already have implemented the `any` condition. If the collectibles list is a collection, then it should be displayed like in the cryptokitties example, with `any` option on top and then all the rest of items of the collection below as in the design.

We already have this bug open: https://github.com/status-im/status-desktop/issues/10546 where we will remove the amount selector when the collectible is a unique one. 

Then, the summary here, if I'm not wrong, would be:
1. If collectible is unique (item inside a collection), number 1 will not be displayed, since it only exists 1 element of this type.
2. For the rest of cases (selecting any in a collection type or, our minted collectibles), number 1 should be displayed.

Could you confirm @benjthayer , @anastasiyaig ?

**Comment by benjthayer** [comment]
> We do already have implemented the `any` condition. If the collectibles list is a collection, then it should be displayed like in the cryptokitties example, with `any` option on top and then all the rest of items of the collection below as in the design.
> 
> We already have this bug open: #10546 where we will remove the amount selector when the collectible is a unique one.
> 
> Then, the summary here, if I'm not wrong, would be:
> 
> 1. If collectible is unique (item inside a collection), number 1 will not be displayed, since it only exists 1 element of this type.
> 2. For the rest of cases (selecting any in a collection type or, our minted collectibles), number 1 should be displayed.
> 
> Could you confirm @benjthayer , @anastasiyaig ?

Correct! Thanks @noeliaSD  :)
