### ISSUE TITLE
I can't log into my mobile account on the desktop version, and the desktop version can't chat with the mobile version

### ISSUE THREAD

**Issue by ZiMoFangCong** [status-im/status-desktop#10699]
### Description
I can't login my mobile account on the desktop version, and the desktop version can't chat with the mobile version

**Comment by jrainville** [comment]
@ZiMoFangCong Hi, what versions of each app do you use and on which operating systems?

How did you add the mobile account on the desktop app?

**Comment by uraioa** [comment]
@jrainville 

Similar problem.
Since I generally only use Status desktop, I haven't tried the synchronization function.
But when I try to use Status desktop to chat with Status mobile, I found that the address format of the two is not the same (desktop starts with "zq" and mobile starts with "0x").
Many of my friends use Status mobile and I can't seem to start chatting with them via their addresses (starting with "0x").
Is this normal? And how can I chat with them?

OS: archlinux 6.3.1-arch2-1
Status version: 0.11.1

**Comment by ZiMoFangCong** [comment]
Status version 0.11.1
OS: ArchLinux 6.3
I trying use the sync code on phone,but i can't find the sync code option in "syncing".
So I try to recover the account with 12 words. But it shows that the account cannot be restored after two minutes.
Instead of letting me restore my account with these 12 recovery words, it made me create a new account with a public key address that is shorter than the one on my mobile account, and has 3 words user name in common. Also, this account (or any other account I create on the desktop) cannot chat with mobile users, as they do not show up in the search.

**Comment by John-44** [comment]
@uraioa @ZiMoFangCong Are you using Status Mobile 1.x (the version that is currently in the app stores) or a pre-alpha of Status Mobile 2.x?

The reason I'm asking is that the old legacy Status Mobile 1.x uses Waku1, and Status Desktop and Status Mobile 2.x use Waku2.  Waku1 and Waku2 are completely different protocols, and won't interop.   Also the device syncing functionality is only present in Status Mobile 2.x and Status Desktop, and is not present Status Mobile 1.x (and wouldn't work anyway, because of the different underlying messaging protocols being used).

Syncing a single user profile across two different installations of Status Desktop works today, and will this functionality will be present in a future Status Mobile 2.x release.  

For chat compatibility, today it's possible for different Status Desktop and Status Mobile 2.x users to message with each other (this is fully tested and being heavily dogfooded).  But it won't be possible for Status Mobile 1.x users to message with Status Desktop and Status Mobile 2.x users, and vice versa.    

When the Status Mobile 2.x app store release comes out, all Status Mobile 1.x users will update to the new version.  After this has happened, all Status clients will be using the same protocols and will be fully compatible.  But at the moment Status Mobile 2.x is still "pre-alpha".  A public alpha release of Status Mobile 2.x is scheduled to happen later this year.

**Comment by ZiMoFangCong** [comment]
Thanks for your answer. I look forward to and support Status to be more perfect.
I appreciate your development efforts. Once the new version comes out and fixes this issue, I will switch to Status with my friends and say goodbye to Matrix.
Good luck with your development!
