### ISSUE TITLE
[messenger] group chat keeps disappearing

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#10818]
# Bug Report
After every fresh start, the group chat is not visible. It only reappears later through the runtime when there's some new messages. You can see below that I even get notifications on startup from the said "UI Team" group chat.

![image](https://github.com/status-im/status-desktop/assets/5377645/cabe3b10-0218-4a12-ba04-a5e151a462ca)

And later it's back (after a new message arrived there):
![image](https://github.com/status-im/status-desktop/assets/5377645/18988a00-3dad-4ef4-95de-a9535da8e5f0)

### Additional Information

- Status desktop version: master
- Operating System: linux

**Comment by anastasiyaig** [comment]
@jrainville any suspects for potential root cause of this one? it is defo a regression (works ok in 0.12.0)

**Comment by caybro** [comment]
> @caybro are you still mutual contact with the group owner?

No I'm not :/ 

![image](https://github.com/status-im/status-desktop/assets/5377645/c408a255-e3d1-47e7-95ee-efb65cb3507d)

I guess it broke at some point due to some bad contact migration; but in any case, this "disappearing" problem started happening only recently

**Comment by jrainville** [comment]
> this "disappearing" problem started happening only recently

Yeah I haven't seen it in a while. It might be because in my case, I'm mutual with everyone in the group.

Still, when starting the app, we should get all the chats from the DB regardless of who is in the chat, so it seems like the chat is showing at start, disappearing because maybe you got a message a from a non-contact, then reappearing later when a contact messages?

Let me know if that sounds like a possible scenario.

I'll try to investigate later

**Comment by caybro** [comment]
> Still, when starting the app, we should get all the chats from the DB regardless of who is in the chat, so it seems like the chat is showing at start, disappearing because maybe you got a message a from a non-contact, then reappearing later when a contact messages?

It's always hidden at startup, regardless of whether there's some new messages there or not

**Comment by jrainville** [comment]
> But at the same time, I always get the group notifications at startup, even before the UI shows up

Ah yeah that makes sense. The message fetch starts before even seeing the UI. Ok I'll check what's going on.

**Comment by jrainville** [comment]
@caybro I can't seem to reproduce.

I looked at the status-go code and I am 75% sure that the issue is partly caused by you and Iuri (the owner) not being mutual contacts.
However, I don't understand the cause of it repeating. It might not appear at first, but once you see it, it should be saved as `active` and it would appear each time.

Without a repro state, it's hard to know why the repeated disappearance happens. 

Is there a chance you can share your DB with me? Or maybe we can have a pairing session so we can try to debug together?

In the meantime, I assume this is a DB/account that you had to re-sync using the seed phrase. Did you have to get re-added to the group or it just ended up appearing once (and then disappearing on the next start)?

**Comment by caybro** [comment]
For me, 100% reproducible, repeatedly. Happy to pair-debug this, just ping me :) 

> In the meantime, I assume this is a DB/account that you had to re-sync using the seed phrase.

Yes

> Did you have to get re-added to the group or it just ended up appearing once (and then disappearing on the next start)?

Nope
