### ISSUE TITLE
Account recover screen isn't vertically centered

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#10947]
I just imported one of my tests account and Status did its recovery. While processing, my screen looked like this:

![Screenshot from 2023-06-06 14-41-12](https://github.com/status-im/status-desktop/assets/445106/9ff871ee-31b1-4a13-aaf2-efb529ed0266)

The bottom part is cut off. I do realize that this is due to the height of my window, but since the pure content does fit into the height, I'd expect it to be vertically centered regardless.

**Comment by kounkou** [comment]
Hi,

Here are the list of steps to reproduce the issue along with the result. This is to account for any update on the source code that could have made since the ticket was created on June 6.

### Steps to reproduce

0. I recompiled Status-desktop from the source
1. I created a test account and kept the seed phrase
2. I make clean from the source code, and deleted the Keys in Keystore
3. I launched Status-desktop (using `make run`)
4. I `adding existing Status user` then `I don't have other device` -> `Enter seed phrase`
5. I enter previously saved seed phrase

### Result

![Image](https://github.com/status-im/status-desktop/assets/2589171/55c08467-677b-40e6-aa7a-5f46d1627961)

### Conclusion

This is different from the posted screenshot by @0x-r4bbit where the gif, `fetching data...` and `list view` and `continue button`  block is not entered in the parent window.

### Further analysis

I have also tried to reduce the window to its minimum, and the result is still consistent with expectations

![Image](https://github.com/status-im/status-desktop/assets/2589171/2bb7e773-9e0c-4adb-9a2d-f6ca60447012)

From code perspective : 

This issue is similar to #10939 and was fixed by @noeliaSD with commit https://github.com/status-im/status-desktop/commit/e36ace38b2383059c702d852a5dc63fd6ab5c7f7 just `3 weeks ago`


@0x-r4bbit @jrainville Any concerns closing this ticket based on evidence gathered above ?

**Comment by 0x-r4bbit** [comment]
@kounkou Let me start by saying that this is one of the best "let me try to reproduce this" reports I've seen. You've clearly done your homework!

Judging by the analysis you've done, I think we're good to close this.
