### ISSUE TITLE
[Mint / airdrop tokens] Airdrop item not inserted correctly

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11147]
# Bug Report

## Description

When user navigates from mint view to airdrop, one entry of the selected token should be added in the form, but there is no entry added.

## Steps to reproduce

1. Open an account with some minted community collectibles
2. Go to `Mint Token` section in community settings
3. Open one of the collectibles item
4. Click on `airdrop` footer option

#### Expected behavior
Airdrop view is reset and only 1 token entry is added. The token type from where we started the navigation.

#### Actual behavior
No token entry is added.

**NOTE:** Take into account that there can be multiple navigations to airdrop so:
- User can go back to `Mint Token` section in community settings ( app will navigate back to the token that was open before)
- User can click again on `airdrop` footer option

Airdrop form must be reset properly.

### Additional Information

- Status desktop version: master commit **54ae6a31546b75d36e6f21447a5f6a1af124e922**. It will be in release _0.13-RC1_
- Operating System: macOS - Monterey 12.3.1

https://github.com/status-im/status-desktop/assets/97019400/e84f33fb-03fd-498e-92e9-61804fcd7415

**Comment by John-44** [comment]
@noeliaSD at 0:03 in the video above, I noticed that the "Remotely destruct" option in action bar at the bottom of the body area was active, even though there are "No hodlers just yet".  If nobody is hodling any of the token, this button should be in the inactive state (because there are no tokens in existence to remotely destruct).  If there isn't an open issue for this, would you be able to open this as a new issue?  Thanks!
