### ISSUE TITLE
Fill community_tokens table when restoring account

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#11188]
After restoring account the community owner should see his deployed contracts.
We need to check all community tokens info from CommunityDescription and fill the community_tokens table.

**Comment by 0x-r4bbit** [comment]
After some investigation here are some updates on this issue:

1. When we restore accounts (and their communities, profile etc) we're relying on backedup sync messages. It turns out we're also syncing/backing up the private keys of communities. While the sync message itself is encrypted as well, I think there was a discussion to maybe remove the private key from there altogether. I assume for this task we still want to rely on it though
2. Simply listening to backup data and recovering community tokens from the community description is unfortunately not going to work because we're not storing all relevant information in the community description
3. Because of 2), this task needs to be extended to introduce a new `SyncCommunityTokens` message type which will be emitted separately during backups and then handled/recovered later on
