### ISSUE TITLE
Retry and Delete contracts options

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#11186]
Retry and Delete buttons were added to the design. They are already added in UI, but disabled/hidden.

Figma:
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=29528-590685&t=52upMdOoworXuukv-0

When the deployment fails, user should see his failed smart contract. He should be able to try to deploy again by pressing "Retry". He also should be able to delete the contract from the list by pressing "Delete".

We should change a bit deployContract() function. We add to the list contracts with failed state, when transaction is failed. However when status-go deployment function is failed there is an exception and the contract is not added to database. We should additionally handle this case.
I think that failed contracts should not be added to waku. I see it rather as a local information. So probably we need to add a failed contract to database (in order to see it on the list), but not to waku. Then, "Deleting" contract will be only removing it from database.

Also we need to prevent airdropping and burning of failed contract.

**Problematic issue**
We have a field in the model called "contractUniqueKey" which is a string "chainId_contractAddress" (function contractUniqueKey() in common/utils). It is used by UI and for UI - logic interaction. In case of exception we may not have contractAddress. Maybe we should put in contractAddress field something like "failed_randomHash" to have some random id. It's just a quick idea.

**Comment by jrainville** [comment]
@endulab can you add more details to this issue? Is this only to delete it or also retry?
Also, is there already a UI for it?

**Comment by 0x-r4bbit** [comment]
Had a discussion with @endulab about this, as some of the description conflicts with what currently exists.
We've concluded the following plan of actions:

1. First of all, make the call to `deployContract` (assets/collectibles) asynchronous. Currently it's synchronous and due to how the underlying API works, either the whole thing fails or not, which means, you can't really end up the error state view because the code returns early
2. Once async, ensure we still create an entry in the database with tx pending state. This lets users then view/enter their currently in-deployment token
3. Add tx hash to `community_tokens` table. Technically this is not necessarily an absolute requirement, but based on how the underlying deployment API works, we only get a contract address when deployment was successful. If the deployment is pending or fails, we still need a way to identify the entry in the database in case people hit retry or delete. In such cases we can make use of the tx-hash as an ID
4. When "delete" is hit, remove the entry from the database
5. When "retry" is hit, also remove the entry from the database, then reinitiate deployment (all async of course)

**Comment by 0x-r4bbit** [comment]
I'm running into issues making the underlying API async. All of our async tasks receive their arguments as string and are then decoded, so they can be passed to RPC calls.

Here's what it would roughly look like for our `deployCollectibles()` API:

```nim
type
  DeployCollectiblesArg = ref object of QObjectTaskArg
    chainId*: int
    deploymentParams*: DeploymentParameters
    txData*: TransactionDataDto
    password*: string

const deployCollectiblesTaskArg: Task = proc(argEncoded: string) {.gcsafe, nimcall.} =
  let arg = decode[DeployCollectiblesArg](argEncoded)
  try:
    let response = community_tokens.deployCollectibles(arg.chainId, %arg.deploymentParams, %arg.txData, arg.password)
    if not response.error.isNil:
      raise newException(ValueError, "Error deployCollectibles" & response.error.message)
    let output = %* {
      "result": response.result,
      "error": ""
    }
    arg.finish(output)
  except Exception as e:
    let output = %* {
      "result": "",
      "error": e.msg
    }
    arg.finish(output)
```

^ This pattern (define `*TaskArg` + task) is what we're currently doing for all `async*` methods.

The problem here is however that the `TransactionDataDto` has a field that uses the `Address` type of the `web3/ethtypes` package.

The code above will not compile, as the compiler will complain with:

```
/home/rabbit/projects/status-im/status-desktop/vendor/nim-json-serialization/json_serialization/reader.nim(669, 12) Error: Failed to convert to JSON an unsupported type: Address
```

This is because the `decode()` call doesn't know how to serialize the `Address` type.
Luckily, there's a `web/conversions` package, which implements `JsonReaders` and `*Writers` for `Address` as:

``nim
proc writeValue*(w: var JsonWriter, v: Address) =
  writeHexValue w, distinctBase(v)

proc readValue*(r: var JsonReader, T: type Address): T =
  fromHex(T, r.readValue(string))
```

So importing `web3/conversions` should fix this.

Unfortunately, after doing that, the compiler now complains with:

```
/home/rabbit/projects/status-im/status-desktop/vendor/nim-serialization/serialization/object_serialization.nim(133, 16) Error: undeclared field: 'val' for type readValue.T [type declared in /home/rabbit/projects/status-im/status-desktop/vendor/nim-json-serialization/json_serialization/reader.nim(612, 10)]
```

It looks like as if it's not even trying to use the correct reader.

@arnetheduck any idea what's going on here?

**Comment by 0x-r4bbit** [comment]
All of this got way simplified:

1. No need to make the deploy calls async as they aren't blocking on pending transactions, they return successfully with a tx hash and a contract address. Tx state is then periodically checked to update community token's deploy state later on
2. Changed logic in `AddCommunityToken()` and introduced `SaveCommunityToken()` such that we can store an entry for the to-be-deployed token in the database, and later publish it on the community description once successful (currently it optimistically publishes community tokens) https://github.com/status-im/status-go/pull/3798 and https://github.com/status-im/status-desktop/pull/11664
3. Introduced an API to remove community tokens from the database (this does not remove it from the community description as we only put successfully deployed tokens there and we can't really remove them) https://github.com/status-im/status-go/pull/3794 and https://github.com/status-im/status-desktop/pull/11653
4. Combined the above to put together the retry functionality https://github.com/status-im/status-desktop/pull/11668
