### ISSUE TITLE
[Mint Token] Footer options must be disabled until minting process is completed

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#11198]
# Bug Report

## Description

Depending on the token minted configuration there are some footer options (airdrop, remotely destruct and burn). These options must be disabled until minting process is completed

## Steps to reproduce

1. Navigate to community settings / Mint tokens
2. Mint a token
3. Click on the token is being minted to navigate to its summary screen.

#### Expected behavior
- While `Collectibe is being minted` text is shown on top of the artwork, footer options are disabled.

#### Actual behavior
- While `Collectibe is being minted` text is shown on top of the artwork, footer options are enabled.

![Screenshot 2023-06-21 at 08 52 59](https://github.com/status-im/status-desktop/assets/97019400/299ecda2-920a-46c6-bdfd-7ae02e9a7738)

### Additional Information

Status version: **0.13.0 RC2**

**Comment by John-44** [comment]
@noeliaSD see my comment here https://github.com/status-im/status-desktop/issues/11147#issuecomment-1601720373

My comment is talking about something slightly different.  If (for example), the token is minted, and then say 5 tokens are airdropped, "Remotely destruct" should be active.  But if all 5 of these tokens are then remotely destructed, then the "Remotely destruct" button should become inactive again because there are no instances of this token in existence that can be remotely destructed.

So I think this button being active should be tied to "are there instances of this token in existence that can be remotely destructed?", not has the token minting been completed or not.

Of course the "Airdrop" button should always be active as long as:
A) the 'minting' (contract deployment) of the token is complete

AND

B) there are tokens available to airdrop (e.g. this button should become inactive again if the token has a finite supply, and 100% of that finite supply has already been airdropped, so there are no tokens remaining to airdrop).

So the logic that determines if the "Airdrop" button is active/inactive and if the "Remotely destruct" button is active/inactive should be different.

**Comment by noeliaSD** [comment]
Here are all cases described:

- Airdrop disabled bc no remaining tokens:
![Screenshot 2023-06-22 at 07 48 52](https://github.com/status-im/status-desktop/assets/97019400/33eb2496-44c7-40d2-b194-57ad7780fe32)

- Airdrop disabled bc no remaining tokens AND remotely destruct enabled bc of there are hodlers:
![Screenshot 2023-06-22 at 07 59 20](https://github.com/status-im/status-desktop/assets/97019400/2790a601-a45e-4e88-b289-8ac42303bd8a)

- Remotely destruct disabled bc no hodlers:

![Screenshot 2023-06-22 at 07 47 49](https://github.com/status-im/status-desktop/assets/97019400/c626f250-e724-43a3-b330-f60edf455281)
