### ISSUE TITLE
Onboarding -> I am new to Status -> Import seed: Fetching data screen is missing

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11194]
### Description

`Fetching data` screen is not present for onboarding flow starting with `I am new to Status`

Steps:
1. open app
2. click I am new to status
3. select import seed option and proceed

**Expected:** Fetching data screen is present

<img width="1468" alt="Screenshot 2023-06-20 at 18 31 04" src="https://github.com/status-im/status-desktop/assets/82375995/74e9ef14-11fa-474b-9496-c22e9e2cc768">

**Comment by anastasiyaig** [comment]
@alaibe is it for our team? :)

**Comment by alaibe** [comment]
Yes it should be for our team

**Comment by saledjenic** [comment]
@anastasiyaig I've checked this, the reason why you do see this weird issue is that we changed the format of backed up messages for wallet accounts. We're backing up keypair which contains all related accounts as a single message now and each watch only account as a single message, but all that with more details that it was before.

That's the reason and that will be solved by itself after 30 days (cause messages are stored on waku for 30 days) from the last backed up message in old format. We could add some handling for that in order to be backward compatible but at this point of time it's not need, cause we're still in the development phase and adding it will just bloat the code, after mvp being backward compatible will be a must.

Just keep this somewhere aside and check it in one month.
