### ISSUE TITLE
Sync wallet account positiion & hide watch only

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#11395]

**Comment by saledjenic** [comment]
@alaibe this should be fixed in this PR https://github.com/status-im/status-desktop/pull/11457, as part of #11268.

Though I've noticed some wonky behaviour of account reordering feature, like it doesn't work smoothly, gets stucked if you want to move an account the the first/last place. Also underlying accounts don't move while I'm hovering over them dragging an account I want to move to a new position. But anyhow a position is dispatched to paired devices and this will be handled in a new issue, cause it's more local desktop thing.
