### ISSUE TITLE
Attached image in community message is not visible in chat

### ISSUE THREAD

**Issue by StateOf-Vlado** [status-im/status-desktop#11401]
# Bug Report

## Description

The image can be attached to the community message, but it is not sent on not visible in the sent message

## Steps to reproduce

1. Open any community chat
2. Attach any image to the message and send it

#### Expected behavior
The message contains the image in the chat log

#### Actual behavior
The message was sent without the image

### Additional Information
https://github.com/status-im/status-desktop/assets/128374224/3d0f53bb-70d7-44f7-abbf-62736a49096e

- Status desktop version:
master build: b3625cceed0e444553394051bed97a567bc43ec5
- Operating System:
Ubuntu 20

**Comment by anastasiyaig** [comment]
cant reproduce on mac btw

<img width="1552" alt="Screenshot 2023-07-04 at 17 11 19" src="https://github.com/status-im/status-desktop/assets/82375995/9435ab64-56bc-4556-8049-f39cafb26509">

**Comment by 0x-r4bbit** [comment]
Sending images on latest master seems to be broken entirely at the moment.

**Comment by 0x-r4bbit** [comment]
Okay I found the culprit.
There was a change in https://github.com/status-im/status-desktop/commit/9aeba367dfd3ce56209c4e08a954e0c0ce45f748 related to image retrieval before sending messages.

The change in itself is fine, but it breaks sending messages if DOtherside isn't forced updated.
I tired this locally and couldn't send any images because the `tmp` images being created didn't have any data.
After forcing a rebuild of DOtherside, this worked fine (so I probably said on a version that was older than https://github.com/status-im/status-desktop/commit/9aeba367dfd3ce56209c4e08a954e0c0ce45f748). 

At this point I can no longer reproduce this.

@StateOf-Vlado can you confirm this after forcing a rebuild of DOTherside?

**Comment by caybro** [comment]
Yeah, I can't reproduce either, it's a build issue

**Comment by jrainville** [comment]
I can't reproduce either.

**Comment by jrainville** [comment]
I'll close. @StateOf-Vlado reopen if you can reproduce on master after forcing a DOtherSide rebuild. Post your logs if it happens
