### ISSUE TITLE
Clicking red cross close button does not close the app but collapse it (with no opportunity to open again)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11405]
### Description

1. open app 
2. click red cross button (mac)

As result, the app is collapsed to task bar but still running. Expanding the app by clicking it again is not possible as there is no active window.

**Comment by igor-sirotin** [comment]
Oh I think I've faced the same. Just didn't catch that it was the red button that caused this behaviour.

**Comment by igor-sirotin** [comment]
This is also reproducible when hiding the app with `cmd+W`. Very annoying 🙁

**Comment by igor-sirotin** [comment]
I spent some time trying to fix this. I got some success, but couldn't yet fully fix it.
Fixing the results below to get back to this later.

# Current results

First, I figured out that the bug is not reproducible with `0.12.0`, even built locally with same Qt version.
After looking though diffs, I found the problem.

https://github.com/status-im/status-desktop/pull/11049 introduced an `NSApplication` instance for our app. This somehow influenced the default window behaviour. To make the window restoring I added this method to `AppDelegate` class:
```objc
- (BOOL)applicationShouldHandleReopen:(NSApplication *)theApplication 
        hasVisibleWindows:(BOOL)visibleWindows
{   
    auto window = theApplication.windows[0];
    if (visibleWindows) {
        [window orderFront:self];
    }
    else {
        [window makeKeyAndOrderFront:self];
    }
    return YES;
}
```

Having this done the window restores fine from dock. But it doesn't respond to any mouse events after that.
To fix this we add another function:
```objc
- (void)applicationDidFinishLaunching:(NSNotification *)notification
{
    NSApplication* app = notification.object;
    app.windows[0].releasedWhenClosed = YES;
}
```

Unfortunately, this didn't help and I'm not sure what to try now.
Will return to this a bit later with fresh mind. Or maybe we have some objective-c experts around 🙂 

# Workaround

Clicking the tray icon restores the window 👌 
Less annoying then restarting the app.

**Comment by caybro** [comment]
`git blame` points at our local obj-c expert @borismelnik ;)
