### ISSUE TITLE
Persist selected filter for an account

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#11412]
Filtering should persist for each wallet account separately even when moving to other views.

### Current behaviour:

* Go to `Account 1` activity list
* Select any filtering (e.g. Type - Send)
* Go to `Account 2` activity list
* Same filter is applied

### Expected bahaviour:
* Go to `Account 1` activity list
* Select any filtering (e.g. Type - Send)
* Go to `Account 2` activity list
* No filtering is applied
* Select any filtering (e.g. Status - Failed)
* Got back to `Account 1` activity list
* Type - Send filtering is applied
* Go back to `Account 2` activity list
* Status - Failed filtering is applied

**Comment by John-44** [comment]
> 1 - I don't think it is necessary to sync the current state of filtering for an account's activity across synced devices but perhaps @John-44 can confirm. The filters are relatively easy to apply, edit and remove and it's unlikely someone will wish applied filters to persist long term (at least I can't think of a widespread use case that would warrant syncing the filtering state across devices - it doesnt save the user a lot of time and might actually be jarring to log in using another device and find filtering pre-applied when I'd be expecting a clean slate).

@Cuteivist I haven't, because I haven't had time to read my github alerts for a while, but I've seen it now :-)  If there is an issue that needs my attention and I don't respond, please chase me on Status or Discord ;-)

Anyhow, re. these questions:

1) Filter state should **not** be synced across devices, and should not persist across sessions.   Should be stateful *inside* a session only.

2) I *think* everything in the db is always encrypted (so this happens by default, but re. should 'specific wallet address + filters' be encrypted, I'll leave this question for @alaibe
