### ISSUE TITLE
Owner must 5 min wait for admin events on a startup before updating CommunityDescription

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#11554]
### Description

If the owner was offline for a certain amount of time, and when he'll be back, he will process the first received admin events and update CommunityDescription clock.
This means, if there will be other CommunityEventsMessages, they will be rejected by the owner, which is not good as this will rollback other admin changes

The idea is for a startup to collect a CommunityEventsMessage's for a certain amount of time and post updated CommunityDescription with all updates

P.S. Need to figure out how to do it correctly, as there could be other messages which can lead to updating CommunityDescription clock

**Comment by osmaczko** [comment]
_The described issue is not exclusive to startup; it's a general problem for which we need a better solution than a workaround with an initial delay._

We don't have control over when messages that may trigger a `CommunityDescription` update arrive. For instance, upon startup, the control node may receive a membership request before `CommunityEventsMessages`. Furthermore, the control node itself may update `CommunityDescription` without any external event due to an initial permissions check.

Given the above, implementing a mechanism that delays `CommunityDescription` updates is not straightforward and would introduce significant complexity.

**Comment by osmaczko** [comment]
Closing, it will be solved by https://github.com/status-im/status-desktop/issues/11552.

As discussed offline with @cammellos, the current solution isn't optimal and could pose problems if the control node goes offline for an extended duration and accumulates many admin events. This could lead to a back-and-forth scenario where numerous admin events get rejected simultaneously.

A better approach would be to publish control node changes in the form of events, mirroring the admin procedure. Essentially, we'd always communicate changes through events, complemented by a separate loop that creates checkpoints (aka `CommunityDescription` updates) at fixed intervals.
