### ISSUE TITLE
Owner must acknowledge the admin about the rejected event due to the CommunityDescription clock change

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#11552]
### Description

We can't guarantee, that 2 admins won't send 2 events at the same time. If it will happen, we can face with next situation:
1. A1 sent E1
2. A2 sent E2
3. Owner receives A1 E1 and updates CommunityDescription clock and publishes CommunityDescription msg
4. Owner receives A2 E2 and rejects it as the CommunityDescription clock is outdated

If the owner will reject the A2 E2 event, A2 must acknowledge, that his CommunityEventMessage was rejected and try to resend it with an updated CommunityDescription clock

**Comment by osmaczko** [comment]
This needs clarification why the event needs to be resend by admin rather than simply applied by control node. In other words, what's the difference between:

A) control node rejects event X -> admin sends event X again but on top of new community description
B) control node doesn't reject event X  -> and applies event X on top of new community description

**Comment by osmaczko** [comment]
> This needs clarification why the event needs to be resend by admin rather than simply applied by control node.

The justification is here: https://notes.status.im/B8FApTVZRP6RKWTp0MD8eg?view

**Comment by osmaczko** [comment]
On hold, requires: https://github.com/status-im/status-desktop/issues/11834

**Comment by osmaczko** [comment]
Still on hold, now requires: https://github.com/status-im/status-desktop/issues/11859
