### ISSUE TITLE
Long delays on unfurling community links

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#11587]
# Bug Report

## Description

Long delays have been seen on having community links unfurl. While the link is loading it cannot be used to reach the community. 
![image](https://github.com/status-im/status-desktop/assets/50769329/8571eccc-65d7-4166-a57e-ee65ae7bb6a0)

Attempts at restarting seem to make no difference. Also unexpectedly, the issue has also been seen on the control node for the community where the data to unfurl would be coming from anyway.

## Steps to reproduce

Share a link to a community in a chat. Observe how long it takes to unfurl and become usable.

#### Actual behavior

Delays un unfurling community URLs do not prevent users from reaching a community.

### Additional Information

- Status desktop version: Master
- Operating System: Mac

**Comment by anastasiyaig** [comment]
@jrainville please add an epic here

**Comment by jrainville** [comment]
This is a known issue/incomplete feature. 

Once https://github.com/status-im/status-desktop/issues/10852 is going to be completed, this shouldn't be an issue.

The problem is we changed how we give the URLs to the UI, but we didn't change yet unfurling component.

I do understand that it's an issue when trying to test stuff. I had to manually revert the change in my branch to be able to add someone as a contact.

@borismelnik do you know how long it will take to fix #10852? If it takes more than a few days, it might be worth to revert the original change until then, because it makes it hard to test.

**Comment by jrainville** [comment]
@glitchminer can you try again on master. The issue should resolved now that the UI part of the share URL issue was completed

**Comment by glitchminer** [comment]
No longer reproducible, closing.
