### ISSUE TITLE
Missing community messages when re-joining

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#11686]
Community-level encryption:
1. Create token-gated community - ✓
2. Join with MemberA who satisfies the criteria - ✓
3. Send message "X" to general channel - ✓
4. MemberA should see the "X" message - ✓
5. Change token permissions so that MemberA no longer satisfies the criteria - ✓
6. MemberA should be kicked from the community - ✓ 
7. Send message "Y" to general channel - ✓
8. Change token permissions so that MemberA once again meets the criteria - ✓
9. MemberA should be ~~re-added to the community - X (user has to manually re-join)~~ able to manually re-join
**10. MemberA should see both "X" and "Y" messages - X (only sees "X")**
11. Send message "Z" to general channel - ✓
12. MemberA should see "X", "Y" and "Z" messages - X (only sees "X" and "Z")

_Originally posted by @lukaszso in https://github.com/status-im/status-desktop/issues/11657#issuecomment-1650700759_
            
 I believe it happens also on non token-gated communities.

**Comment by igor-sirotin** [comment]
Might be related: https://github.com/status-im/status-go/issues/3869

**Comment by igor-sirotin** [comment]
The issue is reproduced in many different ways (at least I think it's the same issue).
In all cases application restart helps.

### Prerequisites:
1. Admin: Create a community
    - community history service: `no`
    - request to join: `yes` (I suppose it's not required to reproduce, didn't test yet)
2. Admin: Share community with User

### 1️⃣ Last messages of spectated communities

1. Admin: Send a message `X`
2. User: Spectate the community
3. User: No message `X` visible ❌ 
4. User: restart the app
5. User: Message `X` visible ✅ 

### 2️⃣ Message in closed spectated community

1. User: Spectate the community
3. Admin: send message `X`
4. User: message `X` visible
5. User: Close the community
6. Admin: send message `Y`
7. User: Spectate community again
8. User: no message `Y` visible ❌
9. User: restart the app 
5. User: Message `Y` visible ✅ 

### 3️⃣ Leave and spectate community

1. User: Send request to join
2. Admin: Accept request to join
3. Admin: send message `X`
4. User: message `X` visible
5. User: Leave the community
6. Admin: send message `Y`
7. User: Spectate community (or event join the community)
8. User: no message `Y` visible ❌
9. User: restart the app 
5. User: Message `Y` visible ✅

**Comment by igor-sirotin** [comment]
1. I wasn't able to reproduce any of cases from my comment above.
2. I wasn't able to reproduce original issue as well.

But I faced a similar (but different) issue.

1. Stage 1. Prerequisites:
    1. admin: Create a community:
        - no history service
        - no request to join
        - `10 STT` to become a member
    2. user: Aquire `20 STT`
    3. admin: Share the community with user
    3. user: Auto-join the community
2. Stage 2. Message `X`.
    1. admin: send message `X` to `#general`
    2. user: receives message `X` ✅ 
2. Stage 3. Message `Y`.
    3. admin: change permission to `30 STT`
    4. user: auto-kicked from community
    5. admin: send message `Y`
2. Stage 3. Message `Z`.
    7. admin change permissions to `11 SNT`
    8. user: re-join community
    9. user: no messages here ❌ 
    10. admin: send message `Z`
    11. user: receives message `Z` ✅  
    12. user: only has message `Z` (should be `X`, `Y` and `Z`) ❌

**Comment by osmaczko** [comment]
> X and Y messages disappear from the database after being auto-kicked

This seems incorrect; I don't know the exact UI flows, but if a user is removed, they should become a spectator and still be able to read all previous conversations. Nevertheless, even if messages are removed, they should be retrievable upon rejoining.
