### ISSUE TITLE
Backup community after admin events

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#11713]
### Description

If the admin event will be propagated and  it will be not certified by the control node, all users and members (not the control node) will keep CommunityDesctiption without the control node signature

This CommunityDescription can be synchronized or backuped without the control node signature
We need to find the best option how to handle this. Here are some ideas
- before backuping/syncing do a verification that we do not backup/sync unsigned CommunityDescription
- do not keep unsigned CommunityDescription (this will require on each community request from db to restore the current state and track that we never save or backup/sync restored community)
- if it is unsigned - take CommunityDescription from the `EventData` struct (we keep here CommunityDescription on top of which the first event was generated)

Would be nice to have some discussion and find the solution, but we will need some person who is familiar with the backuping/syncing code in order to understand pros and cons of this or those solutions

**Comment by mprakhov** [comment]
cc @jrainville @osmaczko

**Comment by jrainville** [comment]
Should only the control node do the backup? If that's so, we don,t have much to do. We'd only need to ensure that only the control node, that has a signed description can back up the description.

If there is an owner node without the private key, they shouldn't back up.

**Comment by mprakhov** [comment]
> Should only the control node do the backup? If that's so, we don,t have much to do. We'd only need to ensure that only the control node, that has a signed description can back up the description.
> 
> If there is an owner node without the private key, they shouldn't back up.

What about the case, when we are the users/admins?

**Comment by jrainville** [comment]
> What about the case, when we are the users/admins?

I don't know that code that well, but I thought only owners used to back up. We don't need every people in the community to backup the community to waku, that would spam the network

**Comment by jrainville** [comment]
I looked at the code and it seems like indeed we backup all communities a user has joined. 

I wonder if instead of backing up all the community description, we should just back up the id, then fetch it? 

Firstly, it would fix the issue described above.

Secondly, it would be lighter for the network.

The downside is that it would be slower for the user, because they would need another store node fetch, but it seems reasonable.

It's a little more work for us, because we'd need to rework the back of communities, but the code to fetch communities from store nodes already exists.

I might be missing details though, so do let me know if it makes sense

**Comment by jrainville** [comment]
> For now, I see only 1 corner case: If the control node will lost his community key or will be offline - the community won't be backuped. So when some user will restore his account by seed phrase - he'll get the old CommunityDescription. But maybe this is ok...
> 
> P.S. In my understanding - the community must have the possibility to "live" even if the control node is "dead" :) But I can be wrong

In theory, once the control node comes back online or just sends an updated version, the member would update to the latest. 

The same corner case could happen with the current backup. If the member was last online one week ago, did a backup and then re-syncs, they'll have a week old community description. They'll need the new one.  

As for the community being able to live when the control node is dead, that is true, up to a certain point. It should be the case for small periods of time, but if the control node never comes back online, the community is basically doomed, because no new users can join, the history archive will stop working and even the ratchet keys will stop to be rotated.

So as for this particular corner case, I think my solution is ok.

**Comment by osmaczko** [comment]
> * do not keep unsigned CommunityDescription (this will require on each community request from db to restore the current state and track that we never save or backup/sync restored community)

I am opting for that option. As I've been saying from the start, we shouldn't store unsigned `CommunityDescription` message in the database. This not only causes syncing issues but I also believe it can lead to problems in various scenarios. I haven't tested this, but I am pretty sure that sharing community won't work if we have unsigned `CommunityDescription` in the database. We use `ShareCommunity` when inviting users to the community. AFAIK admins can invite users to the community. Consider the following stack trace:
```
community.ToBytes
sendChatMessage
SendChatMessage
SendChatMessages
ShareCommunity
```

If an admin sends an unsigned `CommunityDescription`, it will fail on the receiver's end, thus preventing users from viewing the invitation.

> I wonder if instead of backing up all the community description, we should just back up the id, then fetch it?

That's a good idea. It could also be applied to the `ShareCommunity` logic, i.e. instead of sharing whole `CommunityDescription` we could just share the id. With that in place, we wouldn't need to store signed `CommunityDescription` in the database anymore.

**Comment by jrainville** [comment]
> With that in place, we wouldn't need to store signed CommunityDescription in the database anymore.

I guess you made a typo here and meant `unsigned `CommunityDescription`? @osmaczko

**Comment by osmaczko** [comment]
> > With that in place, we wouldn't need to store signed CommunityDescription in the database anymore.
> 
> I guess you made a typo here and meant `unsigned `CommunityDescription`? @osmaczko

No typo here. We store signed community description mainly to be able to share it with others. If we change the mechanism to share only the ID, then we don't need to store signed `CommunityDescription` message, we could store pure (aka not signed & not wrapped in message) `CommunityDescription` in the db.

**Comment by iurimatias** [comment]
moving to 2.29 due to lack of space in this milestone, however this could be done in the stabilization period with other refactors if there is room

**Comment by jrainville** [comment]
> That's a good idea. It could also be applied to the ShareCommunity logic, i.e. instead of sharing whole CommunityDescription we could just share the id. With that in place, we wouldn't need to store signed CommunityDescription in the database anymore.

We no longer use that ShareCommunity API, or if we do, we only pass it as a link instead of passing the whole community, so the receiver needs to fetch it

**Comment by kounkou** [comment]
Closing this issue. Rational for future reference is below :

In summary, we should drop the ticket because merely saving the community ID and fetching the full description when needed isn't sufficient. We also need to back up other fields such as whether the community is joined, spectated, or muted. Attempting to fetch the entire description from store nodes would introduce two-step fetching, synchronization problems, and added complexity. Therefore, it's better to retain the current implementation, where only signed community descriptions are backed up in the database.
