### ISSUE TITLE
Able to send reaction in token gated communities

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#11915]
Members not yet approved in the communities are able to send reaction to message

Expected: they should not be able to react

**Comment by shinnok** [comment]
Hi,

I cannot reproduce this on latest dev, on a test Community, with existing or new messages, neither with mouse hover nor right click.

https://github.com/status-im/status-desktop/assets/544446/6db1dd26-fe01-44f2-afb4-2c6f5020475f

**Comment by shinnok** [comment]
@jrainville I re-enabled the chat input by commenting out the piece below and I was able to send messages to a community without having joined yet:

https://github.com/status-im/status-desktop/blob/29629a3d6d708b0c400772bc2a8f0a01bb6e54a1/ui/app/AppLayouts/Chat/views/ChatColumnView.qml#L260-L267

As for the best place to block this in the back-end, I'm currently investigating in status-go PR https://github.com/status-im/status-go/pull/4064.

**Comment by jrainville** [comment]
Nice find @shinnok .

So we should block that both on sending side, but most importantly on receiver side, so that if someone clones the repo and "hacks" the sending code, we still don't accept messages from non-members.

I recommend using the Go tests available in status-go. They are very powerful (you can debug) and way faster than running the app.

Let me know if you need some coaching on them. All members of the messenger team know how they work, so you can reach out to any of them.

**Comment by igor-sirotin** [comment]
related: https://github.com/status-im/status-go/issues/3869
