### ISSUE TITLE
Community: device is not recognised as Control node when community is recovered (owner token is present)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#11932]
### Description

1. create community
2. mint owner token and token master token for it
3. back up seed phrase
4. delete your data folder and restart the app
5. recover the account with the seed 
6. in the community that will be recovered for you, open overview page, airdrops page and tokens page

**As result:**
1. device is not recognised as control node
2. there is Mint owner token on Airdrops page
3. minting tokens is not possible

https://github.com/status-im/status-desktop/assets/82375995/bd60cf79-a2c6-4f86-a190-a071787e8ecc

<img width="1557" alt="Screenshot 2023-08-17 at 17 15 59" src="https://github.com/status-im/status-desktop/assets/82375995/64a292f3-4262-4289-b006-e498340e9b94">
<img width="1557" alt="Screenshot 2023-08-17 at 17 16 05" src="https://github.com/status-im/status-desktop/assets/82375995/ecea1712-83f3-43f8-abe3-b539ec48f7d1">
 <img width="1557" alt="Screenshot 2023-08-17 at 17 16 19" src="https://github.com/status-im/status-desktop/assets/82375995/43d1e2ee-f9fb-4c35-8d91-67407832b423">

**Comment by jrainville** [comment]
This is not a bug, but  a "feature" :sweat_smile: 

We removed the back up of the private key on waku, so it's normal that you are not recognized as a control node.

The tokenized ownership is going to be done in 0.15.

For now, having the Owner token is just a way to make sure on chain that only owners and tokenMasters can deploy and mint community tokens.

The only way to become a control node again is to import the community's private key. If you didn't back it up before deleting the data folder, then that community is lost sadly.

**Comment by anastasiyaig** [comment]
oh my , so even i have Owner token - it is still like that? what is the token for then :D @jrainville

**Comment by anastasiyaig** [comment]
alright ! @endulab seems it is expected

**Comment by jrainville** [comment]
> oh my , so even i have Owner token - it is still like that? what is the token for then :D @jrainville

It's an on-chain validation mechanism to make sure that only accounts that are Owner or TokenMaster can interact with community tokens.

For example, if there is the token called StatusCommunityToken that is for the Status Community, we not only do a check in our code to make sure that no one can mint that token except Owners and TokenMasters, but the OwnerToken And TokenMaster contract is also checked, so it's more rigourous.

It is also the first step for the ownership tokenization. So yes, later, hopefully in 0.15, having the Owner token will mean you can be the control node.
It's just not that simple because the whole backend works with a community private key right now, so it's not easy changing it to using a user's key instead.
