### ISSUE TITLE
[Community Ownership] new Owner should ask members for addresses

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#11969]
Dependent on https://github.com/status-im/status-desktop/issues/11972

At present, only the control node stores the revealed addresses of members. When ownership is transferred to a new owner, this new owner doesn't have access to these revealed addresses. To perform permissions checks, the new owner must request members to reveal their addresses again. ~~Maybe we could introduce a cool-down period, potentially 24 hours, during which members are not kicked for not having revealed their addresses immediately after an ownership transfer.~~ All members should be kicked and asked to rejoin with revealed addresses. This should happen automatically without members interaction. The community will rebuild itself silently when members become online. If control node is offline members should be informed with something like: "The community owner has changed, you will be added back to the community when the control node goes back online".

NOTE: _Although the new owner can approach the previous owner to obtain the revealed addresses, this method poses a security risk. The former owner could send malicious addresses or may no longer be trusted._

### Acceptance criteria:
- [ ] new control node should kick all members and ask them to rejoin with revealed addresses
    - [ ] clients should send request to join automatically without user interaction
- [ ] users should be notified if they have been removed due to owner change and are waiting for control node to become online to accept their request to join
~~- [ ] permissions check should be done after cool-down period, so that members have time to send addresses~~

**Comment by mprakhov** [comment]
Discussed the proposal solution with @osmaczko, we want to change the behavior and need feedback from you

Taking into account, that the new community Owner will not have a revealed address of other clients, if we use a cool-down period of 24h for clients to share their accounts, all clients will have the possibility to access the secret chats, for example (permission check must be disabled for this 24 hours)

The proposal is to kick all members (as I understand, they must stay in spectator mode) and send a specific message to the client that he was kicked. When the client receives this msg, we can:

- option 1: Handle this msg and make an automatic request to join. 
Cons: if the community was ON_REQUEST - it must be manually approved

- option 2: Handle msg and show in the UI (activity notification?) that the community Owner was changed and he needs to rejoin the community

@jrainville @osmaczko @John-44 @cammellos what are your thoughts?

**Comment by jrainville** [comment]
> Taking into account, that the new community Owner will not have a revealed address of other clients, if we use a cool-down period of 24h for clients to share their accounts, all clients will have the possibility to access the secret chats, for example (permission check must be disabled for this 24 hours)

I don't think every one will have access to the secret channels.

I think we can just make it so that in that 24h window, the member lists don't change, nor the encryption keys for the channels. In other words, in that period, nothing changes. No new community description, apart to signal that the owner changed I guess.

We do still have the issue that some people will not be online when the change will happen, even within 24 hours, so yes, these people would end up being kicked if the community has a join permission.

IMO, we should do option 1, but we could improve it further.
Maybe the new control node could keep in their `requestToJoin` table the list of users that were kicked because of missing addresses. Like a new state `rejectedBecauseMissingAddresses`.
That way, when the user comes back online and it automatically sends the shared addresses (the same ones that were used previously), the control will see that this user was not kicked because of bad behaviour, but because of the change of owners. It would then auto-accept the request.

What do you think? It's a little more work, but the UX would be way better, since not much is to be done by the user nor the owner/admins.

**Comment by mprakhov** [comment]
If it would be possible, I would like to have this community owner change to be more event-based without any cool-down periods for anything (it will be a complex change, especially on status node startup)
And keeping `requestsToJoin` and having a separate status for it looks ok for me

**Comment by John-44** [comment]
> Maybe the new control node could keep in their `requestToJoin` table the list of users that were kicked because of missing addresses. Like a new state `rejectedBecauseMissingAddresses`.
> That way, when the user comes back online and it automatically sends the shared addresses (the same ones that were used previously), the control will see that this user was not kicked because of bad behaviour, but because of the change of owners. It would then auto-accept the request.

This seems like a good improvement.

@osmaczko @mprakhov @jrainville to double check, all of the revealing addresses to the new owner would be automatic and happen without user interaction (other than one of the user's Status devices needing to be online), correct?

**Comment by jrainville** [comment]
> @osmaczko @mprakhov @jrainville to double check, all of the revealing addresses to the new owner would be automatic and happen without user interaction (other than one of the user's Status devices needing to be online), correct?

As long as the member had shared addresses before, then yes. because members store their own shared addresses in their own database, we could just have a signal from the control node to the member saying "give me your addresses again please" and the member node would just send it back in the background.
So nothing to do from the user side.

The only annoying thing that might happen however is if this becomes fully async, in the case where the member and control node are never online at the same.
Example:
1. Control node changes owner
2. Members get kicked but put in the special category of `rejectedBecauseMissingAddresses`
3. Control node sends the signal to members to get the shared addresses
4. Member is offline
5. Control node goes offline
6. Member goes online, receives the signal and sends the addresses
7. Control is still offline, so the member sees they are currently out of the community

For this case, we probably need a new "pending state". Something saying "The community owner has changed, you will be added back to the community when the control node goes back online".

**Comment by osmaczko** [comment]
> I think we can just make it so that in that 24h window, the member lists don't change, nor the encryption keys for the channels. In other words, in that period, nothing changes. No new community description, apart to signal that the owner changed I guess.

That would mean the community is frozen for 24hrs. I see it problematic because of a few reasons:
1) How new owner would know it can't update the community? Do we need new designs for that?
2) Code-wise, freezing the community may be challenging. There are many asynchronous loops going on -CommunityDescription broadcast, periodic members reevaluation based on permissions and so on.
3) It means that for 24hrs members who no longer satisfy the criteria can participate in community/channel - but that's acceptable I guess.

The most straightforward solution I see is to kick all members (if community is token-gated) and ask them to rejoin with revealed addresses. This can happen automatically without members interaction. The community will rebuild itself silently when members become online. If control node is offline members should be informed as you proposed: "The community owner has changed, you will be added back to the community when the control node goes back online".

**Comment by jrainville** [comment]
Yeah I agree, the 24h freeze is probably too complex. Let's go with the full kick with auto-re-entry in the background

**Comment by John-44** [comment]
> > @osmaczko @mprakhov @jrainville to double check, all of the revealing addresses to the new owner would be automatic and happen without user interaction (other than one of the user's Status devices needing to be online), correct?
> 
> As long as the member had shared addresses before, then yes. because members store their own shared addresses in their own database, we could just have a signal from the control node to the member saying "give me your addresses again please" and the member node would just send it back in the background. So nothing to do from the user side.
> 
> The only annoying thing that might happen however is if this becomes fully async, in the case where the member and control node are never online at the same. Example:
> 
> 1. Control node changes owner
> 2. Members get kicked but put in the special category of `rejectedBecauseMissingAddresses`
> 3. Control node sends the signal to members to get the shared addresses
> 4. Member is offline
> 5. Control node goes offline
> 6. Member goes online, receives the signal and sends the addresses
> 7. Control is still offline, so the member sees they are currently out of the community
> 
> For this case, we probably need a new "pending state". Something saying "The community owner has changed, you will be added back to the community when the control node goes back online".

Does a member and the control node really both need to be online at the same time in this scenario?   Couldn't the member message to the control node be stored (like all other waku messages, as per waku protocol) on the waku store node and then be delivered to the control node when it comes back online?  And if the member is offline when the control node is online, I would have thought that also wouldn't matter because the control node's message back to the user would also be stored for 30 days on a waku store node.

So both the store node and the control node need to be online within 30 days of each other (if we can pass the required messages via waku).  Or am I missing something.

**Comment by osmaczko** [comment]
> Does a member and the control node really both need to be online at the same time in this scenario?
@John-44 Of course not. As you correctly pointed out, the messages will be restored from store nodes.

I think we agreed on solution: https://github.com/status-im/status-desktop/issues/11969#issuecomment-1730097432

**Comment by jrainville** [comment]
> Does a member and the control node really both need to be online at the same time in this scenario?

No. All you said was right. We will indeed store all those messages/signals on control nodes.

The scenario I highlighted is to show that a user needs a special state/message, because if the control node is **not** online when it sends its shared addresses, it will not be auto-re-accepted in the community until the control is back.
So they need to understand what is going on.

Even if they are both online, there would be a couple seconds for the exchange of messages to get the user back in the community.
I guess the 30 second fake loading will take care of that, but in case the user was already logged in, they will be kicked out for a second or two.

**Comment by benjthayer** [comment]
Hey @osmaczko @John-44 @jrainville @mprakhov I've designed this state for the kicked community member while they await the new control node coming online. I've abstained from specifically referring to the community changing hands given some community owners may be more sensitive to highlighting change in management than others but totally open to copy suggestions. Let me know what you think! 

<img width="1440" alt="ControlNodeOffliine" src="https://github.com/status-im/status-desktop/assets/110033914/5bdad97d-7fc5-491a-a308-53d77940996a">

Figma
https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=40026-142516&mode=design&t=L9f3FBXoghLxinLl-4

**Comment by jrainville** [comment]
Looks good to me. Maybe some people might ask why that is though. It sounds like a maintenance message though, so it can be acceptable as is!
