### ISSUE TITLE
Communities: Owner token holder presented as address instead of contact (self)

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#12065]
# Bug Report

## Description

On the holders list of owner token there is one entry representing raw address belonging to the user. It should be presented as a contact pointing to the current user.

App:
![Screenshot from 2023-09-01 13-23-08](https://github.com/status-im/status-desktop/assets/20650004/6f182064-3723-4bb9-9ea8-b4d51158c8c7)

Figma:
![Screenshot from 2023-09-01 13-27-18](https://github.com/status-im/status-desktop/assets/20650004/d8306dfd-66bf-42cb-b253-5dc9b3ec9964)

## Steps to reproduce

1. Create community
2. Mint owner token

#### Expected behavior
Token holder should be visible as a contact

#### Actual behavior
Wallet address is presented

### Additional Information

- Status desktop version: master
- Operating System: Linux

**Comment by kounkou** [comment]
This requires minting the owner token, and I am currently in the process of minting token.

**Comment by kounkou** [comment]
Hey @benjthayer Just to make sure I understand correctly the requirements here. 
1- You're saying that we should not represent the contact with raw address ever, like in the Figma screenshot we should always display contact correct?
2- In your Figma you didn't include the `No. of messages` and the `Holding`. Is this a mistake or the Figma is the expected state

**Comment by benjthayer** [comment]
> Hey @benjthayer Just to make sure I understand correctly the requirements here. 1- You're saying that we should not represent the contact with raw address ever, like in the Figma screenshot we should always display contact correct? 2- In your Figma you didn't include the `No. of messages` and the `Holding`. Is this a mistake or the Figma is the expected state

Hey @kounkou, to answer your first question:

**We should show the user info instead of the ethereum address in the following cases:**

a) when the current Owner token hodler is the user that created the community and minted the Owner and TokenMaster tokens (we will have the user details so should show those instead of the ethereum address) 

b) when the Owner token has been sent to an existing Status user and the eth address that received the Owner token is one of the user's Status accounts (i.e. that account is associated with the Status profile)

**We may only be able to show the ethereum address in the following case:**

a) Where the old Owner has sent the Owner token to an ethereum address not associated with a current Status user. That user would need to join Status and import the account hodling the Owner token in order for us to be able to show their display name and avatar etc instead of the ethereum address.

@osmaczko could you confirm the above is correct from your perspective?

**Comment by kounkou** [comment]
This ticket seems related to 
- https://github.com/status-im/status-desktop/issues/13643

**Comment by kounkou** [comment]
### Solution

In order to solve this ticket,
we will introduce a concept of context attached to the type of collectibles privilege we will want to view details from. Based on the context, we will then be able to display a contact with image and appropriate name depending if we found the contact from the contact Service.

I am taking one more day to be able to understand more the code base before making the changes necessary to fix the problem.

**Comment by osmaczko** [comment]
> @osmaczko could you confirm the above is correct from your perspective?

@benjthayer  Yes, that seems correct :+1: Although, in this case I would simplify the logic and always show the owner of the community, regardless if we can associate address with the owner or not. The system requirement is quite clear: owner token MUST be held by the owner of the community.

**Comment by kounkou** [comment]
Current render of the proposed solution : 

![Screenshot from 2024-02-24 23-05-40](https://github.com/status-im/status-desktop/assets/2589171/ea2ee445-b05c-49ae-b3d7-1acae45bbc62)
![Screenshot from 2024-02-24 23-05-23](https://github.com/status-im/status-desktop/assets/2589171/4c79d6a0-e0ec-4389-9c34-5a886b1265ff)
