### ISSUE TITLE
[Join community] Cannot join communities after restoring the account from keycard

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#12170]
# Bug Report

## Description

Cannot join Status community with a newly restored account using keycard. It seems to be related to the new `Share address flow`.

## Steps to reproduce
1. Make sure there is an account stored on keycard
2. Go through the onboarding flow for an existing Status account
3. Restore using keycard
4. Login after a successful restore
5. Request to join Status community

#### Expected behavior
Join request is sent
#### Actual behavior
Failed to send join request
### Additional Information

The flow fails with the following error:
`cannot retrieve a valid key for a given account`

- Status desktop version: 0.14 RC9
- Operating System: MacOS

**Comment by endulab** [comment]
There are 2 additional issues found during reproducing:
1. Problem with fetching data. I encountered this may times (already signalized to QA team)
2. Problem with requesting to join community. After clicking "Request to join" button and revealing the address nothing happens.

**Comment by saledjenic** [comment]
I've started introducing myself with this part of the app to grasp a context before starting to fix this bug.

There are 2 things that need to be fixed:
- verifying account address, in case the address belongs to a keypair that is migrated to a keycard
- generating a signature for signing the joining community request in case a profile keypair is migrated to a keycard

But before that, I have some questions for @messenger-team, that might result in some other issues:
1. I see that the address used as `airdropAddress` is always the default wallet account of the logged-in user, actually the profile that is joining a community, is that what we want?
2. I also see that we're letting users select which addresses they would like to reveal to the community, but I don't see in the code that we're letting users join the community if they didn't select the default wallet address as an address to be revealed to the community. Is that what we want? How I get it is that addresses selected to be revealed are those other community members may see, but one used for airdrop doesn't need to be revealed and I guess that's the valid case?
3. Also not sure why we need to sign a community request [here](https://github.com/status-im/status-go/blob/ac813ef5d8f012ba4a0b532483ceeebc553aa3b1/protocol/messenger_communities.go#L987) with all addresses users want to reveal? I somehow expected a community request to be signed once, using the logged-in user chat address, not using wallet addresses.
4. In case we really need to sign a community request for each revealed address and let's that we want to reveal X addresses where each of them belongs to a different keypair that is migrated to a keycard, then it means we need to ask used to provide X different keycard while requesting to join community process it ongoing and provide pin for each of them to complete the request? 
5. This one is not a question, but more a concern based on code I've seen today, while analyzing this issue. I see that you're fetching the accounts from the wallet-section/send module, [here](https://github.com/status-im/status-desktop/blob/2c5eeea50311554fad2343a4aebebfba10128a93/ui/app/AppLayouts/Wallet/stores/RootStore.qml#L21) to offer users addresses to select which addresses they would like to share when joining a token gated community and also using that model to select the airdrop address. That approach is not very good, much better is to inject wallet-accounts-service in the module where wallet-related data are necessary and grab them from that service and use them in a form you like/need. 
An issue (that might be hidden) because of that is that there is no guarantee in the order of accounts model fetched from wallet-section/send module, especially when we know that we have drag&drop feature for accounts and that we know that accounts model is just a UI model. That further means, referring to point 1. of this comment, [this](https://github.com/status-im/status-desktop/blob/2c5eeea50311554fad2343a4aebebfba10128a93/ui/imports/shared/popups/CommunityIntroDialog.qml#L90) and similar approaches in other places in the app are wrong.

@jrainville @alexjba @endulab @osmaczko

**Comment by caybro** [comment]
> I've started introducing myself with this part of the app to grasp a context before starting to fix this bug.
> 
> There are 2 things that need to be fixed:
> 
> * verifying account address, in case the address belongs to a keypair that is migrated to a keycard
> * generating a signature for signing the joining community request in case a profile keypair is migrated to a keycard
> 
> But before that, I have some questions for @Messenger-Team, that might result in some other issues:
> 
> 1. I see that the address used as `airdropAddress` is always the default wallet account of the logged-in user, actually the profile that is joining a community, is that what we want?

Yes, that is (or should be) the default one but the user is free to select any other

> 2. I also see that we're letting users select which addresses they would like to reveal to the community, but I don't see in the code that we're letting users join the community if they didn't select the default wallet address as an address to be revealed to the community. Is that what we want? How I get it is that addresses selected to be revealed are those other community members may see, but one used for airdrop doesn't need to be revealed and I guess that's the valid case?

From the UI pov, the user must select the airdrop address from the ones they reveal (or go with the default one)

> 5. This one is not a question, but more a concern based on code I've seen today, while analyzing this issue. I see that you're fetching the accounts from the wallet-section/send module, [here](https://github.com/status-im/status-desktop/blob/2c5eeea50311554fad2343a4aebebfba10128a93/ui/app/AppLayouts/Wallet/stores/RootStore.qml#L21) to offer users addresses to select which addresses they would like to share when joining a token gated community and also using that model to select the airdrop address. That approach is not very good, much better is to inject wallet-accounts-service in the module where wallet-related data are necessary and grab them from that service and use them in a form you like/need.

I'll defer this decision to the messenger team; in the early (UI) phase with no backend, I needed something that also provides access to the tokens/assets the user possesses

**Comment by osmaczko** [comment]
> 1. I see that the address used as `airdropAddress` is always the default wallet account of the logged-in user, actually the profile that is joining a community, is that what we want?

The default wallet account should serve as a fallback if the user doesn't make a selection on their own.


> 2\. I also see that we're letting users select which addresses they would like to reveal to the community, but I don't see in the code that we're letting users join the community if they didn't select the default wallet address as an address to be revealed to the community. Is that what we want? How I get it is that addresses selected to be revealed are those other community members may see, but one used for airdrop doesn't need to be revealed and I guess that's the valid case?

That's the issue. Users should be able to select a non-default address. Only privileged members (token masters) and the control node can view the addresses; other members cannot see them.



> 3\. Also not sure why we need to sign a community request [here](https://github.com/status-im/status-go/blob/ac813ef5d8f012ba4a0b532483ceeebc553aa3b1/protocol/messenger_communities.go#L987) with all addresses users want to reveal? I somehow expected a community request to be signed once, using the logged-in user chat address, not using wallet addresses.

Users need to prove they own a specific wallet address; otherwise, they could select any address with assets that meet the community's criteria. For example, if I wanted to join a community that requires ownership of 100ETH, I could submit Vitalik's address to gain access, even though I don't actually own 100ETH.
