### ISSUE TITLE
Missing pending animation when switching channels

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#12363]
# Bug Report

## Description

Switching channels feels laggy because the pending animation is missing.

By pending animation I mean:

https://user-images.githubusercontent.com/117639195/229799428-9eb82df3-5d4c-4d15-8b7b-00ed63208805.mov

## Steps to reproduce

Switch channels in any community

#### Expected behavior

Channel switches immediately with optional pending animation

#### Actual behavior

Channel switches with ~1sec lag without pending animation

### Additional Information

- Status desktop version: 0.14.0
- Operating System: Fedora

**Comment by flexsurfer** [comment]
just wondering why you decided to slow down switching. in 0.13 it was fast and without animation

**Comment by igor-sirotin** [comment]
From what I investigated, there's a ~1s delay even when switching between _already loaded_ channels.

This is happening because of `ExpressionRole` here:
https://github.com/status-im/status-desktop/blob/2d0047846739f076510378327ecbff85b05154f3/ui/app/AppLayouts/Chat/panels/UserListPanel.qml#L63-L70

which is used for sorting here:
https://github.com/status-im/status-desktop/blob/2d0047846739f076510378327ecbff85b05154f3/ui/app/AppLayouts/Chat/panels/UserListPanel.qml#L76-L79

Commenting these lines makes channel switching quite fast, we don't need animation there.

cc @alexandraB99, I think UI team knows better how to deal with this?
Can you please pick it up?

-----

We do though need animation when switching to a not-yet-cached channel. 
I'm looking into this now.

**Comment by igor-sirotin** [comment]
Yesterday I added some logs and it seems that the `loading` property is set to `true` during channel loading. 
I guess it's just too fast for QML to react to this change, because there're some other things going on in the event loop.

Let's maybe first fix the `ExpressionRole` problem and then check again how bad this works in release version.

cc @alexandraB99  @caybro @alexjba, wdyt?

**Comment by caybro** [comment]
> Yesterday I added some logs and it seems that the `loading` property is set to `true` during channel loading. I guess it's just too fast for QML to react to this change, because there're some other things going on in the event loop.
> 
> Let's maybe first fix the `ExpressionRole` problem and then check again how bad this works in release version.
> 
> cc @alexandraB99 @caybro @alexjba, wdyt?

Can you pls quickly try to exchange the `ExpressionRole` for the new and fancy `FastExpressionRole` that we just introduced to see if it fixes the issue for you?

**Comment by igor-sirotin** [comment]
I short summary:

1. There was an initial assumption that chat loading animation is missing here.
But it wasn't correct. The delay is happening for already loaded channels.

2. I found that removing these lines fixes the delay:
https://github.com/status-im/status-desktop/blob/2d0047846739f076510378327ecbff85b05154f3/ui/app/AppLayouts/Chat/panels/UserListPanel.qml#L63-L70
https://github.com/status-im/status-desktop/blob/2d0047846739f076510378327ecbff85b05154f3/ui/app/AppLayouts/Chat/panels/UserListPanel.qml#L76-L79

3. I tried to replace `ExpressionRole` with `FastExpressionRole`, but it didn't really help:
https://github.com/status-im/status-desktop/pull/13299


Reassigning this to ui-team as discussed.

**Comment by igor-sirotin** [comment]
Actually I'll open a separate issue not to confuse things with current issue description:
https://github.com/status-im/status-desktop/issues/13354
