### ISSUE TITLE
Add additional jenkins artefact for e2e tests for keycard on desktop

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12412]
### Description

In order to test mocked keycard lib provided by @saledjenic on desktop app , we need to have a special CI build that will include `TEST_ENVIRONMENT` variable set before we create a build, so the lib will be accessible using CI artefact

Values for `TEST_ENVIRONMENT` variable:

- `true`
- `1`

This artefact is needed to be created for pull requests, master branch and release branch.

This build could be called somewhat `%_e2e`

This build is needed for all the platforms we build for, but in case the possibilities are limited, **Mac x64** and **Linux** are preferable for now

**Comment by anastasiyaig** [comment]
@Valentina1133 @StateOf-Vlado

**Comment by jakubgs** [comment]
Thanks.

**Comment by jakubgs** [comment]
According to @anastasiyaig this change is related to Keycard mocking mechanism required for testing added here:

* https://github.com/status-im/status-desktop/pull/9312
* https://github.com/status-im/status-desktop/pull/12182

The key part is here:
https://github.com/status-im/status-desktop/blob/2c5039f7d3333ba843059b1b62339deb67d6ed33/Makefile#L395-L400

**Comment by jakubgs** [comment]
After talking to @jrainville and @saledjenic it turns out that `TEST_ENVIRONMENT` variable is used by the app at __runtime__.

The building of `vendor/status-keycard-go` library is affected by it by accident essentially, and should use a different variable.

I'm proposing:

* Rename `TEST_ENVIRONMENT` to `STATUS_RUNTIME_TEST_MODE` because it needs to be clear this is runtime.
* Add a `USE_MOCKED_KEYCARD_LIB` env variables to affect the use of `build-mocked-lib` target in the `Makefile`.

This should resolve at least some of the confusion here.
