### ISSUE TITLE
Stickers still show in the recent list after being uninstalled

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#12677]
#### Steps to reproduce:

1. Buy or install new stickers
2. Use some stickers from the new stickers pack
3. Uninstall stickers

Result: There are uninstalled stickers in the recently used stickers section

![image](https://github.com/status-im/status-desktop/assets/11926403/9162c30f-be47-4824-8473-1df744d627c0)

### Expected behaviour

Once a pack is uninstalled, all the stickers from that pack should be removed from the recent list (in the UI and also in the saved settings so that they stay out on app restart)

**Comment by kounkou** [comment]
Hi,
I could reproduce the issue by following the steps taken by jrainville@
I will now investigate why there Sticker still appear while the sticker pack was uninstalled

![Screenshot from 2023-12-12 20-41-07](https://github.com/status-im/status-desktop/assets/2589171/1af73bf5-486c-4352-a4a3-ac108da20c43)

**Comment by kounkou** [comment]
From my analysis, it turns out, the function that retrieves the list of recentStickers doesn't take care of cross checking if there is any active Sticker packs or even if the stickers are part of at least one of the active packs.
It seems logical to check those before returning the final list of stickers.

```go
func (api *API) recentStickers() ([]Sticker, error) {
...
```
For info, here is the structure of the Sticker : 
```
type Sticker struct {
	PackID *bigint.BigInt `json:"packID,omitempty"`
	URL    string         `json:"url,omitempty"`
	Hash   string         `json:"hash,omitempty"`
}
```
