### ISSUE TITLE
Token and community token reordering

### ISSUE THREAD

**Issue by Cuteivist** [status-im/status-desktop#12725]
Implement token reordering on status-go and status-desktop side

status-go:
- [x] Add database table
- [x] Add sync logic
- [x] Provide API call for changing and getting token preferences

status-desktop:
- [x] Add call to new APIs
- [x] Pass JSON response to QML
- [x] Update API when JSON is changed in QML

**Comment by caybro** [comment]
I wonder what is this task about and how is it different from mine here? https://github.com/status-im/status-desktop/pull/12671

**Comment by caybro** [comment]
> @caybro it's purely backend task on status go side.

Yeah but what does it involve, what's the goal? :)

**Comment by caybro** [comment]
Great, thanks!

**Comment by noeliaSD** [comment]
Here, as agreed with the team, the proposed basic  *view apis / model* that will allow the interaction between _UI_ and _backend_ is:

**VIEW**
- API to get **int** `sortingType` --> Possible values {Asset /collectible sorting options like by balance, by value, custom order}
- API to get **bool** `isArrangedByCommunity`
- API to get **bool** `isCustomOrderCreated`
-  MODEL **seq[PositionItem]** `positionBySymbolList`:
   - `key`( being  token `symbol` or `address` in case of community token)
   - `position` (the position applied when `isArrangeByCommunity` = false)
   - `groupedPosition` --> (the position applied when `isArrangeByCommunity` = true)
   - `isVisible`
   - `isGroupedVisible` (To be confirmed by `Ben`)

**Comment by caybro** [comment]
Based on the discussion with @Cuteivist, the updated proposal for NIM storage is:
```
-  MODEL **seq[PositionItem]** `positionBySymbolList`:
   - `key` (string; being a non-empty unique token identifier)
   - `position` (int; the position applied when `isArrangeByCommunity` = false)
   - `groupedPosition` (int; the position applied when `isArrangeByCommunity` = true)
   - `isVisible` (bool)
   - `groupId` (string)
```

This will be a read/write property on the NIM side, which the C++ controller will push to/pull from in order to write/read its internal settings (instead of operating on QSettings). This way we can ensure the settings is stored in one place, and can be properly persisted in the database by status-go, with a prospect to have it synced across devices too in the future (not part of this issue). Due to NIM limitation of what it can expose as a property, this NIM property will be a stringified JSON representation of its C++ counterpart, which currently is:

```cpp
// symbol -> {sortOrder, groupSortOrder, visible, groupId}
using SerializedTokenData = QHash<QString, std::tuple<int, int, bool, QString>>;
```

**Comment by dlipicar** [comment]
Tagging myself here to be in the loop
@dlipicar
