### ISSUE TITLE
Community: TokenMaster token is not shown in collectibles view and on etherscan

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12749]
### Description

1. open status and add a community
2. mint token owner and tokenmaster tokens
3. check them on etherscan
4. check them on collectibles tab of wallet

As result, only token owner is shown

https://goerli-optimism.etherscan.io/address/0xf008ce0e07f8996c0fe71beb59e076207b214e2d#tokentxnsErc721

https://testnets.opensea.io/0xf008ce0e07f8996C0Fe71beB59e076207b214e2D

<img width="1559" alt="Screenshot 2023-11-15 at 18 34 36" src="https://github.com/status-im/status-desktop/assets/82375995/9757daa1-6041-437f-8313-0e5e39bd90a3">

![image](https://github.com/status-im/status-desktop/assets/82375995/fc2caaf8-b7a0-48fe-a161-515108ab6c53)

**Comment by anastasiyaig** [comment]
@jrainville can we please check why the token is not shown and never reached the blockchain?

**Comment by jrainville** [comment]
@anastasiyaig did you airdrop the TokenMaster token to yourself or someone else after deploying it? 

Some clarifications: only the Owner token is minted (airdropped)  when it gets deployed. You mint yourself one OwnerToken (the one and only) when you deploy the contracts. Having that token makes you the owner and gives you all the permisisons. 

You do not need to mint yourself a TokenMaster token as an owner, because the Owner token already gives all the TokenMaster permisisons and more.

If you did mint (airdrop) the TokenMaster to yourself or someone else and it doesn't appear, then yes there is an issue.

**Comment by anastasiyaig** [comment]
ah perfect, i was confused because when i do the minting - the notifications say that both tokens are minted and suggest me to go to etherscan and check transactions. That is misleading perhaps a bit. I will try to do airdrop and see what happens, thanks for clarification

**Comment by jrainville** [comment]
> the notifications say that both tokens are minted and suggest me to go to etherscan and check transactions

if it does say that they were both minted, then it's more of a copy issue. We shouldn't say they have been minted, we should say that they have been deployed and the Owner Token was minted.

If you confirm that, you can open an issue for the UI team.
