### ISSUE TITLE
Use same endpoints as mobile for login and create accounts

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#12977]
### Description

To avoid having different behaviors with account creation and login between mobile and desktop apps, we should use these endpoints, instead of Login, SaveAccountAndLogin, LoginWithConfig, etc...

- Login:
https://github.com/status-im/status-go/blob/238a6e2f2db453d748372721005c6ada7bce2435/mobile/status.go#L293
https://github.com/status-im/status-go/blob/develop/protocol/requests/login.go

- Create Account
https://github.com/status-im/status-go/blob/238a6e2f2db453d748372721005c6ada7bce2435/mobile/status.go#L268C6-L268C27
https://github.com/status-im/status-go/blob/develop/protocol/requests/create_account.go

- Restore Account and Login
https://github.com/status-im/status-go/blob/238a6e2f2db453d748372721005c6ada7bce2435/mobile/status.go#L268C6-L268C27
https://github.com/status-im/status-go/blob/develop/protocol/requests/restore_account.go 

Currently there's no new endpoint for login with keycard so the existing one should still be used

cc: @cammellos

**Comment by igor-sirotin** [comment]
related: https://github.com/status-im/status-desktop/issues/12918

**Comment by igor-sirotin** [comment]
cc @jrainville 

Attracting your attention here. Can we try to take this into any close milestones?
Because we use different endpoints, any fixes done by mobile never rich desktop. There's growing difference between `loginAccount` and `startNodeWithAccount`. And we have to keep an eye on that and copy that behaviour to desktop.
