### ISSUE TITLE
It's not possible to switch the log level

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#13139]
In the advanced settings section, if using a local build, the DEBUG flag is always active, and switching it makes no difference (i tried restarting the app). The same happens in release version, except that the log level is always INFO and it's not possible to switch the DEBUG flag

I'm not entirely sure, but I believe this code might be causing the issue: https://github.com/status-im/status-desktop/blob/a2aedb5c6a699c154382f75d9c5a7e6e641fa14c/src/app/boot/app_controller.nim#L137-L143

cc: @chaitanyaprem

**Comment by caybro** [comment]
CC @igor-sirotin

**Comment by igor-sirotin** [comment]
@richard-ramos 

> if using a local build, the DEBUG flag is always active, and switching it makes no difference

For local build we always set log level to `DEBUG`. Indeed, the switch won't affect anything.
Here's the code that checks `isDebugEnabled` switch on startup:
https://github.com/status-im/status-desktop/blob/a2aedb5c6a699c154382f75d9c5a7e6e641fa14c/src/app/boot/app_controller.nim#L451-L454

We could add `else: setLogLevel(chronicles.LogLevel.INFO)`, but using always using `DEBUG` for local build makes sense to me. Maybe we should change the behaviour of the switch in this case? Maybe even hide it?

> The same happens in release version, except that the log level is always INFO and it's not possible to switch the DEBUG flag

For me it's the opposite 😄 
I run `make RELEASE=true -j10 run`. I still get debug output and `DEBUG` switch is always on!

<img width="591" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/1a536251-b1a2-433f-93c7-40ddcd9b7072">

-----

I think we should reconsider the behaviour of this switch. Requirements would be nice 🙂 I'd be glad to give input.

⚠️  But I don't think this is of any urgency. This switch is only used by devs and the behaviour can be controlled by env variables or CLI flags.

cc @John-44 @iurimatias

**Comment by chaitanyaprem** [comment]
I am facing an issue in my laptop when i run the rc10 release of 0.15.0, i cannot enable DEBUG at all. 
If i enable debug from settings, i am asked to restart the app and when i restart the setting is set back to INFO. 

So, if i have to debug something while dogfooding it is not possible for me due to this limiation. 
Also when CCs start dogfooding and run into issues, we would want debug logs in order to debug the scenario. If DEBUG can't be enabled, then that would make it a challenge. So i think this atleast should warrrant urgency.

**Comment by igor-sirotin** [comment]
> I am facing an issue in my laptop when i run the rc10 release of 0.15.0, i cannot enable DEBUG at all. If i enable debug from settings, i am asked to restart the app and when i restart the setting is set back to INFO.
> 
> So, if i have to debug something while dogfooding it is not possible for me due to this limitation. Also when CCs start dogfooding and run into issues, we would want debug logs in order to debug the scenario. If DEBUG can't be enabled, then that would make it a challenge. So i think this atleast this requires to be addressed immediately .

@chaitanyaprem Thanks for our input. I believe this should be fixed in master already: https://github.com/status-im/status-desktop/pull/12935 (the heading is different, but it's very related). Could you please give it a try with master branch?

**Comment by kounkou** [comment]
Discovered that the bug is happening at start up where the last value set is overwritten for some reason by a DEBUG value, and it’s always set to DEBUG for logLevel. This result in the button always being set to Debug. So I am currently investigating why the value is always DEBUG at start up. Why can't we fetch the value in database and use that as start up value.

**Comment by kounkou** [comment]
More information about the scoping of this ticket in https://github.com/status-im/status-desktop/pull/13309

**Comment by igor-sirotin** [comment]
https://github.com/status-im/status-desktop/pull/13309 not yet merged
