### ISSUE TITLE
[StatusQ] Optimise delegate creation in the 2-sections Flickable

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#13273]
When the view is resized fast, a high amount of delegates are getting created. With heavy grid view delegates it could freeze on resize.

This is the code I've been testing with. The DoubleFlickableWithFolding is inside a layout with a dynamic height/width.
Rename the `json` to `qml` (GitHub doesn't accept qml files as attachments)
[DoubleFlickableWithFoldingPage.json](https://github.com/status-im/status-desktop/files/14026795/DoubleFlickableWithFoldingPage.json)

Repro steps:

1. Scroll down the page
2. Increase the window size

https://github.com/status-im/status-desktop/assets/47811206/b50cd51b-6b03-474f-a06e-cbf284b99d12

_Originally posted by @alexjba in https://github.com/status-im/status-desktop/pull/13231#pullrequestreview-1839146904_

**Comment by micieslak** [comment]
I did several experiments and checked if parameters possibly affecting number of instantiated delegates, like grid's width and height. Unfortunately I didn't find any suspicious there. However the problem exists indeed, also in my env (ubuntu, qt 5.15.2) the problem is observable. There are spikes when there are many delegates instantiated, several times more than needed to cover viewport.

In the next step I created a bit heavier setup to check the resizing then along with other operations like scrolling.

To simulate more complicated delegate, the tested one consist of ListView with 10 Labels inside, 11 text components in total, with different font sizes.
```
                    delegate: Rectangle {
                        width: grid1.cellWidth
                        height: grid1.cellHeight

                        border.color: "black"
                        color: "lightblue"

                        ListView {
                            model: 10
                            anchors.fill: parent
                            orientation: ListView.Horizontal

                            delegate: Label {
                                text: index
                                font.pixelSize: 10 + index
                            }
                        }

                        Text {
                            anchors.bottom: parent.bottom
                            anchors.right: parent.right
                            text: index
                        }
                    }
```
The number of items in model for tests was 25K per listView, 50K in total.

In such setup, for used delegates size, there were ~650 visible delegates on the screen, with over 7K Label components inside.

[Kazam_screencast_00097.webm](https://github.com/status-im/status-desktop/assets/20650004/d88dde90-4f3a-46df-a602-b90ac60b719f)

Observations:
- scrolling by dragging or mouse wheel is fully smooth (same as in plain list view with the same delegate)
- scrolling by dragging scroll bar, especially rapidly is not smooth and jumpy but still usable
- similar jumpiness is observable when resizing window, especially with rapid resize, when the spike of delegates is created. However it's still up to ~1s freeze.
- The number of items doesn't play big role here. Similar behavior for 10K, 50K, 100K. For very small number of items the problem is not visible (<1K)

Conclusions:
- The setup used is far from realistic in terms of number of delegates in the viewport and also complexity of delegate (in most cases)
- The resizing freezes are noticeable but correlated with sluggish scrolling via dragging scrollbar. The same problem appears in just regular ListView.

So, as mentioned before, the problem exist, however at the point where it's observable, there are already other problems, which exist even in a regular ListView. Knowing that, deeper investigation is probably pointless because it doesn't solve any real-life problem. There is also probably no easy fix for that, more time consuming inspection would be needed probably.

**Comment by micieslak** [comment]
There are some issues reporting similar problems, like:

https://bugreports.qt.io/browse/QTBUG-110625
https://bugreports.qt.io/browse/QTBUG-51773
https://bugreports.qt.io/browse/QTBUG-89568

However none of the seem to be directly related to this case because the is no binding to properties like `GridView.view.height`.

**Comment by micieslak** [comment]
All analysis done is documented in comments, and there are basic conclusions:
- the problem exists but we rather won't reach that point in real app
- when that problem will be reached, other problems will appear as well
- there is no clear way how fix that
