### ISSUE TITLE
After sending a Contact Request to a user just after rejecting their, it is auto-accepted and the notifications do not reflect that on one of the accounts

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13449]
# Bug Report

## Description

After a contact request from an user is rejected and another one is sent immediately afterwards, the request is automatically accepted. It behaves exactly like an accepted request would, but from the point of view of the receiving user the first request is still displayed as pending. 

## Steps to reproduce

1. Log into two accounts that do not have each other in contact list
2. Send a contact request from User1 to User2
3. Reject the request as User2
4. Immediately send a contact request to User1 as User2

#### Expected behavior
Notifications display the first request as rejected for both users, the second one can be rejected or accepted by the receiving user

#### Actual behavior
One of the users sees the first request as still pending and the other one as blank, despite it being accepted by the application

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/nightly/179/
- Operating System: macOS

https://github.com/status-im/status-desktop/assets/155960867/1f3930de-7014-40cf-9dd5-9ce26edc8293
![image](https://github.com/status-im/status-desktop/assets/155960867/75c89558-2cfd-4856-ba5b-8f3b3fbb83b0)
![image](https://github.com/status-im/status-desktop/assets/155960867/666ebd65-400e-4dc4-bd45-5a51f304229a)
[geth.log](https://github.com/status-im/status-desktop/files/14193897/geth.log)

**Comment by anastasiyaig** [comment]
@igor-sirotin shall it work this way?

**Comment by anastasiyaig** [comment]
@jrainville seems like an edge case , did we ever have it to work? I cant remember, the only thing i remember is that if you send me a contact request and i send same to you - then we are contacts even we dont accept the incoming requests.

**Comment by jrainville** [comment]
> @jrainville seems like an edge case , did we ever have it to work? I cant remember, the only thing i remember is that if you send me a contact request and i send same to you - then we are contacts even we dont accept the incoming requests.

The last part you said is correct yes. I'm guessing this issue is using the same mechanism in the backend. We detect that we received a contact request from the other user, so even if we rejected it, we see that they added us, so since we add them, it counts as mutual, which is true. However, I can understand that it could be confusing.

I don't think we can actually "fix" this, because even if we deleted the contact request in the background when rejecting, we don't actually send the rejection to the user, as far as I know. This is to reduce the potential for spam request iirc.
That means that even if we delete or copy of the contact request, the other person will still be in the state where they sent and are waiting for an answer. So when they get a new contact request from us, they think we added them back basically.

There is a way to make it work where we re-initiate the contact request process by using some kinds of IDs, but it would require a change to the contact request flow and it is already complex as it is, it sounds like a bad tradeoff.

I think there is nothing to do here. Maybe we can ask designers to maybe add a little warning or info when sending the new contact request to say "hey you already rejected this person, do you really want to add them? If yes, then you will become contact right away because they already added you", but written better :grin: 

Or since it's a pretty edge case and the behaviour is actually correct, even if confusing, we could just leave it as is.

**Comment by anastasiyaig** [comment]
alright, lets close it then, thank you @jrainville
