### ISSUE TITLE
Wallet - Settings - Move keypair to keycard is stuck when keycard is not empty

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13566]
### Description

**Precondition: keycard is not empty**

1. open wallet settings
2. create new account by adding new master key (generate new seed)
3. in settings of wallet, navigate to this keypair and select "migrate keypair to keycard"
4. insert keycard
5. click Check whats on keycard

```
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader
keycard - using reader ACS ACR39U ICC Reader
keycard - card protocol T1
keycard - card protocol T1
keycard - card protocol T1
DBG 2024-02-14 16:47:38.576+03:00 sm_on_keycard_response                     topics="profile-section-profile-module" tid=11757356 file=module.nim:448 currFlow=SetupNewKeycard currState=InsertKeycard
DBG 2024-02-14 16:47:38.585+03:00 sm_on_keycard_response - set state         topics="profile-section-profile-module" tid=11757356 file=module.nim:455 setCurrFlow=SetupNewKeycard setCurrState=KeycardNotEmpty
DBG 2024-02-14 16:47:43.742+03:00 sm_primary_action                          topics="profile-section-profile-module" tid=11757356 file=module.nim:381 currFlow=SetupNewKeycard currState=KeycardNotEmpty
```

<img width="1524" alt="Screenshot 2024-02-14 at 16 48 07" src="https://github.com/status-im/status-desktop/assets/82375995/87605a4a-35b8-40f8-abb5-f33daf368b6a">

**Comment by anastasiyaig** [comment]
@saledjenic ^^

**Comment by saledjenic** [comment]
@anastasiyaig that's not a case for me at all. I've just tested it. 

Thinking now, that such behavior t could be an issue with the keycard reading, but that's a low-level thing, not something that we can fix in the app, it's more a thing to be fixed in the keycard library. Also it looks to me like this log is from the release build, not from the develop one, cause there is no useful info. Could you try next time when you see this issue to remove/insert a keycard or unplug/plug the reader?

**Comment by anastasiyaig** [comment]
thanks for checking @saledjenic , i will take a look a bit later

**Comment by saledjenic** [comment]
Not reproducible.
