### ISSUE TITLE
1:1 chat history not synced, replaced with generic request message

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13580]
# Bug Report

## Description

When syncing between two devices, chat history gets cleared and is instead replaced with a generic message sent with a contact request. As you can see in the video - the request was sent with "NOW I AM SENDING A REQUEST", but in the chat history on the synced device it was replaced with a generic "Please add me to your contacts". Other messages are gone. This makes it impossible to test whether deleted and edited messages are synced properly.

## Steps to reproduce

1. Log into an user 
2. Add a contact with a custom message in the request
3. Write some messages to that contact
4. Delete some messages

#### Expected behavior
-Chat history is synced
-Deleted messages are still deleted on the new device
-The custom message used in contact request is not altered

#### Actual behavior
-Chat history is NOT synced
-The custom message used in contact request IS changed to the generic one

### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/6/
- Operating System: macOS

https://github.com/status-im/status-desktop/assets/155960867/cfcc56b9-195f-46f2-ab3e-38c7d846f127

**Comment by jrainville** [comment]
Ah, this is per design.

We do sync the contact state, the renaming of the chat, the contact request, however, we do not and never will sync 1x1 messages. This is because of of the perfect forward secrecy. 

Messages sent from now on though will appear on both apps, since they are sent live and will have the same encryption keys.

I'll close this issue as there is nothing to do, unless we decide to change this requirement.
