### ISSUE TITLE
ID verification cannot be removed

### ISSUE THREAD

**Issue by Michal-Status** [status-im/status-desktop#13619]
# Bug Report

## Description

After the user has ID verified a contact, this verification cannot be removed. The button is there, it just does not remove it.

## Steps to reproduce

1. Add a contact
2. ID verify that contact
3. Click on the profile of that contact
4. Click on "remove verification" (in three dots menu)
5. Confirm

#### Expected behavior
ID verification is removed
#### Actual behavior
ID verification is not removed
### Additional Information

- Status desktop version: https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F2.27.x/14/
- Operating System: macOS

https://github.com/status-im/status-desktop/assets/155960867/cfab4679-9ae9-4450-a1d3-ee5bc5e9f27c

[app_20240219_103242.log](https://github.com/status-im/status-desktop/files/14329356/app_20240219_103242.log)

**Comment by jrainville** [comment]
Moving to 2.29 since there won,t be the time to do

**Comment by friofry** [comment]
Sharing some intermediate findings. We have fields `TrustStatus` + `VerificationStatus`.
```
readonly property QtObject trustStatus: QtObject {
    readonly property int unknown: 0
    readonly property int trusted: 1
    readonly property int untrustworthy: 2
}

readonly property QtObject verificationStatus: QtObject {
    readonly property int unverified: 0
    readonly property int verifying: 1
    readonly property int verified: 2 
    readonly property int declined: 3
    readonly property int canceled: 4
    readonly property int trusted: 5 
    readonly property int untrustworthy: 6
```

1. Initial: `trustStatus = unknown, verificationStatus = unverified`
2. After sending a verification request (outgoing): `trustStatus = unknown, verificationStatus = verified`
3. After receiving a response and marking it as Verified: `trustStatus = trusted, verificationStatus = trusted`
4. After clicking the "Remove ID verification" button, the `removeTrustStatus` function is called:
```

proc removeTrustStatus*(self: Service, publicKey: string) =
  let response = status_contacts.removeTrustStatus(publicKey)
  if not response.error.isNil:
    error "error removing trust status", msg = response.error.message
    return

  if self.contacts.hasKey(publicKey):
    self.contacts[publicKey].dto.trustStatus = TrustStatus.Unknown
    if self.contacts[publicKey].dto.verificationStatus == VerificationStatus.Verified:
      self.contacts[publicKey].dto.verificationStatus = VerificationStatus.Unverified

  self.events.emit(SIGNAL_REMOVED_TRUST_STATUS,
    TrustArgs(publicKey: publicKey, isUntrustworthy: false))
```

I found the specification here: https://github.com/status-im/feature-specs/blob/spec/identity_check_spec/content/raw/chat/identity_verification.md.
But I'm not sure which behavior is correct.
Since the verification status is `Trusted` but not `Verified`, the verification status stays the same.
(I guess we can always reset Trusted/Verified?)

5. After restarting the application, the verification status becomes `Verfied` for some reason (I want to find out why it was `Trusted` before the restart and `Verified` after the restart). I assume this is because the `TrustStatus` was reset in step 4.

So if it's ok, I'll tweak the `removeTrustStatus` function. Or maybe I should do a more general refactoring

**Comment by friofry** [comment]
Today I debugged some more, and it turns out strange that the contactDto that on the nim side after `removeTrustStatus` has `verificationStatus=trusted(5)`, and `trustStatus = 0`. And on the go side, if you do `Contacts.Load(contactId)`, you can see that `verificationStatus=verified(2)` and `trustStatus = 0`

I have two general thoughts: 
1) It seems that on the nim side sometimes there are changes that don't make it to go. And apparently in this ticket I need to find where that is. And in general, in an ideal world, it seems there should be one "source of truth" on the go side, and nim can store a map of cached values on its side, and update them if something is updated in go. (but I have little understanding of the code so far).

2) Strange that trustStatus and verificationStatus are not "orthogonal", i.e. they can store inconsistent values

**Comment by jrainville** [comment]
Reopening until the desktop PR is merged (https://github.com/status-im/status-desktop/pull/14308)
