### ISSUE TITLE
Community Token holder list empty sometimes

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#13650]
# Bug Report

## Description

Weird issue. I was a TokenMaster in a community that had multiple tokens. One of the token was an NFT needed to join the community.

2 people owned that token, yet, when I went to see the list of holders in the admin panel, they didn't appear (the list was empty).

The owner could see them. However, after a restart, the owner also lost the list.

After doing something, not sure what, the list reappeared for both of us. I assume the community description was updated and that is how it got propagated again.

## Steps to reproduce

0. Be part of a community that has a permission to join, and you are TM, and 1 or 2 other people are holders of the token to join
1. Go to the admin panel -> Tokens
2. Click the Join token
3. See that the list of hodler might be empty

As of writing this issue, the list is empty again. I did restart the app.

I know that there are 3 members of the community that own it, including myself.

![image](https://github.com/status-im/status-desktop/assets/11926403/3a8d5006-5c3b-43dd-97e8-be5bf6aca128)

#### Expected behavior

The token holder list is populated with the people owning the token

#### Actual behavior

The list is often empty

### Additional Information

- Status desktop version: 2.27RC2
- Operating System: Ubuntu 20

**Comment by kounkou** [comment]
This should be already fixed. Let me have a second look to make sure.

**Comment by kounkou** [comment]
So it turns out, we are currently using the `GetCollectibleOwnersByContractAddress` to retrieve the list of owners for a give contract then we extract the owners from that API call.
From wallet prespective, there is no caching so we need to keep the strategy of polling for the blockain or from some aggregator in this case Alchemy...

Currently the only feasible proposal is to reduce the polling and make sure the time is consistent after the Status app restart.

There is however, a strategy to reduce further the waiting time, but this require Status to become its own aggregator and in this case we will just be able to fecth the data internally (within Status). This is very long term.

**Comment by jrainville** [comment]
Couldn't be completed in 2.28. Moved to 2.29

**Comment by kounkou** [comment]
**WIP**


Following conversation with Jo, I will come back with proposal solution for drastically reducing data retrieval as current waiting time for retrieving the list of token oweners is not acceptable nor user friendly. 
The proposal should include 

- An eviction policy and strategy for managing data in cache.
- The expected outcome is that data can be retrieve below 1s timestamp from cache compared to 10min without caching today. These should be defined in RTO and RPO requirements
- and data should be correct within 5 min bounds as data need to be retrieved from the blockchain. By correct, we mean that the data should be reflection of Blockchain data.

### Changes made to the architecture

```mermaid
sequenceDiagram
    participant status_client
    participant community_service
    participant Alchemy
    status_client->>community_service: fetchCollectibleOwnersTask
    community_service->>Alchemy: GetCollectibleOwnersByContractAddress
    Alchemy->>community_service: response
    community_service->>status_client: collectible owners by contact address
```

### High level system architecture

Our proposal will consist in adding a database for caching the result of the L2 queries currently made to Alchemy Rarible

```mermaid
sequenceDiagram
    participant status_client
    participant community_service
    participant Alchemy
    participant PostgresDatabase
    loop cache miss
       status_client->>community_service: fetchCollectibleOwnersTask
       PostgresDatabase->>community_service: collectible owners deleted
       community_service->>Alchemy: GetCollectibleOwnersByContractAddress
       Alchemy->>community_service: response
       community_service->>status_client: collectible owners by contact address
    end
    loop cache hit
       status_client->>community_service: fetchCollectibleOwnersTask
       community_service->>PostgresDatabase: Get token owners
       community_service->>status_client: response
    end
```

### Database structure

### Consideration for data that do not change frequently

As of now 

### Consideration on cold start

Our proposal will be subject to cold start, indeed, upon activation of the service, any attempt to fetch the token owners will result in cache misses because of cold cache issue. This issue should quickly dissipate as the data are filled.

**Comment by jrainville** [comment]
In the graph, you say `PostgresDatabase`. Do you plan to add a new database or you just mistyped and meant Sqllite?

Because I don't feel like we should add a new database. You can just reuse the one we have and add a new table. Also, we need to make sure it's all in status-go, that way mobile uses it as well.

As for the cold start, I'd say we should make it so that if the cache/table is empty, then we should force the fetch from Alchemy. Of course, we need a mechanism to say if we already tried, so that if a token has no owners, we don't just force the fetch each time.

This way, we'd not have an empty list for too long.

**Comment by kounkou** [comment]
> In the graph, you say `PostgresDatabase`. Do you plan to add a new database or you just mistyped and meant Sqllite?
> 

Ah sorry those graphs will have a second pass for me to match the exact names we have, good catch, **I just meant sqlite here**. Out of the way the idea to centralize anything here 😈

> Because I don't feel like we should add a new database. You can just reuse the one we have and add a new table. Also, we need to make sure it's all in status-go, that way mobile uses it as well.

👍🏾

> As for the cold start, I'd say we should make it so that if the cache/table is empty, then we should force the fetch from Alchemy. Of course, we need a mechanism to say if we already tried, so that if a token has no owners, we don't just force the fetch each time.

That's correct! @jrainville You read my mind, didn't have time to update the graph 😄
I am seeing if the eviction policy should handle the management of cache misses or if I would need anything custom here (to see...)

> This way, we'd not have an empty list for too long.

I also feel like what you just said should be enough... I believe this high level idea disambiguate enough the addition of a cache, and should solve the current problem we're facing.

**Comment by kounkou** [comment]
Seems like Wallet has specific expectations on their side which are not met.

```
ERR 2024-03-19 09:32:33.670-07:00 Can't fetch community token owners         topics="community-tokens-service" tid=271622 file=service.nim:1407 chainId=421613 contractAddress="\"0x24b23b3f095f33909b23cff69fc67f6c67242d026a1b93b16a02a4f308cfcf4b-master\"" errorMsg="\nstatus-go error [methodName:wallet_getCollectibleOwnersByContractAddress, code:-32602, message:invalid argument 1: json: cannot unmarshal hex string of odd length into Go value of type common.Address ]\n"
```

Because of the error, we seem to be unable to retrieve the token owners.

```
ERR 2024-03-19 09:32:33.670-07:00 Can't fetch community token owners         topics="community-tokens-service" tid=271622 file=service.nim:1407 chainId=421613 contractAddress="\"0x24b23b3f095f33909b23cff69fc67f6c67242d026a1b93b16a02a4f308cfcf4b-owner\"" errorMsg="\nstatus-go error [methodName:wallet_getCollectibleOwnersByContractAddress, code:-32602, message:invalid argument 1: hex string has length 70, want 40 for common.Address ]\n"
```

**Comment by jrainville** [comment]
Ah, maybe we use the pubkey by accident instead of the address. The Owner does have access to the addresses, we might have an issue in the code where we don't grab them from the DB first.

**Comment by kounkou** [comment]
Welp my problem disappeared

https://github.com/status-im/status-desktop/assets/2589171/24316b6a-abf1-4403-81a3-34efc96e2390

**Comment by kounkou** [comment]
> Ah, maybe we use the pubkey by accident instead of the address. The Owner does have access to the addresses, we might have an issue in the code where we don't grab them from the DB first.

I checked those contract addresses, they are temporary generated most probably from this code :

```nim
...
  proc temporaryMasterContractAddress*(ownerContractTransactionHash: string): string =
    return ownerContractTransactionHash & "-master"

  proc temporaryOwnerContractAddress*(ownerContractTransactionHash: string): string =
    return ownerContractTransactionHash & "-owner"
...
```

I'll continue the dive deep
