### ISSUE TITLE
ENS name can't be purchased on Sepolia

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#13697]
### Description

The app is saying i have to have SNTs when being on Sepolia testnet which is wrong

<img width="1512" alt="Screenshot 2024-02-23 at 10 17 20" src="https://github.com/status-im/status-desktop/assets/82375995/06258178-e53b-4a66-9649-ce6a28251285">

And i have a lot of STTs on Sepolia for this transaction

<img width="1512" alt="Screenshot 2024-02-23 at 10 19 31" src="https://github.com/status-im/status-desktop/assets/82375995/536640be-69e5-48f5-bfb7-fd033dc9b7dd">

**Comment by anastasiyaig** [comment]
@alaibe i talked to @0x-r4bbit and it seems to be UI issue

**Comment by 0x-r4bbit** [comment]
Did some digging. Turns out the app isn't taking into account that there can be multiple testnets to operate on when inside the ENS module.

Here's what happens:

1. The UI determines a users SNT/STT balance and uses that to figure if one can buy an ENS in the first place: https://github.com/status-im/status-desktop/blob/f31f01d64b263aea422a84d70f079f6c49be06b0/ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml#L40
2. The `sntBalance` property used there is calculated in the `EnsNamesStore` here: https://github.com/status-im/status-desktop/blob/f31f01d64b263aea422a84d70f079f6c49be06b0/ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml#L40 What's important is that it uses some `sntToken` to calculate this (https://github.com/status-im/status-desktop/blob/f31f01d64b263aea422a84d70f079f6c49be06b0/ui/app/AppLayouts/Profile/views/EnsTermsAndConditionsView.qml#L35)
3. The `sntToken` is ultimately retrieved from the `ensUsernamesStore` (https://github.com/status-im/status-desktop/blob/f31f01d64b263aea422a84d70f079f6c49be06b0/ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml#L127-L131)
4. Which takes us to the ensService's `getStatusTokenKey()` function: https://github.com/status-im/status-desktop/blob/f31f01d64b263aea422a84d70f079f6c49be06b0/src/app_service/service/token/service.nim#L408
5. And that one does a simple if/else check on whether one has testnets enabled. If yes, it'll use `STT_CONTRACT_ADDRESS`
6. Which turns out to be hardcoded to the goerli address: https://github.com/status-im/status-desktop/blob/f31f01d64b263aea422a84d70f079f6c49be06b0/src/app_service/common/wallet_constants.nim#L7

So this doesn't take into account that there can be different testnets (with different contract addresses).

**Comment by alaibe** [comment]
PR: https://github.com/status-im/status-desktop/pull/13636
