### ISSUE TITLE
[Communities] Do not propagate channels to members if they do not have permissions and `hideIfPermissionsNotMet` is true

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#13878]
In issue https://github.com/status-im/status-desktop/issues/13291 we added a functionality to hide chats for members who do not have permissions to view them. Chats are hidden only in UI but they are still propagated to members by control node.
In this task we want to stop propagate chats to members if above conditions are met.
We should do this in the same manner as "Hide permission" feature.

**Comment by jrainville** [comment]
@benjthayer @John-44 I was wondering if this encrypting of hidden channels is something we want.

If we do this, those channels will never appear in the Join popup when you check your addresses, even if you do fit the permissions.

- Option one is to leave it as is and only hide in the UI:
  - pro: it keeps the join flow as is where you can see the hidden channels in the Join popup if you do meet the requirements.
  - con: the hidden channels can easily be "leaked" by UI bugs or just by printing them from the backend
- Option two is to implement this ticket and encrypt them:
  - pro: impossible to leak. Also fixes the "bug" where hidden channels can appear when you don't have the tokens because we are checking the permissions
  - con: the join permission popup will never see those channels

**Comment by John-44** [comment]
@jrainville I think option one (leave as is and hide in the UI).  The content of the channels is encrypted which is the important thing, and the Join flow will become a bit broken if we do option 2.  The leakage is channel names (not content), but I don't see any way around this while preserving the 'accounts to share with the community' flows.

**Comment by jrainville** [comment]
I'll close this issue then as we do not want to encrypt the channel metadata (name).
The solution will stay on the UI side.
