### ISSUE TITLE
[Wallet/Graph] Analyze all graph use cases needed and confirm what can be done

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#13936]
### Description

- List the needed features
- Check if the current version of the component supports these features
- If not, check on the possibility of update version
- Plus: look at other qml wrapper components that can maybe offer us better benefits

**Comment by alexjba** [comment]
ChartJs supports all of our needs, but to speed-up the development we need to use some ChartJs plugins. Unfortunately to support the latest ChartJS version (or at least a 3.x) we'll need to adapt the ChartJs library to Qt's more limited standard support. Haven't found any reason to invest more time in this because the latest 2.x version is sufficient for the wallet graphs. The only additional feature we could use from the latest ChartJS versions is the data decimation, but it's not mandatory.

That this task will provide:
1. Out of the box support for ChartJs plugins supporting ChartJs 2.9.4. (https://www.npmjs.com/search?q=chartjs-plugin-, https://github.com/chartjs/awesome) and QML integration
2. Integrated [Crosshair plugin](https://chartjs-plugin-crosshair.netlify.app/samples/) - this adds basic support for zoom, pan and crosshair
3. Integrated [DataLabel plugin](https://v1_0_0--chartjs-plugin-datalabels.netlify.app)
4. Adding Storybook examples

**Comment by iurimatias** [comment]
moving to 2.31

**Comment by caybro** [comment]
> moving to 2.31

We have the PR ready, it would be better to merge it for 2.30 in order not to run into many conflicts in the future
