### ISSUE TITLE
Request to join community always use keycard flow

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#13974]
Currently when requesting to join a community, the keycard flow is always the flow the user goes through

https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=45015-290195&mode=design&t=kvgycWyxjrhQLyDt-0

Fix: if user don't have keycard, shows not keycard flow

**Comment by jrainville** [comment]
For additional context, we used to only have the password flow, then the keycard flow was added and became the only flow in [this PR](https://github.com/status-im/status-desktop/issues/12170).

So a partial revert with some conditions might be possible.

Also, note that if there is only one Keycard,  the flow is also simpler than what we have right now (see Figma's centre flow)

**Comment by noeliaSD** [comment]
Related to that: https://github.com/status-im/status-desktop/issues/13988

**Comment by saledjenic** [comment]
I've just checked the issue, so what I did:
- created a new account (regular, not keycard account) and asked to join a community

<img width="2776" alt="5" src="https://github.com/status-im/status-desktop/assets/86303051/a355003c-a30b-46b6-b37c-0310c53ce636">

- as can be seen, the password popup was displayed, which is expected and I managed to authorize an action using it, on the right screen in the screenshot blow we can see that the request was received by the community

<img width="2766" alt="6" src="https://github.com/status-im/status-desktop/assets/86303051/b8c00fa7-cb25-4dad-86f4-36249eaf642d">

- then I canceled the membership on the left side, a change on the left side (sender side) was good, a change on the right side (community owner side) was good, and the pending request was removed, as can be seen in the screenshot below

<img width="2761" alt="7" src="https://github.com/status-im/status-desktop/assets/86303051/06702be3-6671-41f9-bf06-f502544da52d">

- then I migrated the left side user to a Keycard and tried to make a community request again and the entire process went well, I was able to authenticate the request to join the community and successfully sent it using the keycard

<img width="2778" alt="8" src="https://github.com/status-im/status-desktop/assets/86303051/7b07598b-c697-49b1-9738-fd5385d6f4ad">

- at this step, as can be seen in the screenshot below the joining community request was not received by the community, but that's another issue, not the one this issue is about, I checked and I am sure that after authentication the request was sent (called `wakuext_requestToJoinCommunity` without any error).

<img width="2761" alt="9" src="https://github.com/status-im/status-desktop/assets/86303051/3ad85720-d6f1-4873-8474-334afeca3fe4">

**Comment by saledjenic** [comment]
Fixed via https://github.com/status-im/status-desktop/issues/13988, in this PR: https://github.com/status-im/status-desktop/pull/14024
