### ISSUE TITLE
Not possible to send community asset with decimal points specified

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14074]
### Description

https://sepolia-optimism.etherscan.io/tx/0x1012f175b0fef7fd541dbdcf6ff04c0fbb668ecece5fdfc5e66e5dcaeadf9a40

https://github.com/status-im/status-desktop/assets/82375995/5e3d3dcf-7d99-413b-b477-5b16ca864929

**Comment by stefandunca** [comment]
Found the root cause for community tokens not working. The tokens is sent as a contract deployment (to is `0x0`), not sure how come I missed this. It seems the symbol won't resolve to a contract address due to differences in how identify tokens. I have to move the implementation to use `tokensKey`, I checked that is available in UI which I will do next.
