### ISSUE TITLE
Wallet: [sending] activity record is not replaced when transaction is finalised

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14071]
### Description

I just sent 1 stt on Sepolia to wallet address and i have now 2 records for the same transaction in activity history 

https://sepolia.etherscan.io/tx/0x7487e4a9e8c9e85e0556cc353dec4b6292cbb86f49d01da51f21f7e9878c7fda

<img width="1149" alt="Screenshot 2024-03-21 at 12 35 10" src="https://github.com/status-im/status-desktop/assets/82375995/bcdc8d4c-c5a3-4849-9999-313ba4ec7fa1">

**Comment by stefandunca** [comment]
After more debugging the corner case observed is that for some non-native token transfers when both sender and recipient are in the accounts list only one entry is downloaded instead of the usual two (sender as owner have MTID and second doesn't have). However, the MTID one is overwritten. I will continue on this path.

**Comment by stefandunca** [comment]
Found that in case of same accounts and ERC the original transfer entry is overwritten with another transaction and there is only one left, still not sure why.
