### ISSUE TITLE
Improve `SharedAddressesPermissionsPanel` component since it has some performance penalties due to the way it's built

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#14276]
### Description

When entering `Edit shared addresses` dialog, it takes some time, rather than being a smooth and instantaneous navigation. It also hangs like a minute after being opened.

The performance problem perceived by the user is noticeable when we work with a large community with multiple permissions such as `Status CC`.

https://github.com/status-im/status-desktop/assets/97019400/aba97d8e-01f8-45ac-a182-361b40dd06e1

Improve `SharedAddressesPermissionsPanel` component to be more efficient.

**Comment by caybro** [comment]
Having a look at this

**Comment by caybro** [comment]
After some investigation, it's obvious we're doing some heavy QML stuff here in this component. In the longterm (for 2.29 maybe) we should spend some time and write a dedicated data transformation model in C++ so that we don't have to do the partial calculations inside the Repeaters; and then the QML part can be greatly simplified. If we need a really quick/hotfix for 2.28, we should maybe consider disabling displaying of the channel-related permissions in this dialog imho

However, surprisingly maybe, the biggest offender is this little part:

![image](https://github.com/status-im/status-desktop/assets/5377645/859d855f-0609-4625-b0bf-886320010126)

Which takes a whopping overall 20% of time, most of which is spent inside the `HoldingsSelectionModel`
