### ISSUE TITLE
Member list empty for all permissioned channels in the Status Community

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14296]
# Bug Report

## Description

![image](https://github.com/status-im/status-desktop/assets/11926403/6c89cd87-5b20-4111-a673-dc5f561ceeee)

## Steps to reproduce

We don't know how it happened. Since yesterday, I couldn't see any member. Even Iuri (control node) can't see them.

#### Expected behavior

Permissioned channels have at least Admins+ as members plus those that fulfill the requirements

#### Actual behavior

All permissioned channels' members list are empty

### Additional Information

- Status desktop version: 2.28 RC5 (tested on RC3 too)

**Comment by jrainville** [comment]
Seeing the logs, it seems like the issue comes from the database locked issue.

We don't have the info yet how it started though.

@cammellos did you manage to find anything?

[iurilog.txt](https://github.com/status-im/status-desktop/files/14877151/iurilog.txt)
[iurilog2.txt](https://github.com/status-im/status-desktop/files/14877152/iurilog2.txt)

**Comment by cammellos** [comment]
@jrainville we don't get that issue, we had `database is closed`, but it turns out that's a bit of a different one (race conditions on login/logout, as far as I can see).

```
[91mERR[0m 2024-04-04 16:32:04.965-04:00 [1mrpc response error                        [0m topics="[93mrpc[0m" [91mtid[0m=[94m2278[0m [91mfile[0m=[94mcore.nim:36[0m [91merr[0m=[94m"\nstatus-go error [methodName:wakuext_checkAllCommunityChannelsPermissions, code:-32000, message:database is locked ]\n"[0m
[91mERR[0m 2024-04-04 16:32:04.965-04:00 [1merror doing rpc request                   [0m topics="[93mrpc[0m" [91mtid[0m=[94m2278[0m [91mfile[0m=[94mcore.nim:40[0m [91mmethodName[0m=[94mwakuext_checkAllCommunityChannelsPermissions[0m [91mexception[0m=[94m"\nstatus-go error [methodName:wakuext_checkAllCommunityChannelsPermissions, code:-32000, message:database is locked ]\n"[0m
```

We don't use `checkAllCommunityChannelsPermissions` anymore on mobile, I had a chat with @kounkou a few days ago, and I don't think desktop needs to use it, that's an expensive endpoint and likely that's hogging the database?

But before, the client would check member permissions periodically with Infura, but that's not their responsibility (they should only in the case you want to show whether they  **could** have access to the channel, but I don't believe we do that in the UI). 
Control node should do all the checking, publish community description, and clients should just check that, without making any call to infura (or `checkAllCommunityChannelsPermissions`).

Though not sure about desktop, @osmaczko can confirm that this is generally (or correct me) what we want to do, clients should not be "self-checking" their own permissions.

**Comment by osmaczko** [comment]
> Though not sure about desktop, @osmaczko can confirm that this is generally (or correct me) what we want to do, clients should not be "self-checking" their own permissions.

I believe there are scenarios where clients must check permissions by their own.
- When you are not yet a member of the community, the control node is not aware of you, so you need to check the 'become a member' permissions on your own. On the desktop client, you cannot send a request to join if you do not meet the criteria.
- When you are not a member of given channel, it is required to show which criteria are satisfied and which are not on [the overlay screen](https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?node-id=2578%3A353802&mode=dev).

Currently, clients check channel permissions at the app's startup and then again each time a channel becomes active. This process should be optimized to check permissions only for channels of which we are not members. An issue has been created to address this: https://github.com/status-im/status-desktop/issues/14220. Also, I believe, this logic should be status-go driven, meaning Community object should already contain information which criteria are satisfied and which not, for every not joined channel.

**Comment by cammellos** [comment]
Thanks @osmaczko for the reply, we had a discussion on chat to align ourselves, and we both agreed that:

1) We should only check permissions when the overlay screen is presented to the user, ideally only for that particular channel. Patryk also suggested some caching mechanism.
2) Permissions to view/post on the channel should be dictated by the communitydescription object, `canPost`/`canView` can be used, or checking for membership can be used instead of `canView` (they are equivalent).

So in pseudo code:

```
WHEN user_clicks_on_channel {
   IF user_can_view || user_can_post
      access_channel_without_checking_permissions
   ELSE
      show_overlay_and_check_permissions
     }
```

Patryk, correct me if I haven't captured things correctly

thank you

**Comment by osmaczko** [comment]
^ Seems correct. @cammellos thanks for summary :pray:

**Comment by caybro** [comment]
Sorry to spoil the party, that's not entirely true; from the UI perspective, we need all channels permissions, and we need to recheck them everytime we select/unselect a wallet account:

![image](https://github.com/status-im/status-desktop/assets/5377645/02063ec0-b715-463d-8ccf-62567c988754)

**Comment by caybro** [comment]
But this can of course happen on demand, only when looking at this dialog

**Comment by cammellos** [comment]
> But this can of course happen on demand, only when looking at this dialog

yes, that's something I mentioned throughout:

```
they should only in the case you want to show whether they **could** have access to the channel, but I don't believe we do that in the UI).
```

sorry if it wasn't clear, I am not familiar with desktop designs (don't have access to them either I believe), but that's a valid case, but should only happen as you mentioned when we show this dialogue

**Comment by jrainville** [comment]
All that was said above is correct . I'll move the refactor issue to address this problem to 2.29. It seems like a very big improvement, too big to wait for the refactoring weeks at the end of the cycle.

**Comment by caybro** [comment]
Great, and another remark from the UI perspective: since we need to enable/disable the "Join/Save" button (see https://github.com/status-im/status-desktop/issues/14299), it would be beneficial to know which of the checks (join and/or channels) is pending (not the combinations of the two)
