### ISSUE TITLE
Permissions requirements that are not met are being hidden on the community permission overlay

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#14446]
# Bug Report

## Description

User 1: Create open community
User 1: Mint owner token
User 1: Mint and airdrop a "member" token
User 1: Create permission requiring "member" token and TokenMaster token to join

User 2: Visit community

Permissions overlay initially displays requirement for member token + token master token but then after a few seconds hides the criteria that is not met by the account, the token master requirement. This incorrectly shows only the "member" token as being required.

#### Expected behavior

User is informed of ability to join by holding member token + token master token.

### Additional Information

- Status desktop version: 2.28.1 RC1
- Operating System: Mac

**Comment by noeliaSD** [comment]
The requirements related to PRIVATE permissions are the following:
- If permission is PRIVATE, it will ONLY be shown when the criteria is MET. Otherwise, they are hidden.

@glitchminer , correct me if I'm wrong, but I understand that this is the current behavior so, not showing the `token master` permission to this user, is correct.

However, I understand that while the first "permission check" is in progress, this token master permission is displayed to the user so, probably we should avoid this situation. We need to ensure the user meets this private requirement until showing it.

**Comment by glitchminer** [comment]
@noeliaSD , it's not the token master permission itself is hidden. The issue in the example is where 2 tokens are required to become a member but the the joining account is missing one of them, it just happened that one of the tokens specified was the TM token. The permission to become a member was not hidden.

The one the account does not hold is not being displayed, so they only see half the requirement. Another example would be if the account does not hold USDC then they only see the need for "Member".

![image](https://github.com/status-im/status-desktop/assets/50769329/b859c6d8-0bb4-449e-be30-125712643492)
