### ISSUE TITLE
Get API keys for CoinGecko and CryptoCompare

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14509]
### Description

Problem: we receive market data from CoinGecko and CryptoCompare and we're using their "free" plans currently.

The Free plan has per-IP-Address limits, which works fine as long as we're not all in the same hotel using Status at the same time.

We need to get some paid plans and API keys for this services so they are reliable

**Comment by anastasiyaig** [comment]
@churik @iurimatias @John-44

**Comment by anastasiyaig** [comment]
@alaibe adding you as well

**Comment by jakubgs** [comment]
Even more centralized services being added to the App? Really?

**Comment by jakubgs** [comment]
Okay, but what kinda of scale do we want for this? Honestly regardless of which plan we pick once people start using this we will hit the limit, but do you have any idea what numbers we need right now?

![image](https://github.com/status-im/status-desktop/assets/2212681/5b978f41-8fdd-4413-9310-389c00c6da5e)

**Comment by anastasiyaig** [comment]
i would like to hear opinions from wallet team and @John-44 
cc @iurimatias

**Comment by dlipicar** [comment]
Hey there! Sorry for the delay in commenting.

So, we're using both CryptoCompare and CoinGecko in a way that's not even properly documented. According to their docs, even if you don't pay you're supposed to use an API key, which has terrible (per API key) limits

![image](https://github.com/status-im/status-desktop/assets/11161531/9e452a49-2789-407e-85d1-655628951b41)
![image](https://github.com/status-im/status-desktop/assets/11161531/a289c3bf-9f8d-46fb-a61b-f33e6bd69f7a)

We're not using API keys for any. The closest thing we have is an identifier for CryptoCompare calls, not sure if we have some special arrangement with them:
![image](https://github.com/status-im/status-desktop/assets/11161531/eaac6a7c-54ad-4f0e-98d8-78b69d524224)

Anyway, this lets us have per-IP-address limits which is awesome for our use case. However, this is dangerous because:
- Conditions for this no-API-key usage could change at any moment or it might even be disabled
- If several people use Status from the same location with a shared IP address (offsite, presenting Status at some crypto event), we hit the limits very quickly and the wallet becomes useless

So, the plan was to keep trying to use the free plan initially, but use an API key if our requests get throttled/denied. I've got the logic for this implemented, but still need to do some tests. However, there's still some issues:

Cryptocompare's `Commercial` plan allows only one user per license, which is no good for the current way we use their service. We'd need to get a custom plan suitable for our "decentralized" usage. 
![image](https://github.com/status-im/status-desktop/assets/11161531/28f9fe28-23ff-4931-9363-ca6c592ed9a9)
Unless we set up a proxy server to concentrate calls :D

I don't have exact usage stats, but with a 10min refresh period I think 1M calls/month would be good for a few hundred users. Unless we set up caching in our proxy server :D :D

CoinGecko's plans seem less restrictive, but I'm concerned about the calls/min limit (proxy server? :D :D :D)

Regarding privacy, requests to these APIs only include token symbols, no information about accounts.

**Comment by jakubgs** [comment]
That all sounds terrible. And nobody has the time to develop a proxy server. Best we can do is just an nginx with some caching, but even that could easily be overwhelmed.

I have yet to hear any actual concrete request for a proxy server, just conversations, so until someone actually explains what is necessary, at what scale, and for what service, there is no proxy.

**Comment by saledjenic** [comment]
Was logged here https://github.com/status-im/status-desktop/issues/14591 as well.

**Comment by anastasiyaig** [comment]
So what is the decision there? @iurimatias

**Comment by iurimatias** [comment]
@anastasiyaig we'll try the proxy approach so long users have a fallback

**Comment by jakubgs** [comment]
Indeed, the work is being done in: https://github.com/status-im/infra-proxy/issues/1

**Comment by anastasiyaig** [comment]
Alright thanks!
