### ISSUE TITLE
Add a line to the balance chart that reflects profit/loss

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-desktop#14558]
### Description

Balance chart does not contain information on actual fiat profit/loss from ETH/tokens prices changes, not including deposits/received crypto.
If user wants to know profit/loss, they must calculate it themselves (this is how I do this in Ledger app, their balance chart is useless for it). It would be nice for user to see this information on chart instead.

Current version of Chart.js (4.4.2) supports multi-axis charts: https://www.chartjs.org/docs/latest/samples/line/multi-axis.html
But we are using v2.9.3 for now, which does not support it.

According to @benjthayer:

> We could show 2 lines on the chart - one for balance and one for profit and loss. We would need 2 Y axes to do that.

**Comment by caybro** [comment]
CC @alexjba (who's recently worked on the charts); TLDR we can't upgrade any further

**Comment by alexjba** [comment]
@IvanBelyakoff Do you have a visual example you could share?

Not sure if what we have in this PR helps https://github.com/status-im/status-desktop/pull/14433. The print screen below shows multiple datasets in the same chart. If I understand correctly this is what we would need.

<img width="809" alt="Screenshot 2024-04-30 at 21 58 55" src="https://github.com/status-im/status-desktop/assets/47811206/df511e38-401d-4d70-9495-c748de437ac5">




> Current version of Chart.js (4.4.2) supports multi-axis charts: https://www.chartjs.org/docs/latest/samples/line/multi-axis.html
But we are using v2.9.3 for now, which does not support it.

Anything beyond 2.9.4 would require extensive dev effort to adapt the library because it's incompatible with the JS support we have in Qt.
