### ISSUE TITLE
Community preview in community portal shows invalid data (members count)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14567]
### Description

Community portal preview:

<img width="1163" alt="Screenshot 2024-05-02 at 10 27 16" src="https://github.com/status-im/status-desktop/assets/82375995/dc110bcf-5d21-4a40-8ccf-a0e58987b729">

Actual community (45 members, 3 tags):
<img width="1165" alt="Screenshot 2024-05-02 at 10 32 36" src="https://github.com/status-im/status-desktop/assets/82375995/3140c47b-1b8f-46dc-a623-f7686626df2f">

**Comment by anastasiyaig** [comment]
@jrainville how important is it? Maybe some quick tweak we can easily do with community curation dapp? 
cc @glitchminer @lukaszso

**Comment by caybro** [comment]
I think we show `0` since it's a closed community, yet the number of active users still somehow creeps in :)

**Comment by anastasiyaig** [comment]
@caybro good point , i was thinking of the same that it is somewhat related to the fact it is closed community. Not sure if that is important tho, just noticed

**Comment by jrainville** [comment]
Mine shows the right number of members:
![image](https://github.com/status-im/status-desktop/assets/11926403/8bac73da-c265-4661-bcaf-a8600be089db)

I am a member of it though. 

In theory, we will switch the community to Open when we release, so the problem shouldn't appear if it is indeed about the encryption.

Just to confirm, when you did that screenshot @anastasiyaig , you were **not** a member right?

If it turns out there is a bug, let's just hide it for now, but in this case, it will probably be resolved when we open it. We could also hide the member count if it is a closed community.

The only visual thing that's annoying is the small arrow on the bottom left.

**Comment by anastasiyaig** [comment]
yup @jrainville the screenshot with weirdo information is taken from the app with account that is not a member of that community

**Comment by jrainville** [comment]
Gotcha. We were planning on testing putting the community open before the release, so we can keep this open until we do that test to see if it all resolves.

Though we could still go with the solution to hide the member count when the community is closed, because there is nothing we can do about that for now

**Comment by jrainville** [comment]
I just checked the code and we actually already handle it: `memberCountVisible: model.joined || !model.encrypted`
So we should be hiding the member count when the community is encrypted.
So there is indeed a bug.
It's probably simple. I'll try to get it fixed this week

**Comment by caybro** [comment]
> Maybe we should just port that commit to the release branch since it fixes the member count issue.

That's the thing... I didn't touch the member count at all :) There's another bug though, the "lock" icon is always closed due to CommunitiesGridView.qml having:

```qml
readonly property bool requirementsMet: !!model.allTokenRequirementsMet ? model.allTokenRequirementsMet : false
```

which simply doesn't exist in the model

**Comment by caybro** [comment]
@anastasiyaig it's unclear which branch the issue is from; looks like we might have a diff between master and the release branch somewhere

**Comment by anastasiyaig** [comment]
@caybro i am sorry for confusing you, so i checked with 2.28.1 rc4 and 2.28.0

**Comment by jrainville** [comment]
> I think the current code is fine then?
> 
> ```qml
> memberCountVisible: model.joined || !model.encrypted
> ```

Ah, it seems like the code I shared was from master, not `release/2.28.x`, so the fix is just to port that code to the release branch

**Comment by caybro** [comment]
> > I think the current code is fine then?
> > ```qml
> > memberCountVisible: model.joined || !model.encrypted
> > ```
> 
> Ah, it seems like the code I shared was from master, not `release/2.28.x`, so the fix is just to port that code to the release branch

Yup, needs a backport to the stable branch then, mystery solved :)

**Comment by anastasiyaig** [comment]
it is in rc now , closing. The only thing i noticed is that Ethereum tag is missing an icon


![Image](https://github.com/status-im/status-desktop/assets/82375995/25f1b64e-55ca-442b-b312-cf983c2e8cad)
