### ISSUE TITLE
Aligning avatar initials display (desktop/mobile)

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#14667]
# Bug Report

NOTE: Aligning colors is excluded to a separate task: https://github.com/status-im/status-desktop/issues/14842

## Description
There is an inconsistency with the usage of the accent color within the app, leading to discrepancies in avatar colors and initials between the desktop and mobile versions. Below is a screenshot illustrating the issue:
![Screenshot](https://github.com/status-im/status-desktop/assets/4557972/03b53ed4-072d-4a65-b139-6312a620969e)

For more details on the implementation, refer to these pull requests: [PR#19087](https://github.com/status-im/status-mobile/pull/19087) and [PR#18517](https://github.com/status-im/status-mobile/pull/18517#issuecomment-1914867210).

## Steps to Reproduce
1. User1: Create an account on Desktop named `Two letters desktop` without setting a user picture.
2. User2: Create an account on Mobile with a custom color, named `Two letters lily`, without setting a user picture.
3. User3: Create an account on Mobile named `Noaccent1word`, without setting a user picture.
4. Add all the above users as contacts.

### Expected Behavior
Both chats and contact lists should appear identical on Desktop and Mobile.

### Actual Behavior
1. **Different Initials:**
   - On Desktop, `User 2` and `User 3` display as "TW" (first two letters of the first word).
   - On Mobile, `User 2` and `User 3` display as "TL" (aligned with the design).

2. **Different Colors:**
   - On Desktop, contact colors appear random.
   - On Mobile, contacts use accent colors; if not set, the default fallback color (blue) is used.

### Requirements for Resolution:
- [ ] Desktop should not assign colors randomly; it should default to blue or use the accent color (should be aligned with the desktop design. Since there is no accent color flow in the desktop version yet, this would be considered an initial iteration)
- [ ] Desktop should align with Mobile regarding initials: display the first initials of two words (e.g., `Alice InWonderland` should be `AI`). For a single word, use only the first letter (e.g., `AliceInWonderland` should be `A`). This applies to both user profiles and contact/chat lists.
- [ ] Accent colors should be consistent across Desktop and Mobile: contacts should use the fallback color (blue) or the contact's set accent color.

### Additional Information
- Status Desktop/Mobile Version: nightly 09/05;

**Comment by micieslak** [comment]
Mobile/Desktop user icon color discrepancies:

- In the mobile app the user icon color is equal to `customizationColor`. The color can be selected when creating account and can be changed later. Whenever changed other will see the updated color of the contact.

- In the desktop app the user icon color is always derived from public key. It means that it's not known upfront in a account creation flow. It can't be changed later neither (however there are two sets of colors, for light/dark theme). 

To align colors among mobile/desktop there are two options:

- use customization color on desktop. Currently it requires changing 20+ qml files and also many nim files. `customizationColor` must be propagated wherever it's needed bc currently used mechanism allows to compute color on the fly only from pubKey (the color is not stored). Light/dark theme versions of customization colors should be prepared probably. Moreover currently customization color is not used in any way on desktop, user icon color would be an exception here. Probably it also collides with approach based on dark/light variants.

- use pubKey-based color generation on mobile. This way should be simpler because it depends only on pubKey which is a basic identifier of any contact. The additional benefit is that fixed color is probably the easiest to remember visual identification of the contact.

It's not clear for me which option is best one for now. @noeliaSD, @osmaczko, @churik please share your opinion about that.

**Comment by noeliaSD** [comment]
> use pubKey-based color generation on mobile. This way should be simpler because it depends only on pubKey which is a basic identifier of any contact. The additional benefit is that fixed color is probably the easiest to remember visual identification of the contact.

But with this option, what you are suggesting is that all flows related to changing the profile color on the mobile should be deleted, right?

I think this is a design mismatch between mobile and desktop and we need to clarify the correct requirements for them first with the design team. Do we want to change the profile color or not @benjthayer @xAlisher ?

In case of YES, then I see kind of a risk of doing this change now since we are almost in the end of the milestone cycle and if this fix implies changing this amount of files, I'd postpone it to `2.30` if there's no objection. WDYT @churik ?

Also, if the answer is a YES, we will need a proper design on `desktop` to cover the color edition flows @benjthayer .

**Comment by benjthayer** [comment]
I don't really have definitive answers here but a couple of thoughts to chip in regarding the colour and initials issues raised:

**Regarding profile initials:**
I don't see an issue with aligning with mobile other than the fact that with the mobile way of doing things we might see a lot of users with the same first initial - see this related issue raised on Figma:

<img width="741" alt="Screenshot 2024-05-15 at 17 47 34" src="https://github.com/status-im/status-desktop/assets/110033914/18b2bf0e-12f9-47d5-9c44-4579b028f79c">

What we could do is show the first 2 letters of a single word profile name and the first letter of both of the first 2 words of a profile name with 2 words or more but that feels like mixing logic so I lean slightly more towards the desktop way of initialising (first 2 letters of first word in profile name). WDYT @xAlisher - you probably have more context for how things were thought out on mobile in this regard?

----

**Regarding the default colour:**
Any change to how this is generated is likely to have a greater visual impact on mobile - the blue is a nice high contrast colour so it's provision to new users who don't want to necessarily pick a customisation colour right away has usability advantages. I'm not sure it would be a good idea to change this behaviour. Perhaps we can keep the colour generation methods independent (as long as we are pulling from the same colour palette) and for future iterations of the desktop when we have more time, implement a more consistent approach where the user is given the default blue but we supply the ability for the user to change this upfront. It's quite edge case that the user will create new profiles with exactly the same names on the 2 platforms so its unlikely they will be too concerned with this disparity?

**Comment by osmaczko** [comment]
IMHO, the icon color should not be strictly correlated with the accent color.

- The icon color is propagated through the network, while the accent color is a local setting of the app. We may want to keep the accent color private from the rest of the world.
- Having the same default icon color for every user will result in a members list with one dominant color.
- The icon color is derived from the pubkey and, as a consequence, is a part of visual identity representation. It is easy for the eye to remember. If it becomes customizable, we'll lose this advantage.

I am opting for deriving the icon color from the pubkey, as in the Desktop, and keeping the accent color setting for everything else in the app. That's also the simplest way to align I believe.

**Comment by churik** [comment]
> What we could do is show the first 2 letters of a single word profile name and the first letter of both of the first 2 words of a profile name with 2 words or more but that feels like mixing logic so I lean slightly more towards the desktop way of initialising (first 2 letters of first word in profile name). WDYT @xAlisher - you probably have more context for how things were thought out on mobile in this regard?

@benjthayer 
I'd prefer to go with the easiest option for now. Let's not redo it for both clients, at least for the time being. On mobile, it matches the design and has already been implemented to show the initials of the first and second words in the name. It seems to me that we just need to align it for now with minimal cost. Correct me if I'm wrong, @cammellos.

> use pubKey-based color generation on mobile. This way should be simpler because it depends only on pubKey which is a basic identifier of any contact. The additional benefit is that fixed color is probably the easiest to remember visual identification of the contact.

The problem is that it doesn't match our mobile design, which could create confusion. If aligning the colors is too complicated for now, we can start with the initials and address the colors later. What do you think?
@noeliaSD @micieslak

**Comment by noeliaSD** [comment]
Ok, so let's do that in 2 steps!

- **Letters** now but the designers need to agree bc it depends on their decision if the fix is for `desktop`, `mobile` or `both`:

  **2 words:**
    - _Option A_: Lauren Digby = LD
    - _Option B_: Lauren Digby = LA

  **1 word:**
    - _Option A_: Lauren = L
    - _Option B_: Lauren = LA

  ^^cc: @benjthayer @xAlisher 
  
- Please @micieslak continue the discussion for the **color** with the design team. If needed, create a separate task for it and assign the next milestone as a target (`2.30`).

**Comment by benjthayer** [comment]
> Ok, so let's do that in 2 steps!
> 
> * **Letters** now but the designers need to agree bc it depends on their decision if the fix is for `desktop`, `mobile` or `both`:
>   **2 words:**
>   
>   * _Option A_: Lauren Digby = LD
>   * _Option B_: Lauren Digby = LA
>   
>   **1 word:**
>   
>   * _Option A_: Lauren = L
>   * _Option B_: Lauren = LA
>   
>   ^^cc: @benjthayer @xAlisher
> * Please @micieslak continue the discussion for the **color** with the design team. If needed, create a separate task for it and assign the next milestone as a target (`2.30`).

@xAlisher and I spoke with @John-44 and the design team this morning regarding both the colour and initialisation issues. The following was the outcome:

1) Regarding initialisation, the consensus was to follow mobile:
- One initial for one word user names
- First initial of first two words for user names that have two words or more

2) The colour issue alignment was not a high priority and should be tackled for 2.23. No consensus on the approach there yet as it will require further discussion
