### ISSUE TITLE
Channels don't seem to become visible when you get added to channels (re-evaluation was done)

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14719]
# Bug Report

## Description

This issue should be looked at after https://github.com/status-im/status-desktop/issues/14220 and https://github.com/status-im/status-desktop/issues/14709 are done.

Jen (@kalinfinity) is an admin in the Status Community. When she first joined the community, she only had access to the public channels, which is expected since the new members need to be re-evaluated to know if they fit the channel permissions and this is done async.
However, after a long while, we saw that she still didn't have access to the private channels.
She saw that she had an AC notification from John in the #private-announcements channel. So she clicked on it and could see the channel and its content. She still couldn't see that channel in the channel list though.

After restarting the app, she could see them. So it makes me believe that probably we have a bug where if you are added to a channel after the re-evaluation is done, the app doesn't update the UI correctly to show the new accessible channels.

## Steps to reproduce

0. Have an open community with private channels that are hidden
1. Join the community
2. See that you only have the public channels
3. Add that user to admins/TMs
4. Wait for the re-evaluation to complete
5. The user still only sees the public channels
6. Restart the app
User can see all channels now

#### Expected behavior

User sees new channels as soon as they receive the new community description where they are a member of the channels

#### Actual behavior

User has to restart to see the new channels

### Additional Information

- Status desktop version: 2.28.1

**Comment by jrainville** [comment]
This might be fixed after the new refactor here https://github.com/status-im/status-desktop/pull/14993

**Comment by friofry** [comment]
The problem is still there, partially. Because one of the hidden channels is visible:

<kbd>

<img width="1225" alt="image" src="https://github.com/status-im/status-desktop/assets/1083341/86f9c77b-405a-433c-a6eb-918d41e1674f">

</kbd>

after restarting the app, all hidden channels are visible:

<kbd>
<img width="592" alt="image" src="https://github.com/status-im/status-desktop/assets/1083341/5fb98158-23d2-4ac7-a4c5-961cad627c9f">

</kbd>

**Comment by friofry** [comment]
Thanks to @micieslak, I found a way to easily inspect chat sections:

<img width="1511" alt="image" src="https://github.com/status-im/status-desktop/assets/1083341/05bb8178-cf74-4abb-9151-193c710fdc47">

I think the problem happens because communities/model.nim doesn't trigger the update signal for the ShouldBeHiddenBecausePermissionsAreNotMet role, because it's calculated in 2 steps. If I manually trigger the role change in `setData`, the problem goes away. First we need to calculate all dependent roles(MemberRole , HideIfPermissionsNotMet, canPost and canView), then it'll update the complex role. I think we should always calculate roles immediately.
