### ISSUE TITLE
Browser Plugin Connector SPIKE

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14795]
### Description

Spike to investigate the different ways that we can connect the Status app and a browser plugin.

### Acceptance Criteria

- A document or issue is created describing the different options investigated
- A final decision is made towards the solution

**Comment by kounkou** [comment]
# Connector implementation 

Status : `in progress, getting more input`

## Context

Status is building a `Browser plugin` that serves as a cryptocurrency wallet and gateway to blockchain applications. It primarily interacts with the Ethereum blockchain but supports other networks as well. To achieve the creation of the Browser plugin, Desktop core team will be involved in creating a `connector` that will connect Status-go and the Browser plugin by exposing the Wallet API’s. Here are proposals for implementing the solution.

## Requirements

- Being able to respond to API call from the browser plugin
- Being able to send events to the browser plugin without prior API call 

## Proposals

### 1. RPC server and IPC with statusd

Seems to be preferred solution since it already has most of the needed functionalities required. IPC component might be to low level here?

**Pros** :

- More elaborate service with configurable RPC and IPC
- Some handlers are already present and can be taken as example
- Support IPC for signal triggering 

**cons** :

- Might require some time to adapt to the code
- Launches a messenger entity built on top of Geth on top of Waku backend, do we need everything?
- IPC are very low level, would it work on any platform that we support + Tablet?

### 2. Media server

Very simple solution, but requires some more development time to add/enhance current functionalities with capacity to send signals? Enhancement might require stabilization afterwards ?

**Pros** :
- Very simple HTTP server
- Easy to dive into

**cons** :

- Require more development to add the needed functionalities
- Need to be enhanced with Websockets or IPC for sending signal to the Browser plugin
- Need to be enhanced with handlers logic to reach status-go/wallet
- Might require stabilization period before release

**Comment by MishkaRogachev** [comment]
I think we can close this issue with https://github.com/status-im/status-desktop/pull/15168
