### ISSUE TITLE
Members should use the wallet tokens instead of checking the chain when checking permissions

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14913]
### Description

Currently, when members need to check if they fit a permission for the edit shared address popup or the channel blurred screen, we do calls to providers to know on chain if we have the correct tokens.

However, this is very wasteful, because the wallet already has that information. We should be using the standard wallet APIs to ask if we the tokens.

If we are concerned about the accuracy of the data in the wallet, we can call the function to refresh the balances, but IMO it shouldn't be necessary. The wallet already tracks the activity and should update over time.

### Acceptance criteria

- the channel and join permission screens work as before, same with the shared addresses popup. The UI/UX should't be affected at all. If anything, it should be faster
- members no longer call the providers

**Comment by kounkou** [comment]
Hi, 

I wanted to start with some questions @jrainville 

just want to clarify, are we talking about the method call `GetCollectibleOwnersByContractAddress` https://github.com/status-im/status-go/blob/07de481b69a5f5d0272222833f42102ef4ac12cc/services/wallet/api.go#L353 call going through  Alchemy, Rarible and which is indeed part of the `EditSharedAddressesForCommunity` call flow for instance?

From this 
```
However, this is very wasteful, because the wallet already has that information. We should be using the standard wallet APIs to ask if we have* the tokens.
```

Are we assuming that Wallet does the caching of the list of tokens on a specific chain supporting our contract? If the answer is `yes`, I think this needs to be verified, I don't think those information are cached anywhere in Wallet per last check in 03/2024, but almost 3 months have passed 😄 already.

**Comment by jrainville** [comment]
> Are we assuming that Wallet does the caching of the list of tokens on a specific chain supporting our contract? If the answer is yes, I think this needs to be verified, I don't think those information are cached anywhere in Wallet per last check in 03/2024, but almost 3 months have passed 😄 already.

I thought so. We do have the list of collectibles for example in the wallet UI if you go in the collectibles tab.

Maybe it's not cached on app start, so we'd need to call the fetch method(s), but clearly we do gain access to that data at some point

cc @dlipicar

**Comment by dlipicar** [comment]
Soooo, we probably need to distinguish between 2 scenarios.

1) I'm the control node and I want to check permissions for all members of my community
2) I'm a community member and I want to check permissions for myself

We're discussing number 2 here, right?

`FetchCollectibleOwnersByContractAddress` gives you all addresses that own a collectible from a given contract address. AFAIK, a simple community member has no use for this.

As far as I understand, what a simple community member needs is the list of collectibles owned by their accounts. This is cached in the wallet DB (`collectibles_ownership_cache`) and we've got some logic to ensure the cache is relatively up to date + events telling you when the list for a given account+chain changes.

**Comment by jrainville** [comment]
> We're discussing number 2 here, right?

Yes exactly.

> AFAIK, this is much more information than what a simple community member needs. Instead, they just need the list of collectibles owned by their accounts.

Indeed. That's why we want to use the cache instead.

> This is cached in the wallet DB (collectibles_ownership_cache) and we've got some logic to ensure the cache is relatively up to date + events telling you when the list for a given account+chain changes.

Awesome, thanks for confirming.

@kounkou so it's seems like we do have a cache and it should be quite doable :smile:

**Comment by kounkou** [comment]
I spent some time to craft a manual testing to be able to have a control state when making the changes resolving this ticket.
For context, currently when we check the permissions, might it be when the screen is blurred (when  wanting to join a community for instance) or when editing shared addresses, we call 2 specific functions : 

- `GetBalancesByChain` found [here ](https://github.com/status-im/status-go/blob/89cf317641b79bae2bd5e3bb988382b139f8a856/protocol/communities/permission_checker.go#L254) 
- `GetOwnedERC721Tokens` found [here](https://github.com/status-im/status-go/blob/89cf317641b79bae2bd5e3bb988382b139f8a856/protocol/communities/permission_checker.go#L263)

These 2 calls will at some point call providers in order to get the information about collectibles to satisfy the permissions.
This is exactly the 2 functions that I will attempt to replace.

### Plan

Just replace the current logic of fetching the collectibles (2 functions stated above).
Please note that as of today permission re-evaluation is done every 10 min. I'll start implementation in a future PR.

### Out of scope ?

In @dlipicar message above, there is a mention of some logic to keep information update to date for client wanting to be notified of Updated, Removed or Created collectibles.

> and we've got some logic to ensure the cache is relatively up to date + events telling you when the list for a given account+chain changes.

To discuss, we might need to extend the changes by including a subscription to the `OwnershipUpdateMessage` and re-assessing permission upon create, update and delete collectibles update.
This implies possibly removing the current 10min timer for re-evaluation of permissions.

![Screenshot from 2024-05-28 13-19-40](https://github.com/status-im/status-desktop/assets/2589171/fbee620b-859b-4a61-8dd5-19f8ae16ad24)

**Comment by jrainville** [comment]
> Just replace the current logic of fetching the collectibles (2 functions stated above).

@kounkou FYI, `GetBalancesByChain` is for ERC20s (assets). Indeed we need to refactor that one too, but it won't be the same function, as for `GetOwnedERC721Tokens`. The wallet obviously gives the info for both, but just an FYI in case you would be replacing it all with a single collectibles function.

> To discuss, we might need to extend the changes by including a subscription to the OwnershipUpdateMessage and re-assessing permission upon create, update and delete collectibles update.
This implies possibly removing the current 10min timer for re-evaluation of permissions.

Let's do it later.

---

Another thing to note is that it's important that you don't remove the old check functions, as the control still uses them, ie the control node still needs to check the chain for the balances of members.

So it means that you probably need to create new functions for the member checks that will be local. Hopefully, you can do so in a way that reduces duplication. I guess it could be with the use of conditions (if member, use local check, if control node, use network checks)

**Comment by kounkou** [comment]
Submitted changes for `GetOwnedERC721Tokens` as I think it might be worth making the changes in 2 phases. All tests should be pass. I will perform further tests and will gather feedbacks from the team on areas I might need to put laser focus on.
