### ISSUE TITLE
The history nodes setting doesn't show anything and doesn't remember

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#14982]
# Bug Report

## Description

In Advanced, there is the History Nodes setting.
However, currently, it shoes as always empty:
![image](https://github.com/status-im/status-desktop/assets/11926403/959fb710-980a-4eb7-852c-d6ebbd763158)

Also, when you click on it, it doesn't seem to remember the last one that was selected:
![image](https://github.com/status-im/status-desktop/assets/11926403/9d8d0f3b-7c23-48e1-ac8a-f5ebc2ea2a6e)

## Steps to reproduce

1. Go to Settings -> Advanced
2. See that History Nodes shows `---`
3. Click on it
4. Uncheck "Select node automatically"
5. See that nothing is selected
6. Click one of them
7. Close the popup
8. It still says `---`
9. Click it  again
10. Still unslected

#### Expected behavior

The `History nodes` setting line tell which node it is connected to
When opening the popup, when not in automatic mode, it shows which one was manually selected

#### Actual behavior

No info about the current node

### Additional Information

- Status desktop version: 2.29.0 RC5
- Operating System: Ubuntu 22

**Comment by friofry** [comment]
Update:

1) In the DB we store `settings.pinned_mailservers` by ID: for example `shards.test':"store-01.do-ams3.shards.test`.
2) The sync module has an `activeMailServer` property which stores the nodeAddress that is updated when status-go sends a `MailserverSignal`. And here the server ID is converted to nodeAddress ending with the `statusim.net` domain (see fleet.go).
3) The allMailServers model in the `sync` module is loaded from fleets.json (where nodeAdresses end in `status.im`).

My suggestion is
a) Update the urls in fleet.go (or fleets.json) 
b) Or for activeMailServer signal we can use fleets.json instead of fleet.go to convert id -> nodeAddress

**Comment by yakimant** [comment]
@jakubgs, do we have `status.im` DNS records for all fleets?
Is it safe to just switch all configs to `status.im` or better to check case by case?

**Comment by friofry** [comment]
I think we need to make one more improvement:

To have a single source of truth for fleets:
1. move fleets.json to status-go
2. modify fleet.go and initialise it with fleets.json

**Comment by jrainville** [comment]
> I think we need to make one more improvement:
> 
> To have a single source of truth for fleets:
> 
> 1. move fleets.json to status-go
> 2. modify fleet.go and initialise it with fleets.json

Yeah that would be a good improvement. We can open a new ticket for that to fix in 2.30

**Comment by jakubgs** [comment]
You shouldn't be using `fleets.json` at all. We have DNS discovery with ENRTrees for a reason.
