### ISSUE TITLE
Owner token not available in community management tab after restart

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#15076]
# Bug Report

## Description

After app restart, community "forgets" about owner token.

## Steps to reproduce

1. Mint owner token
2. Restart the app
3. Go to community management Tokens tab

https://github.com/status-im/status-desktop/assets/33099791/808366ef-2801-4a3f-a253-9787a3a56519

#### Expected behavior

Minted owner and master-token are visible.

#### Actual behavior

No tokens are visible. 

### Additional Information

- Status desktop version: a3c9012f4ac959e7a3fef21268c550c55f7d332a (master)
- Operating System: Fedora

**Comment by osmaczko** [comment]
After some time, community is aware of the token owner again. Didn't do anything, so not sure what happened exactly.

**Comment by osmaczko** [comment]
It is lost again after restart :man_shrugging:

**Comment by friofry** [comment]
quick update:

if I change the `main/module.nim` with

```
proc createCommunitySectionItem[T](self: Module[T], communityDetails: CommunityDto): SectionItem =
  echo "Creating community section item for community ", communityDetails.id
  var communityTokensItems: seq[TokenItem]

  if communityDetails.memberRole == MemberRole.Owner or communityDetails.memberRole == MemberRole.TokenMaster:
    let existingCommunity = self.view.model().getItemById(communityDetails.id)
    if existingCommunity.id.len == 0 or existingCommunity.communityTokens.isNil or existingCommunity.communityTokens.getCount == 0:
      self.controller.getCommunityTokensDetailsAsync(communityDetails.id)

      # Get community members' revealed accounts
      # We will update the model later when we finish loading the accounts
      self.controller.asyncGetRevealedAccountsForAllMembers(communityDetails.id)
    else:
      communityTokensItems = existingCommunity.communityTokens.items

```
Here I reuse old token items until new tokens are loaded asynchronously.

The blink is gone. It turns out that when `SIGNAL_COMMUNITY_TOKEN_DEPLOY_STATUS` is successful, we create a new community item to replace the old one, initially with an empty token list, which is loaded in the background using `getCommunityTokensDetailsAsync`. 

Tomorrow I'll try another approach maybe it's better to rebuild the section after `getCommunityTokensDetailsAsync` has returned the new tokens.
