### ISSUE TITLE
Cover status help docs in test rail (enhance the check list)

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#15308]
https://status.app/help

we can review this docs and build some happy pathes to verify per each RC based on this documentation

**Comment by virginiabalducci** [comment]
Test cases : https://ethstatus.testrail.net/index.php?/suites/view/5513&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=62983

Test run: https://ethstatus.testrail.net/index.php?/runs/view/16921&group_by=cases:section_id&group_order=asc

**Comment by virginiabalducci** [comment]
The following help pages contain steps that do not match actual app and also describe some functionality that is not available (such as voice messages)

- https://status.app/help/wallet/delete-your-status-wallet-or-wallet-account
Cannot remove user profile
UI does not show "manage profiles" 


- https://status.app/help/profile/sync-your-profile-across-devices
You can pair up to three devices. -> I think currently you can pair up more than 3 devices
Cannot unpair devices

- https://status.app/help/profile/sync-your-profile-across-devices
Step 1.2 copy mismatch . Sync a new device (actual text on app “Setup Syncing”

- https://status.app/help/messaging/edit-and-delete-your-messages
“Delete for me” and “Delete for everyone” options in group chat are not available.

- https://status.app/help/messaging/delete-a-group-chat 
there is no "Leave and delete" option

- https://status.app/help/profile/mute-your-notifications 
step 3 is unclear, there is not a general “Notifications” option.

- https://status.app/help/messaging/format-your-messages
Code block is not working as expected but there is a known issue reported https://github.com/status-im/status-desktop/issues/14821

**Comment by anastasiyaig** [comment]
@virginiabalducci addressed your findings in https://github.com/status-im/status-website/issues/1112

**Comment by lukaszso** [comment]
I've split mute functionality into a separate subsection because it was a bit confusing https://ethstatus.testrail.net/index.php?/suites/view/5513&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=63007
Also updated the 'Download Status' cases so they include installation, downloading wasn't enough imo. https://ethstatus.testrail.net/index.php?/suites/view/5513&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=62984

Closing as there nothing more to do with this at this point. It is acceptable for now.
