### ISSUE TITLE
Members get kick AC notifications after the ownership change

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#15341]
# Bug Report

## Description

When ownership changes, all members get a kick notification

## Steps to reproduce

1. Create a community and mint owner token
2. Have at least 2 members A and B
3. Transfer ownership token to member A

#### Expected behavior

Members did not get kick AC notification on ownership change

#### Actual behavior

Member B got AC notification, that he was kicked

![image](https://github.com/status-im/status-desktop/assets/117639195/08af61ca-96cc-425e-a1dc-4c6d46b657ab)

### Additional Information

- Status desktop version: latest master
- Operating System: macos

**Comment by 86doteth** [comment]
btw there werent any ownership changes in these two instances. a week ago i tried transferring control node between two devices, both the same account. that combined with the displayname bug i still had probably led to the mass kick. after i got the pr fix for that and put my pre-kick data folder back all members were back again. but in the week since it seems a few members like @jrainville and maybe you as well got removed/kicked a few times. some of these kicks might be triggered by me restarting status, i noticed a user monora basically got removed every time (5-6 times now?) after i logged in. and then every time i received a join request by them maybe an hour later or so.

**Comment by 86doteth** [comment]
nice! i did restore my current profile from seed but like months back i think v2.27. not sure the problem existed before a week ago and why only the same few members seem to get kicked over and over again 🤔
