### ISSUE TITLE
Swap - Cannot get a quote for the pair USDT - SNT and error message displays

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#15542]
# Bug Report

## Description

USDT to SNT pair quote displays an error message

## Steps to reproduce

1. Open Swap
2. Choose USDT as Pay and SNT as Receive

#### Expected behavior
Swap to give a quote for the transaction as in Paraswap.
![Screenshot 2024-07-11 at 8 49 37 AM](https://github.com/status-im/status-desktop/assets/68916150/897990bd-fcc4-4350-8669-fc885c96ee1b)

#### Actual behavior
A generic error displays. 
From 10 times that I try this, maybe 1 time it works. The rest of the times the error message shows.
![Screenshot 2024-07-11 at 8 49 56 AM](https://github.com/status-im/status-desktop/assets/68916150/4ab28a10-4baf-4c5f-93ea-7fa6770a6b9b)

https://github.com/status-im/status-desktop/assets/68916150/e951f3ff-c920-418f-9602-7fb0f604ba2c

### Additional Information

- Status desktop version: Latest master https://github.com/status-im/status-desktop/commit/78e605d92
- Operating System: Mac OS Sonoma

**Comment by dlipicar** [comment]
@virginiabalducci the error Paraswap gives us for that case is `ESTIMATED_LOSS_GREATER_THAN_MAX_IMPACT`.
This normally happens when you try to swap large amounts, it indicates that the swap requested will make the price of the token change more than a certain % (15% by default), and normally happens with low-liquidity tokens.
It doesn't make sense for such a small trade though. It's not triggered by Paraswap for 1USDT, but for smaller values weird things happen as well:
<img width="1327" alt="image" src="https://github.com/user-attachments/assets/302c9c13-79c7-429f-905e-5c2e12c59220">

Anyway, I'll contact Paraswap support and see what they tell us, but it seems to be a problem on their side, not on ours.
