### ISSUE TITLE
Wallet: POTENTIAL FUNDS LOSS: Saved addresses ignores check sums and recalculate them treating input as not check-summed

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#15772]
# Bug Report

## Description

`Add new saved addresses` accepts both plain and check-summed addresses. However when check-summed one is provided, the check sum in not checked, the address is treated as it was all lower-case. But when saved, the new check-sum is computed on top, which is valid for the original potentially malformed address.

Because of that user looses protection of check-sum when using functionality of saved addresses. It accepts broken addresses and hides the problem by providing new check sum.

[Screencast from 24.07.2024 15:36:46.webm](https://github.com/user-attachments/assets/8cea3c02-6c39-4393-bad1-4bb1d56c2831)

## Steps to reproduce
1. Go to wallet, saved addresses,
2. Click "Add new address" to open popup
3. Enter invalid check-summed addres e.g. `0x10e3b1503675aFC56F567ca7d8e6540BE1e729dC`
4. Save, copy the save address and compare to the input:

`0x10e3b1503675aFC56F567ca7d8e6540BE1e729dC`
`0x10E3b1503675aFc56F567cA7D8E6540be1e729DC`

casing differs because the check sum has been recalculated

#### Expected behavior

The check sum should be validated when taking user input in case of check-summed addresses.

#### Actual behavior

The check sum is ignored and overridden.

**Comment by micieslak** [comment]
The funds-loss transaction from the attached video: https://etherscan.io/tx/0x3924a0c197b9792abb7c867bc193f6a6a35288a72229eb019d6ff61fe4f130f8

**Comment by saledjenic** [comment]
The title of this issue is misleading, cause it doesn't lead to loss of funds, cause any address is a valid address.

Also if user's intention is to send tx to address `0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` then any of the following formats:
```
0xAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
0xAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
0xAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
0xAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
.
.
.
0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
will do the transfer to the correct address, but if instead of it user places `0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaB` or anything else, that's cause he wanted so, that's not about funds loss.

----

And that's literally the example above instead of the original address which was 
`0x10e3b1503675aFC56F567ca7d8e6540BE1e729dB`
user entered 
`0x10e3b1503675aFC56F567ca7d8e6540BE1e729dC` <- which is a completely different address (last letter `C` instead of `b` or `B`)
but if he used 
`0x10e3b1503675aFC56F567ca7d8e6540BE1e729db` that would not result in funds loss
