### ISSUE TITLE
[Wallet] Balaces for DAI and SNT disappeard

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#15823]
# Bug Report

## Description

I played a bit with Send dialog. At some point I noticed that balances for SNT and DAI disappeard. I only saw balances for ETH and ARB. I should have 14 SNTs. Balances for ETH and ARB were ok.

![image](https://github.com/user-attachments/assets/f60bb56e-71a7-4119-b095-9df3b2445b51)

In the wallet the same:

![image](https://github.com/user-attachments/assets/1b407305-68ea-400c-b401-509a37d880f7)

I am attaching some errors from logs:

![image](https://github.com/user-attachments/assets/c5076c6c-63df-400b-b417-5dbe4deeeeae)

I tried to restart wallet by setting testnet and mainnet again. Then I saw "Pokt and Infura down for Arbitrum". I pressed "retry now" a few times and balances showed up. But the red banner was still there.

## Steps to reproduce

Hard to say. I opened Send dialog a few times, pasted address, chose tokens to send. I did it a few times.
Probably some downloading balances problem?

### Additional Information

- Status desktop version: master - 7d0e77d86ff4230f653721087a25e1722efee591
- Operating System: mac

**Comment by saledjenic** [comment]
@Cuteivist when you start on this, please check the following scenario:
- select other than the default wallet account, to send from,
- enter all necessary input params to generate a route, 
- keep the Send modal popup open and wait for some time (we need some update to happen)

You will see that the user's entered input data gets refreshed after an update is received.
Most likely that's an issue reported here.

Please share your observation on it here, what event triggers the refresh, and if there is an easy fix for it, otherwise we can leave it for the next milestone and let the UI team (@noeliaSD @micieslak) finish the UI refactor first.

**Comment by saledjenic** [comment]
Cool, thanks for the update, let's check it once it's merged.
