### ISSUE TITLE
[Browser plugin connector] List browser plugin dApps in the dApps dialog

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#15885]
Extend [existing dApps dialog](https://github.com/status-im/status-desktop/issues/14759) with browser plugin dApps. The following functionality should be implemented:
- List dApps, connected to the browser plugin in the wallet dApps dialog
- Implement disconnecting for browser plugin dApp via button

![image](https://github.com/user-attachments/assets/afdcb07f-404e-4f98-8a20-dde1f3adde91)

Note: `Connect a dApp` works for wallet connect only, browser plugin dApps should be connected using `eth_requestAccounts` only.

**Comment by kounkou** [comment]
Hi there, thank you for opening the ticket, working on it today. I am currently gathering some information from the conversation on discord and from the designs in Figma.

**Comment by kounkou** [comment]
Hi team,

**Estimate**

| Task | Task points | State |
| --- | --- | --- |
| `Add an external link to extension in Status desktop`  | 1 | Add a section in Wallet in advanced or something, need design input | `not started` |
| `See connected dApps`  | 5 | Requires saving list of connected dApps similar to WC and feed the model | `not started` |
| `Disconnect dApps`  | 3 | Requires remove specific dApps without impact on other dApps and update model | `not started` |
| `Icon for dApps connected through connector`  | 2 | Need to reachout Design ? | `not started` |
| `The user receives notification in Notification center about pending requests`  | 2 | Handle pending requests in a queue or similar ? | `not started` |
| `Handle offline mode to close WS`  | 3 | Since we are working on localhost, the offline doesn't impact the WS, but this suggests otherwise, so code update is needed | `not started` |
| `Implement wallet_disconnect`  | 3 | Add endpoint in the commands | `not started` |
| `Implement wallet_revokePermissions`  | 5 | Add endpoint in the commands. This seems to imply we need to save permissions in database or similar to be able to revoke permissions | `not started` |

---------------------------------

**Details**

I went back through the [user stories](https://www.notion.so/Status-Connector-user-stories-draft-668f5aac5e7d4be182a834dafa5150cc#75e98149407a4060b731671cef6062ac) to extract an exhaustive list of items missing for completing the Status connector implementation.

**US 1**
- [ ] Add an external link to extension in Status desktop

**US 2, 3, 4** 
Covered

**US 5**
- [ ] The user can see dApps connected via Status Connector in dropdown Wallet/Dapps
- [ ] The user can disconnect dApp from Status Desktop by clicking disconnect button
- [ ] The user can see an icon on dApp in connected dApps indicating that dApp was connected via Status Connector

**US 6**
- [ ] The user receives notification in Notification center about pending requests

**US 7**
- Covered

On top of the above User Stories I crossed the infos with above notes from @felicio to add on missing items : 

- [ ] If desktop ~~quits or~~ goes offline WS should be closed
- [ ] Implement wallet_disconnect
- [ ] Implement wallet_revokePermissions
