### ISSUE TITLE
Remove Functionality for Adding New Watch-Only Accounts

### ISSUE THREAD

**Issue by belalshehab** [status-im/status-desktop#15933]
### Description
This change removes the option for users to add new watch-only accounts to the Status app. Existing watch-only accounts will not be affected – users will still be able to update or remove them as needed.

### Acceptance Criteria

 - No New Watch-Only Accounts: Users should not be able to add new watch-only accounts.
 - Existing Functionality: Existing watch-only accounts should still work (view balances, update details, remove).

**Comment by caybro** [comment]
I wonder... where was this decided?

**Comment by belalshehab** [comment]
> I wonder... where was this decided? What's the rationale behind this, esp. since the existing ones should continue working

@saledjenic @alaibe should have the answer

**Comment by alaibe** [comment]
@caybro there is a risk that if you add watch only account with a lot of transactions, it can potentially consume a lot of rpc calls and at the end freeze the app
see: https://github.com/status-im/status-desktop/issues/15880

For the 2.30 only we will disable the creation, then for 2.31, we will fix that problem hopefully and quite probably do not fetch activity for watch only accounts

**Comment by saledjenic** [comment]
@J-Son89 @ilmotta reason for hiding is explained in the previous comment.

Since we want to have this option hidden for 2.30, there are options:
1. the desktop app hides it and we disable syncing watch-only accounts on the statusgo side
2. the desktop app hides it and the mobile app hides it and we don't need to disable syncing on the statusgo side

I am more in favor of the second option because, at this point adding any heavy account (with many many history txs) as a watch-only account in the mobile app, will drain the battery very fast.

**Comment by J-Son89** [comment]
please raise this issue in chat where the relevent people are more likely to see it and it gets a proper discussion. No strong opinion from my side what to do here, generally in favour of us taking the smoother path for this release. 👍
