### ISSUE TITLE
[BrowserConnect] BrowserConnect tries to handle WalletConnect events

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#15936]
Basically, the following [`onUserAuthenticated`](https://github.com/status-im/status-desktop/blob/0c4b7e92a0b4b9fcceae0244cffc4b47dbaa5527/ui/app/AppLayouts/Wallet/services/dapps/DappsConnectorSDK.qml#L293) will trigger and fail for WalletConnect events.

The `DappsConnectorSDK` is registering for authentication events for the same instance of `DAppsStore` which means all the signals triggered by WalletConnect controller are processed by the `DappsConnectorSDK`.

This causes false errors to be generated. Raising this given that I spent a considerable amount understanding why do I have the `>Error finding event for topic` errors for a valid event. Only after logging out the instance I realized that the error is due to lookup into another instance which is the one from `DappsConnectorSDK`

One quick wind would be to alter the text for all the log entries related to Connector parallel implementation and to use the identity of a Connector request to categorize it as foreign and dismiss without an error.

**Comment by kounkou** [comment]
**Discussed and agreed with** @stefandunca

### What's the problem

> The DappsConnectorSDK is registering for authentication events for the same instance of DAppsStore which means all the signals triggered by WalletConnect controller are processed by the DappsConnectorSDK.

### Context

For context, Connector Service requests have a `RequestID` which are used to identify each request coming to Desktop Frontend where we currently reuse building blocks of Wallet Connect for displaying Popup for request account or signing transactions. However, because we reused building blocks of Wallet Connect, during implementation, I did also use the `topic` since the code was inherited and didn't want to diverge later after some possible refactoring.

Knowing more about and after discussion with @stefandunca, on how the code works, this later assumption is not a problem for future refactorings, since the refactoring will abstract all the building blocks.

### Proposal (only one since it's ideal!)

So proposed approach is to use either `topic` or `requestID` to be able to identify a request. Since Connector introduced its own `requestID` for requests, that's what we will go for, thus setting `topic` as empty.

Thanks!

**Comment by alexjba** [comment]
Closed by https://github.com/status-im/status-desktop/pull/16730
