### ISSUE TITLE
[WalletConnect] Can't sign transactions for local accounts when the user authentication is through keycard

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#15957]
# Bug Report

## Description

The user authentication fails when signing transactions for local accounts using keycard authentication.

This task https://github.com/status-im/status-desktop/issues/15647 excludes the wallet accounts stored on keycard from the Wallet Connect feature. Until we'll support keycard authentication for wallet connect maybe we should exclude all Status accounts as well.

## Steps to reproduce

1. Login using keycard
2. Import/generate a wallet account using any option except Keycard
3. Connect to a dapp
4. Request a sign transaction

#### Expected behavior
5. User can sign the transaction
#### Actual behavior
5. The sign transaction fail when the user tries to authenticate using keycard
### Additional Information

https://github.com/user-attachments/assets/ff736dcb-dd7f-47dc-a98d-8ce40a8ddf4f

- Status desktop version: 2.30rc4
- Operating System: MacOs

**Comment by alexjba** [comment]
CC @saledjenic @stefandunca @Seitseman

**Comment by alexjba** [comment]
Added 2.30.0 Beta milestone for now. To be re-evaluated..

**Comment by saledjenic** [comment]
Without knowing the code, just looking at the video, I can say that most likely an authentication was not initiated with appropriate parameters.

From this point, click on the "Sign" button (which is correctly displayed with a keycard icon)
<img width="801" alt="image" src="https://github.com/user-attachments/assets/95a69257-920b-42a7-801f-c318a5209654">
you should run first an authentication flow with an empty keyUid or keyUid of the profile keypair (cause the keypair of the address that you're using for signing is not migrated to a keycard), but it looks like you're using keyUid of the keypair of the keypair that address belongs to. Then once you get the pin from that authentication flow you should sign the message you want to sign on the statusgo side. In case the address you want to use for signing belongs to a keypair that was migrated to a keycard then you would need to run the signing process on a keycard (running runSignFlow) instead of on the statusgo side.
