### ISSUE TITLE
channel: RSS Subscribe

### ISSUE THREAD

**Issue by atlantis451** [status-im/status-desktop#16198]
### Description
[comment]: # channel

*Summary*: ...

The Room administrator can add "RSS Subscribe" to the channel. For example `https://status.app/blog/rss` `https://status.app/news
/rss`

Various latest news and blog posts

There will only be a brief description in the "Status channel". If the user wants to view the full content, clicking the link will open the win10 default browser

**Comment by jrainville** [comment]
Hi @atlantis451 , thanks for the feature request.

Since we cannot guarantee that we'll have time to work on all the great ideas people have, we have opened a forum here using featureupvote: https://status.app/feature-upvote

If you could add you suggestion there, people could vote on it and we'll be able to see which feature the community wants to most.

Closing this in the meantime.
