### ISSUE TITLE
Switching between chats on macOS is slow 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#1642]
~~when you just run the app, the delay is minimum, like 1s, but if you scroll and get more messages from history or receive from mailserver, it's geting growing and might increase up to 5s~~

when you click on any chat, app is freezing for a few seconds, its pretty general action, and when you surf between chats the app feels slow and laggy

**Comment by flexsurfer** [comment]
still relevant in the latest master

**Comment by flexsurfer** [comment]
still relevant in the latest master and beta6, but now there is a white screen also for some chats instead of messages

**Comment by iurimatias** [comment]
@flexsurfer what OS is this? do you have screenshots?

**Comment by flexsurfer** [comment]
@iurimatias its macos catalina, but im not sure its os related, its kinda hard to reproduce i don't have screenshots yet , but it was just white screen instead of messages

**Comment by flexsurfer** [comment]
still an issue on latest master

**Comment by michaelsbradleyjr** [comment]
It's not a wonderful solution, but a known workaround is to delete the app's data folder (`~/Library/Application Support/Status` on macOS) then start over by re-importing your seed phrase.

The older/larger the data folder is (particularly the sqlcipher database created by status-go), the slower the app performs. With a fresh data folder and a build of latest `master` you'll notice a *dramatic* difference.

We're researching what the problem is with older/larger data folders, but it's not clear yet.

**Comment by flexsurfer** [comment]
mhm, i feel like its slow only then i have lots of rendered messages i see it by scroller bar size, so i guess you can use same approach we use on mobile, unmount messages and loadMore and mount on scroll

**Comment by michaelsbradleyjr** [comment]
It is true that when you have an old/large data folder the slowness is experienced when switching to a channel with lots of messages, but it's pretty quick to switch to a channel that has few/no messages.

However, with a fresh data folder, even switching to a channel with lots of messages (e.g. `#status`) is very snappy.

As for unmounting/mounting, it is likely we can make such improvements.

**Comment by iurimatias** [comment]
`As for unmounting/mounting, it is likely we can make such improvements.` afak Qt/QML already does that automatically but should investigate further.

**Comment by iurimatias** [comment]
We found the likely cause for this is getting the contact list from `wakuext_contacts` which is done [here](https://github.com/status-im/status-desktop/blob/master/src/status/libstatus/contacts.nim#L26). It seems each time we switch channels (and other actions like switching communities etc..) this is called. This is not just the list of contacts but all the list of 'seen' contacts, it's usually pretty light or small enough to not be noticeable even with lots of channels and history fetching. however if someone uses the app for a bit as this gets bigger and bigger it starts to impact the performance noticeably.

As a fix we need to improve the cache, be smarter on what we return and how etc.. (under discussion)

**Comment by richard-ramos** [comment]
In addition to wakuext_contacts, `wakuext_markAllRead` is also called when switching channels, and is causing part of the slowdown due to the UPDATE statement being used.  Some possible improvements are to either call `wakuext_markMessagesSeen`  with the specific message Ids, or call `wakuext_markAllRead` async.  In addition to this, add an index over the `local_chat_id` column of `user_messages` table, but with regards to this @jrainville suggest to discuss with Mobile team due to concerns related to storage size

**Comment by flexsurfer** [comment]
we have issues with contacts on mobile as well https://github.com/status-im/status-go/issues/2215

**Comment by flexsurfer** [comment]
cc @cammellos

**Comment by flexsurfer** [comment]
btw this one https://github.com/status-im/status-desktop/issues/2130 is still relevant when you use app for a few months , probably related to this one

**Comment by iurimatias** [comment]
The group messages is likely related to the way group messages work, this issue of switching chats seems related to the contacts and mark messages as read
