### ISSUE TITLE
ENS - releasing an ens name flow triggers irrelevant notifications

### ISSUE THREAD

**Issue by virginiabalducci** [status-im/status-desktop#16505]
# Bug Report

## Description

This is related to the PR https://github.com/status-im/status-desktop/pull/16464 
When releasing an ens name in the send modal, irrelevant notifications are triggered

## Steps to reproduce

1. Log in with an account that has an ENS name
2. Go to Settings -> ENS usernames
3. select an ens username
4. Click on "release username"

Note: the select account issue is not fixed yet

#### Expected behavior
Notifications that are not relevant should not trigger

#### Actual behavior
When the release username flow starts and the Send modal is shown, irrelevant notifications show up

https://github.com/user-attachments/assets/bd06d225-4b7a-488e-a548-2e08b954a56c

### Additional Information

- Status desktop version: build from the PR mentioned on this issue
- Operating System: Mac OS Sonoma

**Comment by virginiabalducci** [comment]
cc @saledjenic

**Comment by saledjenic** [comment]
@virginiabalducci if you're referring to contact request notifications, they are completely unrelated to actions you're doing in the send modal popup while trying to release the ens name. Getting ephemeral notifications at the same time is a coincidence.

Issue that I see here are:
- running the send modal the "Release username" button should have as the selected account an account that the ens name was bought with and we should not allow changing account in that case
- running the send modal the "Release username" button should have as the selected token, ETH token and we should not allow changing token in that case

If we already have an issue for fixing that, you can close this one, otherwise, you can modify the title of this issue and use it for fixing the forementioned issues.

**Comment by saledjenic** [comment]
Ok, I see we have this issue https://github.com/status-im/status-desktop/issues/16506, which is about what I mentioned in the previous comment, so feel free to close this one.

**Comment by saledjenic** [comment]
I think points from this issue are already addressed here https://github.com/status-im/status-desktop/pull/16644, guess we can close this issue? @virginiabalducci

**Comment by virginiabalducci** [comment]
Closing issue as it has been addressed in #16644
