### ISSUE TITLE
start new chat dialog, list of contacts should filter depending on the search string

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#1705]

**Comment by staked-smart-ace** [comment]
Could I work on this issue?

**Comment by jrainville** [comment]
Do we require a design for that or @iurimatias you just want to explain to @staked-smart-ace what is expected here?

**Comment by staked-smart-ace** [comment]
This issue is clear currently, I could just start for now :)

**Comment by staked-smart-ace** [comment]
It seems that this is functionality issue

**Comment by jrainville** [comment]
Yes. There is just the small added detail I think that if the person is not a contact, it should kind of add it to the list? Or should we keep it as is for now @iurimatias ?

**Comment by iurimatias** [comment]
@staked-smart-ace this is 2 issues (that can be done in 2 separate PRs)

1 - searching should filter the contact list
2 - inputing an ENS name should show these in the contact list as well (and filtered)

**Comment by staked-smart-ace** [comment]
> @staked-smart-ace this is 2 issues (that can be done in 2 separate PRs)
> 
> 1 - searching should filter the contact list
> 2 - inputing an ENS name should show these in the contact list as well (and filtered)

@iurimatias I want to make sure more details at this moment.
Do you know that show correct ENS name searched below the search box?
In the following image, ```bridge``` is a none-contact person.
![image](https://user-images.githubusercontent.com/29419562/105249108-01972400-5b91-11eb-80f4-53e9b70036df.png)
- In this case, when clicking Start Chat button, will create new chat with that ENS name
- Otherwise, will create chat when clicking contact item in the list without depends on the searched person

So, I am not sure that should add searched none-contact person into below contact list.

**Comment by jrainville** [comment]
@iurimatias we might want to create the second feature request as part of a new issue since @staked-smart-ace already fixed the first part in his PR #1719

**Comment by iurimatias** [comment]
@jrainville fair, will do

**Comment by staked-smart-ace** [comment]
@iurimatias @jrainville Do you want the second feature to add uncontacted person to list when create new chat?
If you really want, let me do that also.

**Comment by iurimatias** [comment]
created #1721, however we should wait for designs before doing it

**Comment by iurimatias** [comment]
@staked-smart-ace not yet, we should wait for the design.

**Comment by staked-smart-ace** [comment]
> @staked-smart-ace not yet, we should wait for the design.

ok
