### ISSUE TITLE
Changing System Appearance on the fly is not working

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1725]
<img width="677" alt="Screen Shot 2021-01-21 at 18 11 16" src="https://user-images.githubusercontent.com/52249767/105385906-22ed2400-5c14-11eb-96ac-6e0d107edf32.png">

**Comment by iurimatias** [comment]
@simonricoo this works for me.. my system is dark mode, clicking on system switches the whole thing to Dark mode, could you confirm is your system using dark mode, and is this a recent version of desktop?

**Comment by simonricoo** [comment]
Not working for me :/

**Comment by iurimatias** [comment]
what build is this? just confirmed it works for @michaelsbradleyjr as well

**Comment by simonricoo** [comment]
Its working on the latest master.

**Comment by simonricoo** [comment]
Actually its not working when I enable/disble dark mode from the menu bar
<img width="450" alt="Screen Shot 2021-01-21 at 19 42 24" src="https://user-

https://user-images.githubusercontent.com/52249767/105397726-b6792180-5c21-11eb-9f71-71b2a2776e99.mov

**Comment by PascalPrecht** [comment]
That's actually something I've looked into in https://github.com/status-im/status-desktop/pull/1823

> The application also doesn't get notified when a user switches the theme
inside the operating system, requiring her to switch to the same theme
manually unless restarted.

Unfortunately, there's no signal inside of QML for us to react to the user changing the theme via OS settings at runtime.

**Comment by iurimatias** [comment]
probably needs changes on Dotherside

**Comment by saledjenic** [comment]
@iurimatias @anastasiyaig this is fixed and works respecting OS's mode setting now.
So when you start the app if in profile settings->appearance is set to:
- "Light" app will be with light theme
- "Dark" - app will be with dark theme
- "System" - app will be with dark theme if OS is in the dark mode, otherwise will be with light theme

While the app is running if you're changing OS mode (dark/light) app will be responsive to that change only if "System" is set for appearance.
