### ISSUE TITLE
Assigning nickname to the user dismisses his profile pic

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1761]
Fix: Dont overwrite profile pic when I assign a nickname to the user.

<img width="1221" alt="Screen_Shot_2021-01-26_at_13_39_04" src="https://user-images.githubusercontent.com/52249767/105846475-87293280-5fdc-11eb-9c62-71f460855202.png">
<img width="398" alt="Screen Shot 2021-01-26 at 13 44 10" src="https://user-images.githubusercontent.com/52249767/105846523-94deb800-5fdc-11eb-9e59-e8893129ce99.png">
<img width="1223" alt="Screen_Shot_2021-01-26_at_13_44_31" src="https://user-images.githubusercontent.com/52249767/105846565-a45e0100-5fdc-11eb-89de-d9d82ab623d3.png">

**Comment by staked-smart-ace** [comment]
Could I fix this issue?

**Comment by staked-smart-ace** [comment]
@iurimatias @jrainville @PascalPrecht 
I have some questions for this issue.
Currently, profile picture is showed by `thumbnail` and `identicon`
This is code snippet of the `ContactList.qml`
```
identicon: model.thumbnailImage || model.identicon
```
There is a problem when save nickname of the any contact.
`Update Nickname` is calling `saveContact` RPC api, but after called this RPC api, the `thumbnail` is removed for the updated contact.
It is easy to check this issue via calling `getContactByID` and its returned json string

**Comment by jrainville** [comment]
It seems like `saveContact` erases the field you don't save. 
You can see here that `Contact` has an Image field https://github.com/status-im/status-go/blob/develop/protocol/contact.go#L62
So when you call `saveContact`, you need to pass `contact.image` or something like that

**Comment by staked-smart-ace** [comment]
Could you provide detailed format to submit for the `images`? it would be very helpful for me.

**Comment by jrainville** [comment]
`contact`, from the `get ContactById` already has a `identityImage` field. You probably just need to pass it back to the RPC method

**Comment by staked-smart-ace** [comment]
@jrainville 
Using types is different between `getContactById` and `saveContact`.
`get method` is just returning `uri` attribute for the image data with based64 encoded.
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAkUlEQVR4nOzY0QmEMBAG4TuxF+sTLEOwPqvRBhQicWH8me9RRBwWlpDhF8IQGkNoDKExhCYmZGx9cd234+r5Ms3/N36k9/sxEzGExhAViZmIITSG0HSftap51voqQ2hiQpq31lN326Zq+8VMxBAaQ2iat1b1Fuq9H4uZiCE0hqhIzEQMoTGExhAaQ2jOAAAA///QoxV2SRdk5QAAAABJRU5ErkJggg==
```
But I need to send image data with  `Payload` type. I am not sure how to send it with `Payload`.
Could you help me?

**Comment by jrainville** [comment]
I'm not exactly sure either to be honest.

We can ask @cammellos or @Samyoul since they know status-go better. What is the way to send back a user's image when doing `saveContact` (for adding a nickname for example)? Or maybe even better, is there a way to save the nickname without having to send back all the stuff from the contact?

**Comment by staked-smart-ace** [comment]
Sure, if we update only `nickname` attribute of the contact, it would be ideal and best way.
`ex: updateContactNickname`

**Comment by cammellos** [comment]
mmh, so, we don't have anymore a field on `Contact` for images, so you are definitely not overwriting I think as it's kept in a separate table and is not written through the API.

So, if you call `SaveContact` with the updated info, it will definitely not override the field in the database.

I think what's happening is that we do save it the contact you send us in memory, and we don't add pull back the identity images from the db, so it looks like it's overwritten, but I suppose login/logout should show the picture again.

So that's something we need to fix on our side.

We didn't notice on status-react as we optimistically update the structure on the frontend, i.e we don't pull it back using `getContactByID`, once we make a change and we see it's committed, we don't retrieve it back.
But that's easy to fix, thanks for spotting the issue.

**Comment by jrainville** [comment]
Hey @cammellos any update on a fix on `saveContact`? Do you have a status-go issue we can follow?

**Comment by cammellos** [comment]
oh sorry @jrainville , totally forgot, could you pleas create one and assign it to me?
Thanks!

**Comment by jrainville** [comment]
Alright, no problem
