### ISSUE TITLE
Update appearance of code text in the input field

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1933]
Code text should have different appearance:
**Current:**
<img width="378" alt="Screen Shot 2021-02-26 at 10 41 21" src="https://user-images.githubusercontent.com/52249767/109283591-4280f900-781f-11eb-9fe2-127db8ea4436.png">

**Design**

<img width="648" alt="Screen Shot 2021-02-26 at 10 42 32" src="https://user-images.githubusercontent.com/52249767/109283647-562c5f80-781f-11eb-8f46-6e6044de4c50.png">
+ I'm not sure if you used Roboto Mono Font for code block formatted text

<img width="257" alt="Screen Shot 2021-02-26 at 10 42 47" src="https://user-images.githubusercontent.com/52249767/109283773-72c89780-781f-11eb-972b-72b1cdd6062f.png">

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4360%3A245

**Comment by iurimatias** [comment]
in dark mode the code tool doesn't seem to do anything, we need to fix

**Comment by PascalPrecht** [comment]
It seems that we're unfortunately quite limited as to what HTML we can inject into the textarea. At the moment, code blocks are `<code>` tags. It seems however, that the textarea strips out a lot of things that are otherwise possible in HTML+CSS. For example, when trying to apply inline styles on those code blocks, they just get stripped out, except for the background color.

I don't know (yet) what the rules are that QML's TextArea follows here, but with what we have in place at the moment, it seems impossible to apply the styles that are desired here..

**Comment by PascalPrecht** [comment]
Okay so there is an [HTML 4 Subset](https://doc.qt.io/qt-5/richtext-html-subset.html) that's supported by Qt's RichText engine. It doesn't allow for `border-radius` and `display` properties though, which are needed to create those visuals we'd like.

I've also noticed that e.g. `padding` styles, even though they are supported according to the docs, don't apply and get removed entirely once injected into the textarea

**Comment by jrainville** [comment]
Yeah I found those same problems when trying to do the mentions in the messages. What we did is just default to a normal background with no padding nor rounded-corners. It's less pretty, but it works

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/dotherside/issues/39
