### ISSUE TITLE
When there is no space for Tooltip it appears on the wrong position

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#1945]
https://user-images.githubusercontent.com/52249767/109641088-98bca780-7b51-11eb-9eb9-94e278f588b3.mov

https://user-images.githubusercontent.com/52249767/109641724-55166d80-7b52-11eb-93c1-1bff211019d1.mov

https://user-images.githubusercontent.com/52249767/109641592-2c8e7380-7b52-11eb-8135-e34995e35b4a.mov

### Fix: If there is no space for tooltip above, show it bellow.

<img width="211" alt="Screenshot 2021-03-02 at 12 22 57" src="https://user-images.githubusercontent.com/52249767/109641664-40d27080-7b52-11eb-96a2-c83e0e1c07da.png">

**Comment by jrainville** [comment]
This is super hard to fix, because I didn't find a way to know when the tooltip changes position. 
I could fix the Version one relatively easily here https://github.com/status-im/status-desktop/pull/2128, but fixing those in the chat is way harder.
I'll leave this issue opened, but gonna move it to get fixed later

**Comment by jrainville** [comment]
@alexandraB99 the problem still happens for me:

https://user-images.githubusercontent.com/11926403/125479527-3df917f6-a1f2-4f8c-a561-08942daa2a87.mp4
