### ISSUE TITLE
Crash when trying to add custom token

### ISSUE THREAD

**Issue by piskel** [status-im/status-desktop#2036]
I am attempting to add a custom ERC-721 token, but filling the "Contract address" field causes the program to raise this error:
![image](https://user-images.githubusercontent.com/10447278/111034686-19638980-8417-11eb-84ed-1d87151f5cf5.png)

Clicking on "Ok" in the error pop-up causes the app to close.

But the error pop-up doesn't lock the focus, so we can still fill the fields and try adding the token manually.
This means we technically still can use the app if we don't mind the error pop-ups in the background, but eh...

Also, now the token is visible in the assets list, but launching Status causes an error, which again can be ignored.

I am running Windows 10 Pro 20H2, and I am connected to a development blockchain running on Ganache 2.5.4.
Status version is beta.6.1

**Comment by piskel** [comment]
I tried to see if the issue persisted on version beta.7.rc, going through the same process, adding the token, ignoring the error messages and all that.
Also, selecting the newly added token causes Status to crash.
The problem is that now we can't even log into the app. After entering the password I get this error.
![image](https://user-images.githubusercontent.com/10447278/111037346-eb387680-8423-11eb-8077-4da44b93069d.png)
And that's pretty much all we get to see from Status beyond the login page.

I reckon it is pretty serious since we can't do much about it, if not deleting the Status folder in %localappdata%.

**Comment by emizzle** [comment]
Thanks for submitting this issue, @piskel! 

Can you confirm that you were adding an ERC-721 token? The reason I ask is because I did notice that adding a non-ERC-20/721 token contract address would cause an exception in the app and restarting the app would a crash on login, as you've described. In the current master branch, these exceptions are now handled off the main thread (part of a threadpool now), so the error should no longer be propagated to the front end.

In addition, I've added some error-checking for the VM exceptions, so now you should see a nice error message when attempting to add a non-ERC-20/721 contract. This will prevent users from being allowed to add these token contracts, and thus further prevent the crash on login issue you've encountered.

These updates are present in the following PR and will be in the next release: https://github.com/status-im/status-desktop/pull/2116. The error message you will when attempting to add the SimpleStorage contract (ie any non ERC-20/721 contract) as a custom token:
![Imgur](https://imgur.com/y7sIoUY.png)

**Comment by piskel** [comment]
Ah ! Glad to know it'll get fixed ! Thanks a lot !

Here is the contract I used :

```solidity
pragma solidity ^0.6.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract ToToKeKen is ERC721 {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIds;

    constructor() public ERC721("ToToKeKen", "TK2") {}

    function mint(address to, string memory tokenURI)
        public
        returns (uint256)
    {
        _tokenIds.increment();

        uint256 newToken = _tokenIds.current();
        _mint(to, newToken);
        _setTokenURI(newToken, tokenURI);

        return newToken;
    }

}
```
I believe it's pretty much the default ERC721 token implementation from openzeppelin, not much more to it.

**Comment by emizzle** [comment]
Hey @piskel, would you mind trying out Beta 8 RC1 to see if this issue has been fixed for you? The release can be found here: https://github.com/status-im/status-desktop/releases/tag/beta.8.rc1.

**Comment by piskel** [comment]
I tried again by starting fresh, deleting the status folder in %localappdata%, but now I can't add a new custom network. Clicking the "Add network" button does nothing.
