### ISSUE TITLE
A community's current thumbnail images isn't displayed in the 'Edit community' dialogue

### ISSUE THREAD

**Issue by johnlea-quiup** [status-im/status-desktop#2123]
To reproduce:

1. Create a community with a thumbnail image
2. Click on 'Manage community'
3. Click on 'Edit community'
4. The 'Edit community' dialogue appears

Current incorrect behaviour: In the 'Edit community' dialogue, under the 'Thumbnail image' no image is displayed, only the "Upload" empty state.

Correct desired behaviour: If a community already has a thumbnail image, when the community owner navigates to the 'Edit community' dialogue the community's current thumbnail image should be displayed.

**Comment by jrainville** [comment]
The Edit functionality is very much a WIP. It was created to follow the initial design but isn't working right now as it is from phase 2.
In master, I have deactivated the Edit button for now to reduce the confusion.

I'll close this for now since the Edit modal will need more work once we implement it fully in phase 2
