### ISSUE TITLE
Various issues with communities

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2228]
<img width="622" alt="Screen_Shot_2021-04-13_at_11_15_58" src="https://user-images.githubusercontent.com/52249767/114529024-d7ae4480-9c49-11eb-95e6-0732505a1969.png">

 **How Meeting Detail Modal should look for memeber:**
 
<img width="1125" alt="Screen Shot 2021-04-13 at 11 17 41" src="https://user-images.githubusercontent.com/52249767/114529125-ee549b80-9c49-11eb-937f-b2b11d7e5256.png">
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4795%3A43179

<img width="541" alt="Screen_Shot_2021-04-12_at_11_07_15" src="https://user-images.githubusercontent.com/52249767/114530213-05e05400-9c4b-11eb-9de0-9b3915c5fce1.png">

<img width="544" alt="Screen_Shot_2021-04-12_at_11_07_37" src="https://user-images.githubusercontent.com/52249767/114530283-17296080-9c4b-11eb-8f2b-f687142bbb37.png">

<img width="905" alt="Screen_Shot_2021-04-13_at_11_51_37" src="https://user-images.githubusercontent.com/52249767/114534022-d7647800-9c4e-11eb-837c-ddfb2acba764.png">

<img width="1009" alt="Screen_Shot_2021-04-13_at_11_54_57" src="https://user-images.githubusercontent.com/52249767/114534481-5194fc80-9c4f-11eb-9825-799dba4e1dae.png">

<img width="1146" alt="Screen_Shot_2021-04-13_at_12_00_57" src="https://user-images.githubusercontent.com/52249767/114535242-2363ec80-9c50-11eb-981a-a7c2b392b0a9.png">
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=3641%3A33777
<img width="410" alt="Screen_Shot_2021-04-13_at_12_07_39" src="https://user-images.githubusercontent.com/52249767/114535964-e64c2a00-9c50-11eb-8f29-bdae0df544e5.png">

<img width="926" alt="Screen_Shot_2021-04-13_at_12_10_16" src="https://user-images.githubusercontent.com/52249767/114536422-5a86cd80-9c51-11eb-9ebf-f0ce8b7da5d2.png">

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4251%3A42915

**Comment by guylouis** [comment]
Private channels are not part of phase 1, so I'd remove the toggle 'private' int he channel characteristics

**Comment by PascalPrecht** [comment]
@jrainville did you already start with this? (Seeing you as assignee) I'd otherwise take a stab on some of these

**Comment by jrainville** [comment]
No I haven't. Still working on pinned comments. I'll assign you instead

**Comment by PascalPrecht** [comment]
The "Edit community" buttons and menu items are left out on purpose because the functionality isn't implemented yet (#1428)

Muting communities (channels) needs to be implemented as well, therefore, no context menu items for that yet (https://github.com/status-im/status-desktop/issues/2293)

**Comment by PascalPrecht** [comment]
There are some things in this issue that can only be "hacked" into existing components which I'd like to avoid. 
I've created an additional issue that should account for that: https://github.com/status-im/status-desktop/issues/2295

I'll send PRs for some of these things mentinoed here, but I'd like to keep this issue open until everything is properly resolved.

Might make sense to create separate issues for each of these things left, so that this one can be closed and we avoid confusion about stuff that has already been finished.

**Comment by PascalPrecht** [comment]
Here are some PRs that fixes most of the issues described here:

- #2296
- #2298
- #2299
- #2300
- #2302
- #2305

The one thing that isn't "properly" tackled yet is the UI changes related to https://user-images.githubusercontent.com/52249767/114534022-d7647800-9c4e-11eb-837c-ddfb2acba764.png. We need some refactoring to have those done properly as discussed in #2295

**Comment by anastasiyaig** [comment]
i've tested it anyway however all listed Prs are merged already, so basically this issue might be closed. I will look more into Communities feature, but please stick to plan to have PR + Issue linked, otherwise there is no sense to keep issues on the board (for instance in this particular case all PRs are merged and we keep an issue on the board)

**Comment by PascalPrecht** [comment]
Closing this one as all of the PRs have landed already. The one thing that's missing should be tackled as part of https://github.com/status-im/status-desktop/issues/2295
