### ISSUE TITLE
Implement Light/Dark colors in new Component Library

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2329]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A10

**Comment by PascalPrecht** [comment]
This one deserves some more thought. @borismelnik curious what you think about this.
When it comes to theming there are a bunch of things to consider. 
So far we've defined a bunch of color variables + some application specific variables that would have any of the colors as you can see here: https://github.com/status-im/status-desktop/blob/master/ui/imports/Themes/LightTheme.qml#L4

I think this is a good start, but it has some limitations. One of them being that, when switching themes, colors don't always map to their corresponding equivalent. What I mean by that is the following:

- Say you have a header bar, which in light mode is white (e.g. `primaryBackgroundColor: white`)
- In dark mode, the same header is, let's say, black (`primaryBackgroundColor: black`)
- Now there's another component, let's call it navbar, which in light mode, is also white (so it uses `primaryBackgroundColor`)
- In darkmode howoever, the same component uses a share of dark gray, so using `primaryBackgroundColor` doesn't work anymore

For cases like these, I think we'll have to expose color variables from every single component so that they can get a decent default within their themes, however when people create custom themes, they can easily override them.

We have created a bunch of rather "generic" variables of such, but eventually (https://github.com/status-im/status-desktop/blob/master/ui/imports/Themes/LightTheme.qml#L76-L85), we needed to have more control and introduce very component specific variables anyways:  e.g. https://github.com/status-im/status-desktop/blob/master/ui/imports/Themes/LightTheme.qml#L90-L98

Here's what I propose:

1. We create a set of color variables that define all possible colors in a given theme (kind of what we already have, but cleaned up)
2. We create a bunch of "generic" variables that make use of the colors (we have that too somewhat, but again we need to clean this up)
3. We create component specific color variables for every component that make use of the original color variables, as well as generic variables. They might use custom colors as well, but should probably be avoided if possible

If done properly, we should be able to create a Theme by simply defining a theme file with just color variables.
Generic and component variables should be derived from that.

**Comment by jrainville** [comment]
> If done properly, we should be able to create a Theme by simply defining a theme file with just color variables.
Generic and component variables should be derived from that.

Yeah this is a great idea. It was the goal when I first started the theme, but like you said, with the addition of more and more specific components, it ended up getting hard to do that, especially since at the start, colors weren't as well named as Simon did now.

Anyway, I'm all for it, it does need a nice cleanup.

**Comment by iurimatias** [comment]
closed in favour of https://github.com/status-im/status-qml/issues/3
