### ISSUE TITLE
Revisit StatusButton component

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2332]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A12

**Comment by PascalPrecht** [comment]
I changed the title of this issue because we already have a `StatusButton` that aims to solve this: https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusButton.qml

However, over the course of implementing this, it has grown and got a little bit out of control, so I think it's a good time clean things up a bit. Here are some things that I believe need to be revisited:

- `StatusButton` has a `type` and  a `size` https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusButton.qml#L9-L10. This has worked in the beginning, but it later turned out to be a burden because we've added additional types that weren't considered in the beginning. Originally it was `primary` and `secondary` to get different visuals, then later on, we added `danger` to get styles for "delete" buttons for example. However, both, `secondary` and `primary` button should be able to be danger buttons as well, so we had to do some rather inflexible changes in the component https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusButton.qml#L84-L91
- Another thing that was later taken advantage of was the `Button.flat` property to get an "outline" button as seen in the designs. In order to make all styles work across different variations we had ended up introducing "quick hacks" like `showBorder` , also `disableColorOverlay`: https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusButton.qml#L27-L28. We might want to consider introducing a `StatusOutlineButton` instead so we can remove a bit of complexity here
- There are some state changes in place for having a `loading` state as per design https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusButton.qml#L11. We might want to look into using QMLs statemachine and `PropertyChanges` instead

**Comment by PascalPrecht** [comment]
This one needs #2360 first.

**Comment by borismelnik** [comment]
Based on Figma i will create 3 components `StatusButton` `StatusTextButton` and `StatusButtonWithIcon`. More readable code.

**Comment by PascalPrecht** [comment]
@borismelnik sounds good. We could possibly keep leveraging QML's built-in `Button.icon` and might not need a `StatusButtonWithIcon` variation, but happy too see what you come up with.

**Comment by PascalPrecht** [comment]
The loading indicator component for the `StatusButton` loading state is available in this commit: https://github.com/status-im/status-desktop/pull/2436

**Comment by PascalPrecht** [comment]
Closing this in favour of https://github.com/status-im/status-qml/issues/6
