### ISSUE TITLE
Implement Nav Bar in the component library

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2336]
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1%3A2

**Comment by PascalPrecht** [comment]
The navbar makes use of a bunch of other components. Namely:

- `StatusTabButton` - https://github.com/status-im/status-desktop/blob/master/ui/shared/status/StatusIconTabButton.qml
- `CommunityButton` - https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Chat/CommunityComponents/CommunityButton.qml

These two need to be revisited. Especially `CommunityButton` because it's really just a `StatusTabButton` that renders some image, instead of an icon. Also `StatusTabButton` should probably make use of `StatusIcon` which will be introduced in #2435 

Hence, we should tackle #2443 and #2444 first.

**Comment by PascalPrecht** [comment]
Just a quick heads-up: I started working on #2443

**Comment by PascalPrecht** [comment]
Closing this in favour of https://github.com/status-im/status-qml/issues/18
