### ISSUE TITLE
Improve message fetching when joining a new channel

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2338]
When we join a channel, typically the last 24 hours are fetched, we should make this a bit smarter so it also tries to fetch at least the last X messages, where X can be at least 100 messages.

**Comment by richard-ramos** [comment]
@cammellos is currently working on https://github.com/status-im/status-go/tree/chore/add-populate-db-script-rebase which should besides helping solve this requirement, it will also include mailserver gaps. These will be normal messages now that require special handling to know that once they're clicked, a status-go rpc call must be made to fetch more messages.

The branch is in a state where integration could be done as the API is expected to not change, so I'll start working on it

**Comment by anastasiyaig** [comment]
@iurimatias what shall we do with the issue? According to the [comment](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/2532#issuecomment-848152010), the issue is not fixed by referenced PR . Maybe it is reasonable to send this to backlog or somewhere else so it will be investigated again?
