### ISSUE TITLE
starting a chat with a non-contact for the first time should show a "+ Add to contacts" bar

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2383]
current:

![Screen Shot 2021-04-22 at 3.09.51 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/3008dd3e-97e2-4459-9dcb-72e8b33c74a5)

desired:

![Screen Shot 2021-04-22 at 3.09.55 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/68a3d6ec-09f6-4599-b5d2-2885045416c1)

**Comment by anastasiyaig** [comment]
I think we don't need this issue anymore:

1. this Add to contacts already present when sending contact request
2. Add to contacts should be removed because of having Contact Request 

<img width="1012" alt="Screenshot 2021-06-16 at 14 53 34" src="https://user-images.githubusercontent.com/82375995/122214694-11eacb00-ceb3-11eb-8496-25a53c8063a7.png">
