### ISSUE TITLE
if a community is approval only then the community dialog should have a request button

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2399]
steps

1. go to communities and select a community that needs invitation

result: greyed out button saying "You need to be invited"
expected result: button to request

![Screen Shot 2021-04-22 at 3.55.55 PM.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/1c9ca064-a1ac-45fa-a404-7fcf0ec6b65f)

**Comment by jrainville** [comment]
This is already working as designed.

On invitation communities should not be "clickable", since you need to be invited.

On approval/request communities work like you posted, but they were hard/impossible to test until now, because there was not a good way to fetch the info of a community until today.

To test it correctly, just try this PR that implemented the community fetching for links: https://github.com/status-im/status-desktop/pull/2471

then, just follow the steps explained in the PR and instead of clicking on the bubble, you can then go in the community list and you will see the community is now there and showing the behaviour shown in the design.
