### ISSUE TITLE
No invitation is shown when user left the group chat and re-invited again

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2602]
1. as device A, create a group chat with device B
2. as device B, accept the invitation to join a group
3. as device B, leave the group chat 
4. as device A, add device B to the same group again

As a result, there is no invitation shown for device B to join the group chat

**Comment by emizzle** [comment]
As I understand it, this was done on purpose in status-go to prevent spam. 

The reason this occurs is because when Device B leaves the group, it remains a member of the chat, but the chat is marked as `active: false` (which means it not visible to or cannot be interacted with by Device B). If Device B was removed as a member, then it would work as desired. This logic may be reverted when the "swipe to delete" feature is included in mobile, as mentioned by @cammellos.

Additionally, when a user is re-invited in Step 4, there is an activity center notification received on Device B's side that looks like the following:
```json
"activityCenterNotifications": [
      {
        "id": "0x0e342d33",
        "chatId": "e342d33f-dd05-4d7b-b14e-b5335e1a3ee9-0x043bf46aa874c377a34946eab67a32cf36c15907b328216dfce375d169fed7d81c21cada3229db1fd37c762d2c02702111a646657feca6621e2e948febcf378fb4",
        "name": "test-22",
        "type": 2,
        "lastMessage": null,
        "message": null,
        "timestamp": 1623305612000,
        "read": false,
        "dismissed": false,
        "accepted": false
      }
    ]
```
There is a possibility that when accepting this notification in the Activity Center, it may allow the user to be re-invited, however since the Activity Center feature hasn't been finished yet on desktop, I'm unable to test that theory.
