### ISSUE TITLE
Failing to login on Mac. Entering seed-phrase brings new Chat Name and Chat Key

### ISSUE THREAD

**Issue by Barukimang** [status-im/status-desktop#2758]
**Issue:**

Failing to login with current password on status-desktop using Macbook.

When entering seed phrase it brings a new chat name and chat key. All previous contacts and messages have disappeared.

Fresh re-install does not work.

Previous account keeps working on synched status-app on Android.

Hearing of one more status-desktop user having the same issue (also using Mac)

**Comment by anastasiyaig** [comment]
@iurimatias so far i cant replicate it

1. spaces are handled correctly (before and after seed phrase)
2. cyrilic "c" is not accepted (instead of latin c)
3. upper-case is not accepted
4. numbers are not accepted
5. less / more than 12 words is not accepted

I am now trying to think of more cases, but would be good to know any other details if possible (build version, any scenario etc)

I also imported same account to mobile and desktop -> dont see a problem

**Comment by iurimatias** [comment]
@Barukimang what version of status-desktop was this?

**Comment by Barukimang** [comment]
@iurimatias it was this version: StatusIm-Desktop-v0.1.0-beta.7

De-installed everything related to Status Desktop.

Downloaded this version: StatusIm-Desktop-v0.1.0-beta.10-06484e

On this version the 12 word seed phrase also bring another chat key and chat name however.

**Comment by Barukimang** [comment]
Tried it again but this time it worked! Maybe had to do with the older version

**Comment by iurimatias** [comment]
we tried and also could not replicate so closing it for now
