### ISSUE TITLE
Agree on Spec & implement user status on a community

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#2811]
To support seeing who is online or not in a community it should be possible to do this with a under the hood channel that each client can send a ping every X minutes, when the app quits it can send a offline ping, no ping in the last X minutes can interpreted as a offline state. We should talk to @cammellos to agree on whatever method is chosen before implementing.

**Comment by richard-ramos** [comment]
**StatusMessage**
Status messages are used to indicate to other nodes the current status of an user account. Clients are expected to use the `status_type` to visually represent the status of the users that belong to a community, or the status of an added contact. Devices receiving a status message from another paired device should update their own status if the received message has a newer `clock` field value.


```
message StatusMessage {
  uint64 clock = 1
  
  StatusType status_type = 7;
  
  string custom_emoji = 3
  
  string custom_text = 4
  
  enum StatusType {
    UNKNOWN_STATUS_TYPE = 0;
    ONLINE = 1;
    DO_NOT_DISTURB = 2;
  }
}
```

Clients MUST specify `clock`, `status_type`, and optionally `custom_emoji` and `custom_text`. For better developer experience this specifications RECOMMENDS creating a function that a user would call to set their current status, and then, the client will periodically send a status message every N minutes containing the latest user's status. The `custom_emoji` and `custom_text` are optional values that can be used to extend the user status with extra content with a short messaje and Unicode emoji

Clients MUST sanitize the payload before accessing its content, in particular the `custom_emoji` and `custom_text` fields

Status messages are sent into specific topics: 
- With communities, a topic derived from the community-id with the suffix `-ping` concatenated. 
- With contacts, a topic derived from the contact public key with the suffix `-ping` concatenated. 

A filter SHOULD be created in the clients using the topics created for a community and contacts to subscribe to the status messages. Mailservers will store these messages since Waku v1 does not have a way to identify if a message is ephemeral and should not be stored in the database, but clients SHOULD not request stored messages from these topics. (An issue has been opened for Waku V2 to introduce the concept of [ephemeral messages](https://github.com/vacp2p/rfc/issues/424))

Since these messages can be thought as the equivalent of a heartbeat message, clients can visually change the representation for the online status depending on the time that has passed since the last time a status message has been received for some user account, and mark a user as offline if the user has not sent a status message in a considerable amount of time

Two new settings are expected to be created on the user's database setting table:
- `send-status-updates`, a `boolean` value indicating whether the status will be sent or not. This feature is opt-out, so the default value is `true`
- `current-status-type`, an `int` value matching the `StatusType` enum.
- `custom-status-emoji`, an optional `string` value that can be used to asociate an emoji to a custom status. Empty by default
- `custom-status-text`, an optional `string` value containing a custom status text. Empty by default

cc: @iurimatias @cammellos

**Comment by cammellos** [comment]
> With contacts, a topic derived from the contact's public key with the suffix -ping concatenated.
Not sure about this, you mean to send a message to each contact you have? I think that would be too expensive and generate quite a lot of traffic.
There's some way around it, but it's difficult not too disclose the fact that you are online to non-contacts, while status could be protected.

**Comment by richard-ramos** [comment]
> Not sure about this, you mean to send a message to each contact you have? I think that would be too expensive and generate quite a lot of traffic.

I mean to have something similar to the timeline status updates. Currently users create a timeline status update by sending a message to a public channel whose id is their own public key,  and any user that adds you as a contact will automatically subscribe to your pubkey channel.

I want to have something similar for status updates, so when a user adds you as a contact they would also subscribe to a channel where the user will periodically send the status updates. (I think we could even reuse the same timeline channel).

**Comment by cammellos** [comment]
Yes, that sounds ok, so basically you only publish once, not each for contact. We already have a topic we can use, the "contact-code" topic

**Comment by oskarth** [comment]
Can we make sure this makes it into a spec in the specs repo? https://github.com/status-im/specs
