### ISSUE TITLE
Recipient of the transaction message is not notified that transaction is completed

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#2915]
Connected issues:
- #2719
- #2720
- #1205
- #1201

PR for this may be seen [here](https://github.com/status-im/status-desktop/pull/2914) but it's not completed cause in the step when sender "Sign and Send" transaction, transaction bubble on the sender side is updated, transaction is received by recipient and funds are on account in his wallet, but transaction message bubble on the recipient side has not been updated.

**Comment by Khushboo-dev-cpp** [comment]
This is a non issue. The test was performed under ropsten and reason the status is not updated is that -> we set the VerifyTransactionURL  to mainnet 
https://github.com/status-im/status-go/blob/f1569e4bde50e993611288a59b7a415a010cbfa8/params/config.go#L614
This is  because -> the URL for verifying transaction is a separate piece of config, we always point it to mainnet, and we don't want to change it if the user changes network, as otherwise someone could trick them and send a ropsten transaction instead of a mainnet
So if any one wants to test for development please set
"VerifyTransactionChainID": 3 &
 "VerifyTransactionURL": "https://ropset.infura.io/v3/" & INFURA_TOKEN_RESOLVED here
 https://github.com/status-im/status-desktop/blob/7f058f3141dee2e0b2a66037501475c3b1825968/src/app_service/common/account_constants.nim#L156 
 and everything should work as expected. 
The PR only fixed the broken UI
