### ISSUE TITLE
Pin and copy actions icons are blurred, also the menu itself is too wide

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#2956]
<img width="1012" alt="Screenshot 2021-07-19 at 15 55 11" src="https://user-images.githubusercontent.com/82375995/126163023-77bb7f4b-aae0-4454-85c4-757f85525ef9.png">

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5395%3A43214

<img width="1422" alt="Screenshot 2021-07-19 at 15 57 34" src="https://user-images.githubusercontent.com/82375995/126163123-f06f920d-d055-45fe-baa7-d4558fd26a8f.png">

**Comment by pinebit** [comment]
The bug is in `PopupMenu.qml` implementation:
```
            Image {
                id: menuIcon
                source: popupMenuItem.icon.source
                visible: false
                width: parent.width
                height: parent.width
                sourceSize.width: width
                sourceSize.height: height
            }
```
it is incorrect to set `sourceSize` to the final rendering Image size. The `sourceSize` property must always match the original SVG size. Then width and height properties of Image can specify the desired rendering canvas size. What makes this even worse - most SVG icons we use in Menus have different sizes.

How to fix:
Every `Action` that has `icon` property set, must always specify `width` and `height` of the original SVG (need to manually open each SVG and check the size). These values we will assign to `sourceSize: Qt.size(popupMenuIcon.icon.width, popupMenuIcon.icon.height)`. Next, since all icons in a given menu must have the same final rendering size (e.g. 16x16), we should introduce a property on PopupMenu item that defines the common icons size, e.g. `iconsSize`. Then `indicator: Item {` must be always sized to `popupMenu.iconsSize` and then `menuIcon` should be aligned inside the parent item using proper scaling/fit mode.

**Comment by iurimatias** [comment]
@anastasiyaig I don't see this bluriness on master, could you confirm if you still see it plz?

**Comment by anastasiyaig** [comment]
@iurimatias the bug is there, it is in 1x1 chat:

<img width="1344" alt="Screenshot 2021-07-28 at 11 58 41" src="https://user-images.githubusercontent.com/82375995/127294764-8e121c8e-3eac-44b5-8c46-fd4482161fec.png">

i checked in https://ci.status.im/job/status-desktop/job/release/job/release%252F0.1.0-beta.11/5/

**Comment by PascalPrecht** [comment]
This blurryness should not be an issue when rendered using StatusQ components. We should replace `PopupMenu` with `StatusPopupMenu` and see if this issue still persists

**Comment by Khushboo-dev-cpp** [comment]
The more Pop up isn't opening in an 1-1 chat.
Get the following error - qrc:/app/AppLayouts/Chat/ChatColumn/Message.qml:215: ReferenceError: nickname is not defined
Need first fix that and then check the reported issue.

**Comment by iurimatias** [comment]
@Khushboo-dev-cpp you need to update to the latest master
