### ISSUE TITLE
Edit message input field doest change its appearance on dark mode

### ISSUE THREAD

**Issue by simonricoo** [status-im/status-desktop#2978]
<img width="1020" alt="Screen Shot 2021-07-20 at 13 18 56" src="https://user-images.githubusercontent.com/52249767/126315711-3462fc0f-ed4b-4ccc-84cd-b3bf34dea28a.png">

**Comment by PascalPrecht** [comment]
@simonricoo Could you pls provide a solid color hex code for both, light and darkmode for the input here?

The reason I'm asking for this is because, as per design, this uses colors with transparencies. Unfortunately that doesn't work well because we need to do some funny rectangle layering to get these inconsistent rounded borders. The result is that you'll see the layered rectangles slightly darker than the rest because their color saturation adds up..

**Comment by simonricoo** [comment]
Light: E2E6E8
Dark: 414141
@PascalPrecht
