### ISSUE TITLE
Mention color is too bright when being replied to

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3012]
1. mention someone in community channel for example
2. reply to this message

As a result, the color of the mention is too bright

<img width="1055" alt="Screenshot 2021-07-21 at 23 19 21" src="https://user-images.githubusercontent.com/82375995/126554773-7f877f2f-51c2-46d0-9d60-73acaf86b657.png">

**Comment by simonricoo** [comment]
Currently working on this component, the style should be the same as the mention in regular message. The font size should be 13 Medium instead of 15 Medium though.
<img width="1405" alt="Screen Shot 2021-07-22 at 15 12 35" src="https://user-images.githubusercontent.com/52249767/126644579-47b47315-cd34-4385-900b-09c18db1b556.png">
https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1888%3A15572

**Comment by Khushboo-dev-cpp** [comment]
Hey @simonricoo that link is not working for me. Can you please point me to the correct design file?

**Comment by simonricoo** [comment]
Sorry it was caused by reorganising the file: Here is the new link: https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1855%3A11069

**Comment by Khushboo-dev-cpp** [comment]
@simonricoo No problem :)
But that above link still doesn't open for me. 

Error Msg: Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions.
