### ISSUE TITLE
Public key on login screen sometimes does not match actual public key value from profile when reinstalling the app over and over

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3035]
When upgrading the app , the user data is stored. On login screen there is a value of public key , that should show the public key of an account user , which currently does not match. For instance:

My chat key is: `0x0461904235fb5762daf2970bd61b070784f3705fc51d5c96ea798d81a6552599c4f6c88ba9e83686080710b419dbdcca7a5c5ff9e8de7dd58f38a1c8be4c9a5a1d`

On login screen i do see this:

<img width="1344" alt="Screenshot 2021-07-23 at 10 39 43" src="https://user-images.githubusercontent.com/82375995/126751470-4b3343c9-5118-4e7f-a177-e899ebfe2497.png">

This value does not match neither chat key, nor wallet address, no private key of the account i am using

**Comment by michaelsbradleyjr** [comment]
As discussed in the #status-desktop chat, the unencrypted accounts database does not store public keys, nor can public keys be derived from information stored in that database. Rather, that database stores a deterministically derived `keyUid` (in addition to the three-word name and some other data, e.g. last login timestamp) used to identify an encrypted account database. The `keyUid` is derived with the one-way-hash sha256.

Since the mobile app displays only the three-word name in the login screen, maybe the desktop app should do the same, i.e. if the `keyUid` is more a source of confusion for users than being helpful to them.

See: https://github.com/status-im/status-go/pull/1716.
