### ISSUE TITLE
Scrolling chat history is not smooth

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3067]
When scrolling history, the scroll itself is not smooth, looks like it has some breakpoint. It could get worse when having a picture or reply in a text box as well.

https://user-images.githubusercontent.com/82375995/127123446-b60e30db-6257-45c1-b138-493cae50b514.mov

**Comment by pinebit** [comment]
`ListView` is technically unable to determine the expected `contentHeight` due to dynamic loading of delegates and different delegate heights. Also, our chats have too different items (some small, some too height) and approximation made by ListView components does not work well for our case.
This results in this terrible user experience: https://www.youtube.com/watch?v=3fC1lzTHP_0

One simple solution to this problem is to use cacheBuffer property: https://doc.qt.io/qt-5/qml-qtquick-listview.html#cacheBuffer-prop
When I tried to set this to 5000 (ad hoc value), this made all scrolling working smooth, but at the price of extra memory usage (+50Mb for chat in my case).
The more complex solution would it be to do the same as Discord does: try to scroll #random by holding and moving the scrollbar handle to the top. This will require some coding...

Opened discussion in #random to brainstorm this further.

**Comment by MishkaRogachev** [comment]
There was two problems, one left: 
1) ListView by itself behave twitchy with Mac touchpad with default parameters, resolved with https://github.com/status-im/status-desktop/pull/6456
2) Chat content changes height, as mentioned before @pinebit. https://github.com/status-im/status-desktop/issues/6548

**Comment by alexjba** [comment]
This is a performance issue. The MessageView is a heavy component and 80% of the scroll time is spent on creating the MesageView. The experience is much better if we use ListView.reuseItems, but it it available in 5.15. Even with reuseItems there are still small hiccups that needs to be investigated.

The proposed solution is to enable ListView.reuseItems (after #8642 is completed) and further investigate the smaller hiccups.
