### ISSUE TITLE
Search results do have broken UI

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3142]
1. open 1x1 chat
2. send some messages there
3. search for any part of the message text (valid search criteria)
4. search one more time for another search criteroa (still should be valid)

<img width="1012" alt="Screenshot 2021-08-03 at 12 56 57" src="https://user-images.githubusercontent.com/82375995/127997256-48f480e9-4c57-4681-8679-f0f6d9b7b575.png">

https://user-images.githubusercontent.com/82375995/127997104-475f4fea-7b9a-4bb6-afef-e8a725033013.mov

**Comment by iurimatias** [comment]
I can replicate it, given it makes the search unusable in some cases I'll increase the priority to high

**Comment by saledjenic** [comment]
@anastasiyaig do we need to wast time on this since we have new UI for that part (which is in progress now and will be ready soon) in [this ticket](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/2934), where the search result list is created in other way and works well, I tested it there while I was working on that part?

If that's ok, you may close this ticket.
