### ISSUE TITLE
Linux trackpad scroll in sidebar is fast beyond usability

### ISSUE THREAD

**Issue by zach-is-my-name** [status-im/status-desktop#3353]
The left panel scrolls way too quickly to use my trackpad

v0.2.1
Ubunut 20.04

![statusScroll](https://user-images.githubusercontent.com/16063092/131750577-32e14fc7-7d6c-4c1f-a982-f4964db2f098.gif)

**Comment by rapidddenis** [comment]
the same goes for stickers scrolls

**Comment by richard-ramos** [comment]
relevant: https://bugreports.qt.io/browse/QTBUG-56075

**Comment by richard-ramos** [comment]
The issue has been fixed in Qt 5.15.8 and in 6.2.0. 

For Qt 5.15.8 we need to wait until January 2023, which will be the date when this version will be opensourced (due to the agreement Qt has with KDE) to have access to this fix, and will probably have to build Qt ourselves.
![image](https://user-images.githubusercontent.com/1106587/159281419-375b4271-9cc5-4b02-aa05-f187dec496d4.png)

Qt 6.2.0 is already available.

For both of these solutions we need to update https://github.com/status-im/status-desktop/pull/3499 to point to the correct version (5.15.8 when released and is available with `aqtinstall`,  or 6.2.0)

**Comment by caybro** [comment]
> The same is for chat messages and I've been on Qt 5.15.8 since we moved to Qt 5.15.2 and nothing has changed, it is still too fast

For me, it's way too slow :/ I have literally swipe up over the whole touchpad several times to make it scroll at least half the viewport height

**Comment by caybro** [comment]
For the reference, using Qt 5.15.8 on __Wayland__

**Comment by jrainville** [comment]
Fixed by https://github.com/status-im/status-desktop/pull/10236
