### ISSUE TITLE
Running make after changing status-lib doesn't recompile

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#3639]
After making a change in status-lib, doing a make doesn't recompile the app

**Comment by richard-ramos** [comment]
I can reproduce this issue on my machine as well

**Comment by michaelsbradleyjr** [comment]
This is a result of the changed Nim sources not being among those checked by `make`.

I have an idea, though. Whenever `make update` is run (which you'd do after bumping e.g. `vendor/status-lib`) the file `.update.timestamp` in the root of the repo gets bumped.

So we can add `.update.timestamp` to the `NIM_SOURCES` list in status-desktop's Makefile and it should fix the problem.

Thoughts?

**Comment by michaelsbradleyjr** [comment]
> After making a change in status-lib, doing a make doesn't recompile the app

@alaibe is your workflow to change the sources in status-desktop's `vendor/` directly? There's nothing wrong with that, just thinking about how we can come up with a nice solution (or we can go back to recompiling every time).

**Comment by alaibe** [comment]
@michaelsbradleyjr yes I directly change file in vendor. Happy to change my workflow if you have a faster one ;)

**Comment by michaelsbradleyjr** [comment]
> Regarding adding vendor/status-lib, I personally vote for that one. But as said happy to adapt if needed. Is there any trade off?

I don't think there will be much trade off, I tried it locally and there's still a nice speed bump from not compiling `.nim` sources if nothing has changed in `src/` or `vendor/status-lib/status`.

> If someone is only developing on status-desktop and not status-lib that would not make any big difference right? Cause they won 't just recompile that file?

Correct.

> Also something I would like to understand: when doing a git pull; make update if the only changes are a status-lib bump it won't recompile?

The next time you run `make` or `make run` after `make update`, it would recompile because the `mtime` of `.update.timestamp` is changed when `make update` overwrites that file.

> adapt if needed

To give an idea of what you could do if we don't add `vendor/status-lib/status` to `NIM_SOURCES`:

When making changes in `vendor/status-lib` (or any other `.nim` sources in `vendor/`), you could be in the habit of doing:
```
$ touch .update.timestamp && make run
```
That would trigger a recompile because `touch` will change the `mtime` of `.update.timestamp`.

Alternatively, add it locally like I showed in my previous comment but don't commit it.

**Comment by alaibe** [comment]
> `touch .update.timestamp && make run`

This would work for me (I usually Ctrl-R and not retype everything). I think we should just document it somewhere to avoid surprise

Thanks for all the explanation

**Comment by michaelsbradleyjr** [comment]
In #3652 I've implemented support for `REBUILD_NIM=true` and `REBUILD_UI=true`. I've included explanatory comments in the Makefile and updated dev docs here:

https://hackmd.io/OtFjDnH6QtOl3K65fKKEGg?view#3-Build-binnim-status-client-and-run-the-app
