### ISSUE TITLE
Encrypt profile settings

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#3660]
The same way the dbs are encrypted, we should also try to encrypt the profile settings which are accessed after being logged in

**Comment by saledjenic** [comment]
@alaibe none of the properties stored in either global or user specific local .ini file don't contain any important info. They just store values about app settings for specific user, like... is wallet section enabled or disabled, what language is the default one for the app and so.

To be clear, of course we can do this, but since there are no any important info in local .ini files which may be used for any hack and compromising a user's personal info/accounts do we need to do this?
