### ISSUE TITLE
tabs are empty in activity center

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3957]
when having a reply or mention, messages should appear in ALL / mention / reply sections

<img width="1440" alt="Screenshot 2021-10-29 at 12 47 09" src="https://user-images.githubusercontent.com/82375995/139414195-25f53616-a2b6-4d13-90af-abf9eed7ffc5.png">

**Comment by jrainville** [comment]
@anastasiyaig I just tested, and even though I could "reproduce" at first, I checked the status-go code and it seems like it is by design.
The mentions and replies only appear in the activity center when in a community chat and private group, not in 1-1 chats, since it already counts as a mention at all times

**Comment by anastasiyaig** [comment]
okay, then closing it
