### ISSUE TITLE
[refactoring/base_01] windows login to the app is extremely slow

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#3973]
<img width="1552" alt="Screenshot 2021-11-01 at 13 55 21" src="https://user-images.githubusercontent.com/82375995/139661375-685a5b35-96b9-4324-a2fb-11e9e79e3c3b.png">

it takes a lot of time to generate account and to login

https://user-images.githubusercontent.com/82375995/139662159-ce2b40e2-c230-45fb-9c37-dfa0a04fadb4.mov

**Comment by jrainville** [comment]
I tested Windows and Linux and both had the same account creation (Linux begin a bit slower, but still close enough)
I think base_01 will be slower than master (or latest beta) until we finish some of the refactors, since we load some stuff twice.
I'll leave this task open until we have some more fixes in.
