### ISSUE TITLE
[refactoring/base_01] click the context menu view group shows a blank modal, or sometimes even crashes

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#3975]
![upload_c96fb6b5df363fbc15532cf0e3ea0bb8](https://user-images.githubusercontent.com/176720/139671525-e028113e-60e4-4d56-8954-87f76592c50b.png)

**Comment by alexandraB99** [comment]
as per [design](https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/💬-Chat⎜Desktop?node-id=987%3A662), the channel seems activated when even right clicked
<img width="925" alt="group_channel" src="https://user-images.githubusercontent.com/31625338/140428717-ffe33c04-cdd9-4e44-a2ab-52cc4fb480b1.png">
<img width="570" alt="channel" src="https://user-images.githubusercontent.com/31625338/140428742-6a8747bc-0b93-4d95-b92b-36633f8b64b0.png">

**Comment by PascalPrecht** [comment]
> as per design, the channel seems activated when even right clicked

Unfortunately, it's not actually clear judging by these screenshots. Notice that the active channels also **happens** to be the one that is right clicked. We don't know how it would be have if a different item was clicked.

In addition, it seems you're looking at old designs. I remember actually "fixing" this back then so that right clicking a chat item that isn't the selected one, also doesn't select that item (user only wants a context menu after all).

I've discussed this with @simonricoo and he confirmed this.

**Comment by alexandraB99** [comment]
> > as per design, the channel seems activated when even right clicked
> 
> Unfortunately, it's not actually clear judging by these screenshots. Notice that the active channel also **happens** to be the one that is right clicked. We don't know how it would behave if a different item was clicked.
> 
> In addition, it seems you're looking at old designs. I remember actually "fixing" this back then so that right clicking a chat item that isn't the selected one, also doesn't select that item (user only wants a context menu after all).
> 
> I've discussed this with @simonricoo and he confirmed this.

thanks @PascalPrecht for clarifying!
