### ISSUE TITLE
Can't select emoji from the list

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4102]
# Bug Report

## Description

Can't select emoji from the list

## Steps to reproduce

1. open 1x1 chat
2. click emoji
3. select any emoji from the list

#### Expected behavior

Can select a nice emoji and send it

#### Actual behavior

```
DBG 2021-11-11 21:46:32.516+03:00 callPrivateRPC                             topics="rpc" tid=550184 file=core.nim:20 rpc_method=eth_call
qrc:/imports/shared/status/StatusEmojiPopup.qml:64: TypeError: Cannot call method 'unshift' of undefined
```

### Additional Information

- Status desktop version: `master` commit `2d0c95feb3e3eca8895fde4425c9c861c49ca992`
- Operating System: macOS Big Sur

**Comment by alexandraB99** [comment]
I looked a bit into this, the issue it seems it's caused by https://github.com/status-im/status-desktop/commit/f0b2ed6cca7075156ecbe39415bc2441f19478e9. All below properties that were arrays before:

```
property var recentEmojis: []
property var hiddenCommunityWelcomeBanners: []
property var hiddenCommunityBackUpBanners: []
property var whitelistedUnfurlingSites: ({})
```

are currently undefined. @saledjenic any ideas?

**Comment by saledjenic** [comment]
> I looked a bit into this, the issue it seems it's caused by [f0b2ed6](https://github.com/status-im/status-desktop/commit/f0b2ed6cca7075156ecbe39415bc2441f19478e9). All below properties that were arrays before:
> 
> ```
> property var recentEmojis: []
> property var hiddenCommunityWelcomeBanners: []
> property var hiddenCommunityBackUpBanners: []
> property var whitelistedUnfurlingSites: ({})
> ```
> 
> are currently undefined. @saledjenic any ideas?

@alexandraB99 the thing is most likely in default value which is set on the app start in case values for mentioned properties are not set before. 

Since `nimqml` doesn't have support for nim type QVariant, doesn't have appropriate constructors which will deal with array and object type (even QVariant on the Qt side knows that), we cannot set on the Nim side anything but default types for our properties plus QObject type.

So there are 2 solutions here:
- to add appropriate constructors on the `nimqml` side and corresponding parts to `dotherside` and then use the on the nim side in the standard way you expected
- to pass empty string and deal with it on the qml side, that means above mentioned props in the `LocalAccountSensitiveSettings` class will have in case of array "[]" and in case of object "{}" default values and on the qml side you must pars them and use further

**Comment by anastasiyaig** [comment]
i can reproduce it in latest 0.4.0 release:

`qrc:/imports/shared/status/StatusEmojiPopup.qml:64: TypeError: Property 'unshift' of object  is not a function`
