### ISSUE TITLE
Stickers placeholder is gone

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4127]
# Bug Report

## Description

If user does not have any stickers installed yet, there should be a placeholder saying that.

## Steps to reproduce

Click stickers button in chat

#### Expected behavior

(this is from beta 0.3.0)

<img width="1344" alt="Screenshot 2021-11-17 at 16 47 03" src="https://user-images.githubusercontent.com/82375995/142212942-4b2b64e5-1e07-442b-bae7-d90f75e060d9.png">

#### Actual behavior

<img width="1552" alt="Screenshot 2021-11-17 at 16 46 56" src="https://user-images.githubusercontent.com/82375995/142212980-4863456f-e41d-43e1-8e07-986d8ef1a4a0.png">

### Additional Information

- Status desktop version: master
- Operating System: macOS BigSur

**Comment by PascalPrecht** [comment]
Quick update on this:

The reason why it's loading so long is because it loads all available sticker packs sequentially. I'm not sure what's the best way to make this concurrently in nim. The cases where it keeps loading and doesn't update means that it never finishes loading the available sticker packs. This could also be solved if we had a way to already update the view if at least one of the available packs data has arrived.

However, a quick improvement would be to at least **not** wait until all the loading is done to show that no sticker packs have been installed. That's something we know immediately. When we know immediately that there are no installed stickers, we can also derive that there's no "recent" stickers, meaning we can stop showing the loading indicator very early. 

In case the user **does** have installed stickers, we can just keep on loading as we do now.

That's for the theory. In practice I've been struggling to send a signal to the front-end once we know we don't have installed sticker packs. I'm sure I'll have it figured out tomorrow and send a PR for a quick improvement.

**Comment by jrainville** [comment]
FYI @PascalPrecht , I did a huge refactor on the stickers in this PR https://github.com/status-im/status-desktop/pull/4113
It's not 100% finished, but still, if you were to add new stuff in master, our conflicts would be pretty massive.
The problem you listed above is probably present in my PR as well, but it's worth testing.
Anyway, just letting you know in case you need to add some new code (and not just a quick fix), it would be probably better to do it on top of my branch.

**Comment by PascalPrecht** [comment]
Thanks! I'll have a look!
