### ISSUE TITLE
Enabling Debug flag crashes the app and makes it not responsive after restart

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4157]
# Bug Report

## Description

Enabling Debug flag crashes the app

## Steps to reproduce

Enable Debug flag in Advanced

#### Expected behavior

No crashes

#### Actual behavior

App crashes (or closes without notice) when enabling the flag. After i start the app again, it hangs with Application not responding after a minute or so

### Additional Information

- Status desktop version: master 23-11-2021, commit `de6425446322d728c12eb599c83f1c9728d7bd6f`
- Operating System: macOS

**Comment by PascalPrecht** [comment]
So few thoughts here:

> Enabling Debug flag crashes the app

It's actually not crashing when enabling it, it even tells you that you'll be signed out and have to restart. So this seems to be by design (we do the same when networks are changed by the way).

Now, do I think this is ideal? Definitely not. Ideally we would restart the app automatically. Would have to look into what's possible there...

> After i start the app again, it hangs with Application not responding after a minute or so

This part I can not reproduce. Application doesn't hang for me even after several minutes with DEBUG turned on.

**Comment by anastasiyaig** [comment]
i will check more later in master

**Comment by PascalPrecht** [comment]
@anastasiyaig did you have a chance to reproduce this reliably?

**Comment by PascalPrecht** [comment]
Another friendly ping

**Comment by anastasiyaig** [comment]
i will check when testing master this week, until that i will close the issue
