### ISSUE TITLE
Jumping to search result doesn't work

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#4175]
# Bug Report

## Description

When using the application-wide search, clicking on a result to jump to that result doesn't work. Simply nothing happens.

## Steps to reproduce

1. Start app and long in
2. Click search bar and enter any search term
3.  Results will be shown
4. Click any search result, notice that nothing happens

#### Expected behavior

Clicking on a search result should take me to that search result.

### Additional Information

- Status desktop version: c67384367
- Operating System: macOS Cataline (10.15.3)

**Comment by alexandraB99** [comment]
This commented out [here](https://github.com/status-im/status-desktop/pull/3951/commits/b198225b84e68240c3bae932ba2c6d35dc1ae649#diff-75aa5939547b33fcdd3336326d52f8714888cd809c4d13b496b9d5f1febcbef6R120). @saledjenic what is the plan for this?

**Comment by saledjenic** [comment]
> This commented out [here](https://github.com/status-im/status-desktop/pull/3951/commits/b198225b84e68240c3bae932ba2c6d35dc1ae649#diff-75aa5939547b33fcdd3336326d52f8714888cd809c4d13b496b9d5f1febcbef6R120). @saledjenic what is the plan for this?

@alexandraB99 at the moment I was working on `app search` refactoring we didn't have everything prepared in order to complete this feature. Actually I am not sure that we have it yet (in terms of qml part). 

All in all what we need to do here is:
- we need to add datastore to the message service where we will store for each received message important details (communityId, chatId, messageId)
- now when user clicks on a certain message from a search result we should pass id of the clicked message, chatId and communityId if a message belong to any of communities to the view of the app search module
- app search module will call method from message service `loadIfNeededAndJumpToMessage`
- a method from previous step will check if a message with certain details exists in the datastore we have in message service and then:
  - if yes, we will send a signal `jumpToMessage`
  - if not, we will load 20 messages asynchronous in a loop until we are sure that we loaded a message which was clicked by user, when such message is loaded then we send a signal `jumpToMessage`
- in `init` method of controller from message module we should connect to `jumpToMessage` signal
- once `jumpToMessage` signal is received in the controller from message module, we should via view of that module send a signal which will be connected to `jumpToMessage` function on the qml side, where that message will scroll the message list in appropriate chat/community/channel to the message with passed id

That should be a correct flow. So as you may see there are some thing to be added on the backend side, and some things on the qml side. On the qml side now we have everything for that action, but on the qml side we still don't have messages in place.

If I can help somehow let me know or if you want I can take over backend part or complete feature.

**Comment by iurimatias** [comment]
this is working now
