### ISSUE TITLE
ENS name of the current user is not shown in the list of community members

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#4187]
It should display `rramos.eth` since that's the ENS i set in my account
![image](https://user-images.githubusercontent.com/1106587/143484832-961db513-2b8b-44ae-bfcb-483f512b77e1.png)

**Comment by anastasiyaig** [comment]
@richard-ramos this also happens in Beta 0.3.0 , we can fix it in next version

**Comment by PascalPrecht** [comment]
Some updates here as I'm looking into this:

- Turns out it is working just fine when all contact data for the given member is complete. "Complete" meaning, the member contact data need to have their `ensName` set and `ensVerified: true` (assuming they **do** have an ENS)
- However, for some reason, the contact data we're operating on doesn't seem to be complete all the time. In a test with @richard-ramos , I've added him as a contact, he added me back, and we're in the same community. In this scenario, the contact data I've received from status-go, gave me `ensName: ""` and `ensVerified: false`, **even though** he does have an ENS configured
- Once he sent a message to some channel in the community we're both in, the data was updated

So, need to explore:

1. How come his data got updated after he sent a message and why was it not complete in the first place?
2. In addition, I have an ENS set and configured myself, but also my own contact/profile data says `ensName: ""` and `ensVerified: false` which is incorrect

**Comment by PascalPrecht** [comment]
Putting this on hold for now as:

1. It "actually works" it just so happens that the ENS information isn't immediately propagated
2. It's a bit unclear to me where to dig further into this and there's other bugs for 0.4.0 we need to get fixed first

**Comment by iurimatias** [comment]
reprioritizing this

**Comment by iurimatias** [comment]
this has been fixed, kudos @richard-ramos
