### ISSUE TITLE
Can't open a sticker pack when clicking a sticker in a chat

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#4203]
# Bug Report

## Description

Can't open a sticker pack when clicking a sticker in a chat

## Steps to reproduce

1. open any chat
2. install free stickers
3. send a sticker to chat
4. click the sticker

#### Expected behavior

https://user-images.githubusercontent.com/82375995/143881685-37df159d-9cb9-4675-9113-4390e52b0031.mov

#### Actual behavior

Clicking a sticker does not open a sticker pack

### Additional Information

- Status desktop version: beta 0.4.0
- Operating System: macOS

**Comment by alexandraB99** [comment]
This occurs in master branch as well, pushed the same fix in [master](https://github.com/status-im/status-desktop/pull/4208) and [release/0.4.0](https://github.com/status-im/status-desktop/pull/4207). However noticed that the `onStickerPacksLoaded` signal (ChatLayout.qml line 35) is never emitted if the StickersPopup is not opened and stickers are not loaded there first. @PascalPrecht you mentioned something about some on going work on stickers loading the other day, is there any news regarding this?

**Comment by PascalPrecht** [comment]
> @PascalPrecht you mentioned something about some on going work on stickers loading the other day, is there any news regarding this?

Stickers **are** loaded  (also on latest `master`) it can just take a very long time because we're loading them sequentially and somehow, response time is very slow. 

The work I've done was to give faster visual feedback to users who open the popup in cases they want to inject a sticker.
The way it was is that you see a loading spinner, even though, it should tell you that you don't have any stickers installed yet (which we know right away, not just when we load all sticker packs).

Here's the PR: https://github.com/status-im/status-desktop/pull/4159

This however doesn't improve actual loading performance of sticker packs
