### ISSUE TITLE
Regenerate translation

### ISSUE THREAD

**Issue by alaibe** [status-im/status-desktop#4233]
# Bug Report

## Description

Due to the recent refactoring of the QML files, most of the translation now indicate wrong file/LoC
Once the refactor is over I would suggest to `sed /qstrid/qstr/g` before regenerating all the translation

**Comment by PascalPrecht** [comment]
> sed /qstrid/qstr/g before regenerating all the translation

Just raising awareness that this won't do it because `qsTr()` takes actual text which is then used to create an id that is passed to `qsTrId()`

So for example: `qsTr("Hello world!")` becomes `qsTrId("hello-world")`.
If we replace `qsTrId()` with `qsTr()` this would become `qsTr('hello-world')`. If we then run the translation script we don't actually get translated text but translation ids.

**Comment by jrainville** [comment]
I'm pretty sure we do **not** have to change the `qsTrId`. `lupdate` from QT should do the changes automatically.
Basically, it scans every QML file and then creates/updates the translations file. If translations are moved out of a file, it will delete the entry, and vice versa for those added.

**Comment by PascalPrecht** [comment]
>  If translations are moved out of a file, it will delete the entry, and vice versa for those added.

So assuming we go from `qsTr("hello world")` (which becomes `qsTrId("hello-world")`) and replace that with `qsTr("hello-world")` it somehow magically knows that the text to be translated is `hello world" and not `hello-world`?

I would expect it to then also translate `qsTr("hello-world")` to `qsTrId("hello-world")` but now we have an ID that happens to be the same as the text (`hello-world` while we actually want `hello world`).

Sorry for elaborating on this here :D 
I trust you that it works, I'm just curious how it would know given that there's no link to what the actual text to be translated was before...

**Comment by jrainville** [comment]
> So assuming we go from qsTr("hello world") (which becomes qsTrId("hello-world")) and replace that with qsTr("hello-world")

I'll stop you here. We must NOT do that at any point. Like you then said, it would break everything as there is then no way to find what the original text is.

Right now, we have a JS script that transforms `qsTr` into `qsTrId` because we want to use IDs since status-react uses IDs as well and we can reuse some of their translations.

That script doesn't not work the other way around.

But all that is not really necessary, because whether we use `qsTr` or `qsTrId` doesn't matter. QT is the one that parses the files during `lupdate` and creates and updates the translation files. 
So I'm just warning to NOT touch the IDs and just running the translation steps as in the docs is fine.

**Comment by alaibe** [comment]
@jrainville sorry for coming back to this, I agree with you it will replace the qsTr to qsTrId. However as we moved file around, we can now find `qstrid` function call but not translation file associated to it. You are saying that the script/qt will fix the translation file for us automatically?

**Comment by alaibe** [comment]
Alright I *trust* you blindly. I will close the issue then. Thanks for looking into it
