### ISSUE TITLE
move message component statusq

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4272]
### Description

Will Used this task to evaluate and come up with subtasks to break this task down further

**Comment by Khushboo-dev-cpp** [comment]
This issue needs to be analysed and be divided into several subtasks -

API should be something like below
1. Sender Name
2. has mention
3. Time info
4. Profile Picture info
5. Pinned message
6. Message Content
  a. Text message
  b. Image message (open in full screen should be self contained and also the various actions of right click of button?)
  c. Sticker
  d. Gif
  e. Audio
7. Edit Mode
8. is a reply and the reply component itself.
9. Quick Actions button panel

**Comment by Khushboo-dev-cpp** [comment]
StatusMessage {
        messageFromUser: true
        senderName: "Sender of Message"
        senderProfilePicture: image||identicon
        contentType: StatusMessage.Type.Text ||
                     StatusMessage.Type.Image ||
                     StatusMessage.Type.Sticker ||
                     StatusMessage.Type.Audio
        messageText: "This is a message"
        imageMsgSource: "img"
        stickerData: sticker
        timeInfo: ""
        isMessagePinned: true
        pinnedBy: someone
        isAReply: true
        // replyDetails: Can convert this into a sort of array of vars but maybe difficult to read
        senderNameBeingReplied: "senderName"
        senderProfilePictureBeingReplied: "source"
        contentTypeBeingReplied: StatusMessage.Type
        msgTextBeingReplied: text
        imageMsgSourceBeingReplied: "image"
        stickerBeingReplied: sticker
        editMode: false
        // Edit mode can be handled completely internally with a signal emitted to set new text
        onEditCompleted: {
        // inform BE to update sent Message
        }
        quickActions: {StatusFlatRoundButton{onClicked: {/*Do Action*/}}, StatusFlatRoundButton{},StatusFlatRoundButton{}}
        // Should EMoji reactions Panel or EMoji be in StatusQ? what if this expands to stickers in future?
        footerComponent: EmojiReactionsPanel
         // We have contrints that we cant show message + Image in same message? Will there be support in the future? should we create a component that supports that already?
        onRightClick: {/* show a different context menu*/}
    }

    // Create components for the content Items, AudioMessage, Image with its fullscreen overlay self contained. Also for ReplyPanel

**Comment by alexandraB99** [comment]
This component is generally used as a delegate thus getting all info from a model. In case of `ChatMessagesView` and `PinnedMessagesPopup` is `model.property` and in the case of `ActivityCenterMessageComponentView`is `model.message.property`. Exception is the case that is used in `AppearanceView` as preview sample where the properties are set with a default value. That said, we could probably directly do all assignments inside the component instead of exposing all these properties as an API and have it detecting where is in `ActivityCenterMessageComponentView` to get from `model.message` otherwise just `model`. In the `AppearanceView` case we could either think about creating a minimal `MessageView` component that only demonstrates a preview or use the same one in a "preview" mode. What we should really think about is expose somehow several of its properties that are needed by other components, it could be some function that returns the specific property from the specific selected message in the view or something like this.

**Comment by PascalPrecht** [comment]
Moving the discussion to https://github.com/status-im/StatusQ/issues/499

**Comment by iurimatias** [comment]
closing since this issue moved to StatusQ
