### ISSUE TITLE
notifications aren't being triggered

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4409]
# Bug Report

## Description

No notifications are seen regardless of the settings in this branch

**Comment by saledjenic** [comment]
@iurimatias in order to know what to do we need firstly to agree about the details, so please check below and correct me, if I missed something.

**Topic 1**:
In `Settings->Notifications` we may set our preference for notifications. I see them as two types of notifications:
1. `OS notifications` 
2. `App notifications`

Why I see these two, cause notification's style displayed there doesn't match OS notification bubble style. In case of `App notifications` I see that we have `NotificationWindow` component (which was not in use before in "old" master) and it uses `StatusMacNotification` component which is a part of `StatusQ` and that’s actually a style of notification displayed in the `Settings->Notifications`.

Because of above these two types should be mutual exclusive so either you will get `OS notifications` or `App notifications`. Then regardless what type you select you should be able to select what info/details that notification should display, selecting one of options `Anonymous`, `Name Only` or `Name & Message`. Changes described so far require slightly update in `Settings->Notifications` panel.

Above mentioned is the first thing we should agree on.

(For `OS notifications` we may add image and everything around that, but that requires additional handling in ObjectiveC using macOS native functions, and that's something we don't have implemented yet (didn't have in the "old" master as well))

**Topic 2**:
Another thing for review is what all we need to have notification for:
1. notification on contact request (when someone adds me as a contact); click on this notification should open contact request popup
2. notification contact request is accepted (when one I added as a contact accepts my contact request); click on this should point you to the Settings->Contacts tab
3. notification for new message this includes mention message as well (following selection `Anonymous`, `Name Only` or `Name & Message`); click on this should point you to that message making appropriate section active and appropriate chat active before that
4. Notification that someone wants to join my community; click on this should open popup of community’s pending members
5. notification that my request to join community is accepted; click on this should switch the app to that community
6. notification that my request to join community is rejected; click on this does nothing
