### ISSUE TITLE
[base_bc] Newly created Community remains highlighted 

### ISSUE THREAD

**Issue by abhi-status** [status-im/status-desktop#4519]
# Bug Report

## Description
After creating a community, the community remains highlighted, until another community is selected

## Steps to reproduce
1- Create a community
2- Select Chat
3- Select Settings

#### Actual behavior : 
https://www.loom.com/share/7cada02f232e4d3ea8dfed6093280629
### Additional Information

- Version: base_bc Commit : [d8ee609c62fb7c2463575b610c1a291334754e0a](https://github.com/status-im/status-desktop/commit/d8ee609c62fb7c2463575b610c1a291334754e0a)

**Comment by Khushboo-dev-cpp** [comment]
Spent a day looking and analysing this. The issue is as below -
The new community is added to chat_section, it set to active true as is visible on the UI
However, when we switch to chat the same chat_section model contains the new community with active = false and hence there is nothing to change and the community active on UI remains the same.

Why the new community in the model changes to active and then to false is really not understandable. Will try to look at it from a different angle.

**Comment by Khushboo-dev-cpp** [comment]
unassigning cause I spend enough time and still can't figure why. Maybe someone else can try it

**Comment by noeliaSD** [comment]
What happens here is that when `SIGNAL_COMMUNITIES_UPDATE` is emited, `communityEdited(..)` method in `module.nim` is called and that method creates a new community item instead of updating the existing one and the new item active property is set by default to false (see `createCommunityItem(..)` method). So, when `setActiveSection(..)` in `section_model.nim` is called (when user clicks to another section from ui), the community section that suposed to be active is not so, no `dataChanged(..)` need to be raised. 

Same issue happens when editing, for example, the community name since `communityEdited(..)` method is called (new community item created and set as active false).

In order to fix that, `active` property value in `createCommunityItem(..)` has been set depending on if the current active section corresponds with the item we are going to create. However, I'm wondering if that `createCommunityItem(..)` should be renamed to `updateCommunityItem(..)` and instead of creating a new item instance, it should be necessary to modify the existing one with the new values.
