### ISSUE TITLE
re-add to master: fix: make changing local nicknames of contacts work again

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4687]
cdd79a87e7a944b8aaf5b8e677198b33574fd5f7

**Comment by saledjenic** [comment]
@iurimatias I am closing this since it's already fixed in the `master` branch (actually was in the old `base_bc`, [here](https://github.com/status-im/status-desktop/pull/4452)) in a more improved way than it was before and here is a [video](https://drive.google.com/file/d/1ED_tL5E2y7QbzrkGwI9PPxnoaAPgzw4j/view?usp=sharing), now all user's updates (name, image, identicon) are visible all over the app including messages itself either a user is mentioned in or sender of a message.
