### ISSUE TITLE
re-add to master: fix(@desktop/communities): Close popup when edit is successful

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4711]
0b1538c805d24462f53841a5047198603fa80e36

**Comment by saledjenic** [comment]
@iurimatias I am closing this, since this feature is already in the `master` branch, but for me this is not that intuitive cause we're opening another popup, just for the purpose of editing community details, from the already opened popup which is a complete "community overview popup", and once we click a "save" to store new community details expected behavior would be to get back to the "community overview popup" instead of closing both popups. If you agree we may open new issue and solve in a more intuitive way?
