### ISSUE TITLE
investigate new translation process

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#4759]

**Comment by jrainville** [comment]
The goal is to find if we can use Lokalise straight up for both the TS and JSON files at the same time and the translations and de-duplicated. this link seems to say we can use different keys and it will match them based on text, which is good, but we need to test if it works with different file types: https://docs.lokalise.com/en/articles/1400512-merging-existing-ios-and-android-keys

Another option proposed by @osmaczko is to create scripts that convert from and to JSON with the mobile JSON files and the desktop TS files.

**Comment by jrainville** [comment]
Awesome! Thanks for the investigation @osmaczko

I think you can update the translation docs with your findings and once it is done, we can close this issue.

cc @hesterbruikman and @jinhojang6 Seems like the translation process can be merged in Lokalise 🙌

**Comment by osmaczko** [comment]
> I think you can update the translation docs with your findings and once it is done, we can close this issue.

@jrainville updated, please take a look: https://github.com/status-im/status-desktop/pull/5327/commits/c8048ed573359aa29ab0a85e4ad57eec105b6cfa

**Comment by jinhojang6** [comment]
One thing to note is, if we'd like to automatically update Lokalise reflecting our repos containing .ts files, we need to create another project Lokalise. It would result in making a lot of duplicates and confusion for the translators so I think we'd better avoid it.

**Comment by osmaczko** [comment]
As @jinhojang6 mentioned, Lokalise can only be connected to a single repo. There is a webhook that reflects all the files from [status-react translations](https://github.com/status-im/status-react/tree/develop/translations), these files get updated (manually) periodically with new translations from Lokalise. That implies Desktop .ts files can't be reflected via webhook in the current Lokalise project. One of the options is to [create a separate Lokalise project for Desktop translations only](https://github.com/status-im/status-desktop/issues/4759#issuecomment-1124807142), but it's not really an option, because Mobile and Desktop are supposed to share many same translatable strings and we expect translations for them to be exactly the same. The second option is to convert .ts files via script to .json and keep only one [status-react translations](https://github.com/status-im/status-react/tree/develop/translations) repo, as shown [here](https://github.com/status-im/status-desktop/issues/4759#issuecomment-1032689043).

In order to get around the above and take advantage of Lokalise multiplatform translations support and avoid custom scripting we should consider:
a) creating separate repo for all platforms, that is: status-im/status-clients-translations which will contain both .ts and .json files (still merging the keys requires manual action I believe)
b) making the process of updating .ts files and merging keys manual, as described here: https://github.com/status-im/status-desktop/blob/6c2b2aa2846400f7afcc98777c8e800d99ca8cc6/I18N.md#tldr

I and @jinhojang6 both prefer option a)

CC: @jrainville @hesterbruikman @John-44

**Comment by hesterbruikman** [comment]
@osmaczko @jinhojang6 if anything to exlcude this option: Can platform keys be used? This would mean assigning each key to a platform. Upon export all keys assigned to a platform can be exported to json or ts, depending on export settings.

If not, then for sure a seems like the best option. Next to the manual effort, b will be error prone.

![Screenshot 2022-05-13 120300](https://user-images.githubusercontent.com/35233054/168261618-a38b671a-0afb-4679-9b3d-c72098a17c59.png)

**Comment by osmaczko** [comment]
@hesterbruikman not sure I understand how it relates to the discussion how to handle repos :thinking: option a) would still require platform keys to be used in order to export .ts and .json files after translation

if you update .ts and .json files, the keys are per platform by default, as mentioned [here](https://github.com/status-im/status-desktop/issues/4759#issuecomment-1118719336):
> 3. Export translated files .ts and .json (Lokalise is smart enough to keep original keys per platform)

**Comment by anastasiyaig** [comment]
@iurimatias @osmaczko what do we want to do with this task? can we close it? nothing to be tested here, no need to keep it in Code Review and QA column

**Comment by osmaczko** [comment]
This task is investigation, it's not testable. 

It is still ongoing due to new opportunities discovered on Lokalise. It seems we can configure different repositories for the same Lokalise project, so https://github.com/status-im/status-desktop/issues/4759#issuecomment-1124807142 is not relevant anymore. For some reason automatic translation files update doesn't work for status-desktop repository, we are waiting for response from Lokalise support team.

**Comment by osmaczko** [comment]
Translation process described [here](https://github.com/status-im/status-desktop/blob/8cb1a6471be3ae3db107cd664a2f54f6be9d067a/I18N.md).
