### ISSUE TITLE
The app is crashed after sending GIF to a group chat

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5263]
# Bug Report

## Steps to reproduce
1. Launch the app
2. Sign in with some user that has at least 2 contacts
3. Create a group chat with 2 contacts and send a gif image to this chat

#### Expected behavior
The gif image is sent successfully and the app is not crashed
#### Actual behavior
The app is crashed

https://user-images.githubusercontent.com/14942081/160758353-7b6ebf2d-0a03-4c4b-89b8-461c9378d46f.mov

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/commit/591a5bdf34cb2ad161e6cb4e59ecaf6c039abb2e
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

**Comment by iurimatias** [comment]
the chat input should be hidden completly in this case

**Comment by saledjenic** [comment]
> the chat input should be hidden completly in this case

@iurimatias this comment is somehow vague to me... when you're saying "in this case" that means we should hide chat input field in case of sending gif only, right? 

But at the moment of selecting users we don't know what action a user is going to take. At the beginning chat input is hidden and we display it when there is at least a single contact selected. Also that's how it should be by design, or maybe you meant to hide "gif" button only from the chat input?

@iurimatias while waiting for your answer I will try to fix that crash.

**Comment by saledjenic** [comment]
@iurimatias I've found the root cause of this issue and fixed it. 

Let me know if what you meant with your comment from above, do I need to remove chat input completely or just disable "gif" popup or all is good now since I fixed the crash?
