### ISSUE TITLE
Upload profile picture screen has empty circle

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#5322]
### Description

https://user-images.githubusercontent.com/82375995/166874980-e01cfb69-8d5f-45b9-992c-18020e06dca1.mov

1. open status - settings - profile - click pencil icon under the avatar
2. open status - online indicator - view my profile - click pencil icon under the avatar

**As result,** there is no default userpic on editing screen for the avatar rather than grey placeholder

<img width="1512" alt="Screenshot 2022-04-04 at 12 18 59" src="https://user-images.githubusercontent.com/82375995/161513922-5227da82-abe4-4adc-a500-375c75b67fc7.png">

**Expected**: Profile picture screen should have some default value when having no custom user picture set before. For example, we can use the same picture we have with letters and identicon ring, as we use during onboarding and in settings

<img width="1484" alt="Screenshot 2022-05-05 at 09 55 49" src="https://user-images.githubusercontent.com/82375995/166875407-37516e2e-75c3-4236-8707-7eb9f7776580.png">

**Comment by endulab** [comment]
I am pausing with this one. There is already #5241 which may fix this issue.

**Comment by John-44** [comment]
@endulab @anastasiyaig see designs here https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1116%3A107637

The profile picture dialogue should never be empty, because the user picks the image they want to crop *before* the dialogue opens.  This is detailed in the flow in the figma linked above.

Also the image cropping dialogue shown in the screencast has a number of issues:
- layout doesn't match the design
- the mask on top of the image is missing
- the zoom slider is missing

However @stefandunca has been working on this image panning, zooming and cropping tool.  So if @stefandunca 's image cropping dialogue isn't being used here, then it should be used here, and if there are any issues they should be fixed in the image cropping tool dialogue because this dialogue is used in multiple places.  

![2022-05-10 11_40_21-⚙️ Settings _ Desktop – Figma](https://user-images.githubusercontent.com/22846356/167611549-06c82d0f-bfeb-43b3-a659-4fe9fd820d4e.png)

**Comment by stefandunca** [comment]
> 

The base work along with its usage in the Onboarding is in the following PR; it didn't get much attention though: https://github.com/status-im/status-desktop/pull/5631
As soon as it is merged I will use the dialogue to fix this issue and assign it to me.

**Comment by endulab** [comment]
@stefandunca +1

**Comment by stefandunca** [comment]
Closing as dupplicate. Planned to be fixed in: https://github.com/status-im/status-desktop/issues/5814
