### ISSUE TITLE
In the featured chats, the users find the chats they already joined

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#5548]
# Bug Report

## Steps to reproduce
1. Sign in and on the Chat screen click on any chat in the Featured chats section
2. Click on the same chat in the Featured chats section

#### Expected behavior
If user joined the public chat, it will disappear from the featured chats
#### Actual behavior
Nothing happens, in the logs the error appears:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/14942081/163310858-686f5ccb-7679-4c39-9443-360ba9e36d4b.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/14942081/163310895-01330a7f-85dd-4b49-b20d-5a89c628a371.png">

### Additional Information

- Status desktop version: commit 31728940c4d8efd0b9b8c4c6ed22801dde8c3309
- Operating System: MacOS Big Sur, v. 11.6.6 (20G604)

**Comment by John-44** [comment]
I would treat this issue as very low priority, because we are going to be ripping the whole public chat functionality out of the product as soon as Communities is ready.  So I don't think it's worth investing effort in anything that will only benefit the public chat functionality, because public chats will be removed soon (and then this issue goes away).
