### ISSUE TITLE
speed up after password step

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5678]
### Description

Currently for a new user, when they finalize the password step, we show a loading icon and the user is blocked. To improve this experience we should immediatly go to the next step and perform this step in the background.

**Comment by alexandraB99** [comment]
@iurimatias I didn't create this issue because basically we need to block the user for these seconds until the account is created, the profile image is stored and the main module is loaded, otherwise, we'll take the user directly to the biometrics screen and if the user presses any of the options to login there, they won't be able to load the application.

**Comment by iurimatias** [comment]
already done in https://github.com/status-im/status-desktop/pull/6616
