### ISSUE TITLE
feature: autojoin group when mutual contact

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5717]
### Description

Current: when a user is added to a group, they receive an invitation and have to accept or reject

New Behaviour: 
- when a user is added to a group they automatically join, ~~if and only if they are mutual contacts~~
- only mutual contacts can be added to a group

**Comment by osmaczko** [comment]
"We should 100% remove explicit join.  When somebody is added to an ad-hoc group chat, they should immediately be landed in the group chat. No need for the user to explicitly join, or perform any other action.  This is possible because of mutual contacts, only mutual contacts can be added to an ad-hoc group chat. If somebody is not a mutual contact, they cannot be added to an ad-hoc group chat. No exceptions" @John-44
