### ISSUE TITLE
adapt view for settings as shown during account generation

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#5725]
Currently in wallet we segregate the accounts derived from default account and imported seed phrase.

it looks like this https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=5248%3A188675\

However it should look something like this https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1869%3A134081

**Comment by carlfairclough** [comment]
Ok so first of all I think it's important to frame what the user **might be** doing in both of these situations

Settings:
 - As a user I want to rename my accounts
 - As a user I want to modify my emoji / color
 - As a user I want to disable my account
 - **As a user I want to find out which accounts are related to one another**
 
 Add account
 - As a user I want to add an account
 - As a user I want to add an account using another private key/seed phrase
 - **As a user I want to add another account account using a private key/seed phrase I have already used**
 - As a user I want to add an account using a specific private key
 - As a user...
 
 With this in mind, we need to approach the views with different information-architecture
 
 
 
 ## Viewing account
 
 The accounts themselves are most important, so are used to navigate.
 The keys/phrases are effectively metadata.
 
```mermaid

flowchart LR
    A1[Account 1]
    A2[Account 2]
    A3[Account 3]
    A4[Account 4]
    K1[Key 1]
    K2[Key 2]
    
    A1 --> K1
    A2 --> K2
    A3 --> K1
    A4 --> K1    
```


 ## Adding account
 
 The key/phrase used to generate the account is most important, and used to navigate.
 The accounts derived from these are supporting metadata in lieu of labelling/naming.


```mermaid

flowchart LR
    A1[Account 1]
    A2[Account 2]
    A3[Account 3]
    A4[Account 4]
    K1[Key 1]
    K2[Key 2]
    
    K1 --> A1
    K2 --> A2
    K1 --> A3
    K1 --> A4    
```

## Proposed changes

Rather than mirroring the list format, I propose that we introduce `Related accounts` into the account view, alongside the derivation path. This allows the user to at a glance see which accounts are related

<img width="841" alt="image" src="https://user-images.githubusercontent.com/4670881/179222087-825c1154-3515-43ea-a1db-0f00d6716bd5.png">

https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/branch/G1GVE21KLEWwBwT1uK6IIh/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1009%3A108126

### In the future

In the future the user may want to migrate the account to another location, and we should cover those flows from here (e.g. `Moving Account 1 to keycard, will also move Account 3 and 4`). At that point, the origin of these accounts becomes very important
