### ISSUE TITLE
member list is empty when joining a community one is not an admin of [no membership requirement only]

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#5770]
# Bug Report

## Steps to reproduce

1. in client A: create a community and invite user from client B
2. in client B: accept invite and join community

result:

member list if empty

![Screen Shot 2022-05-16 at 3 46 58 PM](https://user-images.githubusercontent.com/176720/168680205-860f9a6a-497e-40ba-9b3a-fb5ff460f50f.png)

**Comment by anastasiyaig** [comment]
@saledjenic https://github.com/status-im/status-desktop/issues/5729

**Comment by alaibe** [comment]
I confirm, members list are displayed correctly for me too

**Comment by saledjenic** [comment]
Since I was not able to reproduce issue with an empty members list here, I fixed the issue with duplicated channels. Though It was very hidden, it's fixed now on a global level, so this fix might fix some other issues as well.

The whole confusion comes from the moment when we introduced channel groups, since then we have a mixture in `chatId`, in some cases `chatId` is just id in other cases it is composed as a combination of `communityId`+`chatId` and we had inconsistency because of that. Seems that all community calls returns `chatId` as simple id, but all other calls, including signals coming from status-go use combined `chatId`.

**Comment by John-44** [comment]
All Status Communities should have the members bar.  it should not matter if the community is an open or closed community

**Comment by elina2015** [comment]
Tested on the latest master and it's not reproduced now.


![Image](https://user-images.githubusercontent.com/14942081/168957753-95b1f161-cc24-4812-a2ec-bf5ea104b4a3.png)

**Comment by iurimatias** [comment]
closing since this ticket is in the 'done' state
