### ISSUE TITLE
[Chat] The current user should not be visible in the members list 

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#5894]
### Description
As per desktop designs the user themselves isn't featured in the member list and should be removed.

**Comment by John-44** [comment]
instead of this, how about we basically copy exactly what Discord does - if the user is in an ad-hoc group chat a crown icon is displayed next to their name, and if the user is in a Community they are featured in the members list but they don't have a (you) or anything else by their name.

Here is a design for how the crown could appear next to the name of the admin of an ad-hoc group chat https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=8214%3A414813

Just removing the "(you)" would also solve the original layout issue that sparked this conversation.  @alexandraB99  sorry for the flipflop!

![2022-05-26 11_41_30-Kuba⎜Desktop – Figma](https://user-images.githubusercontent.com/22846356/170473254-740b907e-566e-48d5-a1a1-7a471ce48907.png)

**Comment by iurimatias** [comment]
https://github.com/status-im/status-desktop/issues/5897
