### ISSUE TITLE
Squish-Jenkins Pipeline Integration

### ISSUE THREAD

**Issue by OlufemiAdeOlusile** [status-im/status-desktop#5960]
### Description

We want to have squish running in Jenkins
Currently, we can do this via the squish Jenkins Plugin
But only on a Linux service.

This is acceptable as we want to be able to have squish as part 
of our pipeline process when we commit new code, the test job should run.

https://doc.froglogic.com/squish/latest/ao-hudson.html

**Comment by alaibe** [comment]
After test, one squish server can run one test suite at a time

**Comment by alaibe** [comment]
A few notes:
- Python3 needs to be set when installing the license
We need to be able to run the app like a "normal user" as such:
- GLIB needs to be installed where we run squishserver
- QT needs to be installed where we run squishserver
- X server is required for squishserver
- libpulse-mainloop-glib0 needs to be installed where we run squishserver

In order to run the app on ubuntu we need to set LD_LIBRARY_PATH correctly

**Comment by alaibe** [comment]
https://www.froglogic.com/blog/tip-of-the-week/headless-execution-of-gui-tests-with-jenkins/
