### ISSUE TITLE
Intermittent with community invites

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#6170]
# Bug Report

## Description

This is intermittent, doesn't happen often but did happen to some ppl during dogfooding:

- [ ] Users requested to join, but requests don't show to community admin, until app restart
- [ ] Users added to community but community doesn't show until they restart the app

**Comment by saledjenic** [comment]
@anastasiyaig @Hbouaz [here](https://github.com/status-im/status-desktop/pull/6180#issue-1278431966) you can see that I fixed some related issues, but that may/may not fix this issue since I was not able to reproduce it at all. Please give a try and share details/steps how to reproduce it if you manage to do that.
