### ISSUE TITLE
In-chat search result message doesn't navigate to itself when clicked

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#6318]
https://user-images.githubusercontent.com/33099791/176768681-6e114019-5913-4a6a-a44c-b932eaf6d912.mp4

#### Expected behavior
When search result message is clicked the app navigates to the message.

#### Actual behavior
When search result message is clicked nothing happens besides the popup being closed.

### Additional Information

- Status desktop version: beta 0.6.0
- Operating System: Ubutnu

**Comment by saledjenic** [comment]
@osmaczko I was trying to reproduce this issue, for new users it works fine, then I used one of my old accounts and you may see in the video (check the size of vertical scroll bar) that a messages I was searching for were not loaded in the moment I was searching for them, and as you may see that works fine as well. A message, from the list of messages which match the pattern, which I selected was highlighted when I was pointed to it.

@osmaczko @anastasiyaig any suggestions how to reproduce this? Are you able to reproduce this again? Or if you have `Status` folder this issue is reproducible with, may you share it?

https://user-images.githubusercontent.com/86303051/178485346-15b3e891-e5f8-4a33-9e00-f5e7edd4bcbd.mov

**Comment by elina2015** [comment]
Tested on the latest [master ](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2316/)and the bug is not reproduced.
