### ISSUE TITLE
Seedphrase input requires two <TAB> key hits to jump to the next input 

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#6328]
Small thing but still annoying and unexpected.
When importing a seed phrase:
![Screenshot from 2022-07-01 16-16-13](https://user-images.githubusercontent.com/445106/176911869-78590fd9-9882-4d99-bb37-ca3a1da6b941.png)

It takes **2** TAB key strokes to jump to the next input in the following cases:

1. When the input is empty ("Why would someone tab into the next input when the current one is empty" you ask? Great question.)
2. After pasting a seedphrase

"Back tabbing" ("SHIFT+TAB") works fine at all times though.

**Comment by caybro** [comment]
Imho TAB to the next one should be disabled when the current one is empty

**Comment by caybro** [comment]
Fair enough. Then I _guess_ the issue is that the keytab chain gets broken due to the page layout (GridLayout), or simply the auto-heuristics don't work here. In any case, it should be possible to specify the next/prev tabstop manually using `KeyNavigation` : https://doc.qt.io/qt-5/qml-qtquick-keynavigation.html
