### ISSUE TITLE
The scroll in the popup 'Terms of name registration' is shown while there is nothing to scroll

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6559]
# Bug Report

## Steps to reproduce
1. Enable Wallet in Settings-Advanced
2. Go to Settings-ENS usernames
3. Click Start - enter some free name - Next
4. Click 'Terms of name registration'

#### Actual behavior
1. The scrolling is shown while there is nothing to scroll
2. The text is overlapped by the scrollbar
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/14942081/180102411-be845a71-3f19-4aa5-8950-89ca56729314.png">

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2347/
- Operating System: macOS Monterey

**Comment by caybro** [comment]
@elina2015 can't reproduce any longer in master:

![Snímek obrazovky z 2022-07-25 10-55-44](https://user-images.githubusercontent.com/5377645/180738469-e98990b4-c4db-45b0-ab77-570205c57887.png)

Actually there is a scrollbar (since the text here doesn't fix the page height) but it looks completely different than yours

**Comment by caybro** [comment]
cannot reproduce
