### ISSUE TITLE
The Profile Name field is jumping while typing a text there

### ISSUE THREAD

**Issue by elina2015** [status-im/status-desktop#6676]
# Bug Report

## Steps to reproduce
1. Go to Sign up a new account
2. On the onboarding 'Your Profile' page start to type some text (more than 4 characters) in the field 'Display name'

#### Expected behavior
After typing the first 5 characters the field 'Display Name' is **not** jumping up because the error notification disappeared
#### Actual behavior
After typing the first 5 characters the field 'Display Name' is jumping up because of the error notification disappeared
### Additional Information

https://user-images.githubusercontent.com/14942081/181407635-d68f6328-b3f3-4dfe-97bd-028d2bc07f69.mov

- Status desktop version: https://ci.status.im/job/status-desktop/job/master/15/
- Operating System: macOS Monterey 12.3 Beta (21E5227a)

**Comment by faust4exe** [comment]
Cannot reproduce on Linux on master branch with commit b43d773a579a1ebc903a7fb9a511245b2e844748

https://user-images.githubusercontent.com/6445843/182406362-af96ac35-272c-476b-8369-50a592e45c83.mp4

**Comment by elina2015** [comment]
@faust4exe I tested on the latest master https://ci.status.im/job/status-desktop/job/master/20/ and the bug is stably reproduced. Could you kindly check?

**Comment by faust4exe** [comment]
@elina2015 if I go via your link it mentions that build is made from master commit db4ec6430ea6641eecb0cfc95766c1f3e8ed870c and it is like 14 commits before the change I suspect made corrections to this behavior. Can you do a fresher build which will includes this commit 8af4e765c9dbe5598f707e75936d97e91902b3fa ? By the way I also got confirmation from other dev that on MacOS the issue is not present in commit I mentioned earlier.

**Comment by elina2015** [comment]
Tested on the latest master and it's not reproduced
