### ISSUE TITLE
Create a backup copy of a Keycard

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#7035]
This issue refers to the `Create a backup copy of a Keycard` flow, which starts here:
https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=7258%3A188522

Part of Keycard settings part which is the epic tracked under https://github.com/status-im/status-desktop/issues/4920

Criteria covered by this issue:

### Stage 1. 

Select option to backup

**- Attaching keycard**

1. If reader is not attached show Plug in card reader. 
2. If reader is attached and card is not inserted show insert keycard
3. If reader is removed… 

**- Invalid keycard**

1. If inserted card is not a keycard show - This is not a keycard modal
2. If inserted card is not linked to account - Wrong keycard inserted
3. If inserted card is empty - Keycard is empty
4. If inserted card is locked - Keycard locked

**- Keycard recognised**
 
1. Enter PIN
2. Invalid PIN - Factory reset
3. Invalid PIN - Locked after 3 attempts

- Accounts on this keycard
- Extended accounts on this keycard

### Stage 2.

- Remove card
- Insert empty keycard
- Reading keycard

1. Is it a keycard
2. Is it a different card
3. Is card locked

**Route A**
1. Is keycard empty.
2. Copy keycard to insterted card
3. Enter seed phrase
4. Valid seed phase
5. Copying keycard
6. Keycard is now a copy.

**Route B**
####  - keycard not empty
1. enter pin - > factory reset
2. wrong pin -> locked after 3 tries
3. Pin verified

#### - keycard known by profile
1. accounts on this card
2. Factory reset are you sure
3. Yes sure
4. Factory resetting
5. keycard has been reset.

#### -  keycard not known
1. accounts on card
2. I understand
3. Factory resetting
4. keycard reset

**Comment by glitchminer** [comment]
@saledjenic, I have updated the issue with what I think is covered going on the linked Figma. Please can you confirm if this is correct based on the work you've done? Thanks

**Comment by saledjenic** [comment]
@glitchminer looks ok, but this is still overall criteria (what we want to have actually) without getting into and describing all possible states you may ran into from a certain screen (that depends a lot on the Keycard's state). 

- for almost all states before `Accounts on this keycard` (like `Insert this Keycard...`, `Reading Keycard...`, ...) we should display keypair at the bottom of those states even before we actually enter the pin and get the info what's really stored on a Keycard (we can do that, cause we're running into this flow from the card specific page, so we know which Keycard, containing which keypair we're asking user for)
- `Extended accounts on this keycard` - this term doesn't exist and after entering the pin, you will get a list of accounts stored on a keycard, that's all, so it's enough to say `Accounts on this keycard`

**Comment by glitchminer** [comment]
### Issues found

---
#### 1. CLOSED Modal not using assigned display name
Confirmed with @saledjenic that future development is scheduled for this

![image](https://user-images.githubusercontent.com/50769329/204616987-4aa74b41-6d47-465e-86f0-8fc14a4f11ed.png)

---
#### 2. OPEN Figma suggests that user is directed back to Insert this keycard… modal
![image](https://user-images.githubusercontent.com/50769329/204617319-6ad952c0-09a3-4472-b2e7-464f41ed7d5d.png)

A way for the user to be returned to the "insert this keycard" modal was not found.

---
#### 3. OPEN Try inserting another keycard button does not perform any action
It was only possible to cancel.

![image](https://user-images.githubusercontent.com/50769329/204617776-a89c6e5f-33ba-4dac-a34b-3d0c458fb7d9.png)
![image](https://user-images.githubusercontent.com/50769329/204617871-71942270-bb1e-4560-98a7-ac76a6b5aad7.png)

---
#### 4. CLOSED Creating a copy of a copy is not possible
Confirmed that this will be covered under https://github.com/status-im/status-desktop/issues/8136

---
#### 5. OPEN Wording on This keycard already stores keys modal
Figma reads "To migrate..." instead of "To copy..."
![image](https://user-images.githubusercontent.com/50769329/204620275-03dda638-665c-4080-a503-c1c82936b562.png)

---
#### 6. OPEN Keycard locked and already stores keys does not match Figma
If the card being copied to is already locked Figma has a flow that goes straight to Keycard locked https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=7258%3A187459&t=fT7INtOJGMypfzuz-4

In the app the route taken is Keycard already stores keys then goes to Keycard loced and already stores keys, which is not defined in Figma.
![image](https://user-images.githubusercontent.com/50769329/204623215-ee4c90c9-7d78-457a-ac16-6e5613218d46.png)


---
#### 5. OBSERVATION Keycard registered with account after factory reset
Perhaps not directly related to this issue but Keycards listed will be stuck in unlocked state or simply not useable if, for example, a keycard is locked and then factory reset.
