### ISSUE TITLE
Chat - Cannot send messages to unblocked user

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7127]
# Bug Report

## Description

After unblocking a user it is not possible to send them messages

## Steps to reproduce

1. Have a 1 to 1 chat with two users
2. User 1 blocks user 2
3. User 1 unblocks user 2
4. User 1 can now receive messages from user 2 but not send them.

#### Expected behavior

After unblocking, both users can message each other.

#### Actual behavior

https://user-images.githubusercontent.com/50769329/186411216-2cd55951-47a5-4e15-803b-dadd3999e7d4.mp4

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-220824-111243-1c7719.dmg
- Operating System: Mac

**Comment by osmaczko** [comment]
Update:
- it happens only for 1on1 chats, on public chats messages are received correctly
- if "a-tester" restarts the app, then messages "message 6", "message 8" appears, but still, new 1on1 messages from "b-tester" are not received at runtime

**Comment by osmaczko** [comment]
Found the root cause. When `b-tester` blocks user `a-tester`, then `a-tester` is no longer a contact to `b-tester` (that's very strange, cause block user action should be only local to `b-tester`, apparently it isn't). Messages don't appear anymore, because in nim-status-client we [ignore messages from non-contacts](https://github.com/status-im/status-desktop/blob/b5e317db4dc702c7de742d07d55dc9e38bcd56bf/src/app_service/service/message/service.nim#L182-L184).


https://user-images.githubusercontent.com/33099791/198040519-1cb5cabf-d5f2-43e2-a361-1d1662086b77.mp4

**Comment by osmaczko** [comment]
I've just spoken with @John-44. The requirement is: "We don't want the person who is blocked to know they've been blocked.". The block action should not be propagated.

**Comment by jrainville** [comment]
Ok yeah that makes sense. You can probably fix that in status-go
