### ISSUE TITLE
Keycard: User's display name is filled incorrectly for account created with keycard

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7336]
### Description

3 - words name is pasted to user profile display name when account is created with keycard. Also this name does not bypass the validation

<img width="1562" alt="Screenshot 2022-09-13 at 16 49 23" src="https://user-images.githubusercontent.com/82375995/189918962-4882e4f9-cb73-4bb2-90e5-132f1c851823.png">

**Comment by glitchminer** [comment]
Still present in https://github.com/status-im/status-desktop/pull/7350

**Comment by saledjenic** [comment]
@glitchminer @anastasiyaig maybe I was not clear in my previous comment. 
The thing I fixed referred to the user which is migrated to a Keycard via `Settings -> Keycard -> Setup a new Keycard with an existing account`, in that case after app restart if user logs in using keycard in correct display name will be set.

In case you're adding a new user either selecting `Add an existing Status user` from the login screen or following the flow `I already use Status -> Login with Keycard` there is no chance at the moment to know anything about display name since that name is not stored on the Keycard. If we're discussing that it's not only that, but many other things are missing in that case apart of display name, like added wallet accounts, contacts, chats, communities and so on... so that way we're not restoring an account even it should be like that. All that will be in place once we have the mechanism built for fetching all those details from the waku, but as far as I know this is still WIP. 

That's why the following 2 flows are completely incorrect (they do not follow the correct pat which is in figma):
- login using keycard, starting here: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=13777%3A462665
- login using seed phrase, starting here: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=13653%3A452959

**Comment by alaibe** [comment]
I am marking this one as done just because we haven;t yet work on that part yet.

This should be handle by the syncing mechanism
