### ISSUE TITLE
Start chat - group members To: field behavior

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7340]
# Bug Report

## Description

While a level of key functionality has been achieved a number of items could be improved but depend on clarification of the expected behaviour.

## Steps to reproduce

---
#### 1. FIXED After resizing, horizontal scrollbar on members bar does not adjust until bar is in focus
Actual
![2022-09-08_18-08-20 (1)](https://user-images.githubusercontent.com/50769329/189183837-2b379938-a283-4082-919c-6d65d7d81e0e.gif)

---
#### 2. OPEN Can no longer scroll horizontally using trackpad or horizontal (secondary) scrollwheel
While it is now possible to reach all members of the group using a horizontal scrollbar, it is no longer possible to do so using trackpad gestures or horizontal scrollwheel. 

---
#### 3. N/A Not possible to use arrow keys to navigate between members
While it is now possible to reach all members of the group, it is not possible to navigate between users in the field using cursor keys or to remove a user with backspace or delete keys.

---
#### 4. FIXED Admin pill missing from member list when starting chat
Expected
![image](https://user-images.githubusercontent.com/50769329/189401086-e5f4a0a3-3f86-4130-aca1-b7c10ed2ed70.png)

Previously it was confirmed that the admin pill would be present when starting a group chat, but @osmaczko has identified some reasons not to do this. Confirmation also required on whether or not admin pill would be present when starting 1-1 chat.

---
#### 5. FIXED When the 20th user is added the user limit message overlaps the remove button of the final pill
Actual
![2022-09-08_20-02-39 (1)](https://user-images.githubusercontent.com/50769329/189205597-ec370872-b8ba-4713-8d82-107cf81cf235.gif)

---
### Additional Information

- Status desktop version: Found during testing of https://github.com/status-im/status-desktop/pull/7188
- Operating System: Mac

**Comment by alexandraB99** [comment]
@glitchminer in regards to the issue points:

From the above list:
1. DONE
2. I can scroll with trackpad currently, please check again
3. This is not a regression, it was never supported. I would see it more like a feature, nevertheless we need to think if we really want to add it because the tags currently are not part of the input thus the cursor cannot just go inside those. It would need bigger effort to be fixed.
4. DONE
5. DONE

**Comment by alexandraB99** [comment]
@glitchminer in regards to the issue points:

From the above list:
1. DONE
2. I can scroll with trackpad currently, please check again
3. This is not a regression, it was never supported. I would see it more like a feature, nevertheless we need to think if we really want to add it because the tags currently are not part of the input thus the cursor cannot just go inside those. It would need bigger effort to be fixed.
4. DONE
5. DONE

**Comment by osmaczko** [comment]
@alexandraB99 point 4 hasn't been discussed with John yet, that's a good reminder.
