### ISSUE TITLE
Onboarding: create password view still has wrong font-size

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7447]
Here's what the create password view looks like:

![Screenshot from 2022-09-20 13-08-57](https://user-images.githubusercontent.com/445106/191242961-178de859-0781-492e-a9f2-4f9c91542f77.png)

Here's what the password confirmation screen looks like:

![Screenshot from 2022-09-20 13-09-11](https://user-images.githubusercontent.com/445106/191242997-181bdf2a-80f8-40fa-b724-76ccb538a9f4.png)

Notice how on the first screen the text in the view is smaller and has a smaller line height as well.
This is only the case for this particular view in the onboarding which is why it stands out quite a bit.

**Comment by noeliaSD** [comment]
The application follows current designs on figma here:  https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1042%3A300574

So, asking the design team, @benjthayer, to give their input here, please.

**Comment by benjthayer** [comment]
Thanks @noeliaSD - having reviewed the designs, while there is inconsistency in pt size between the screens - that inconsistency seems to be intentional. The confirmation screen purposefully uses a larger pt size and extended leading to add impact and drive user attention in order to ensure that the user notes down their password given Status can not assist in it's recovery.  We could look to finesse this screen but would need to do so taking the entire flow and rest of app into consideration.

**Comment by PascalPrecht** [comment]
>  The confirmation screen purposefully uses a larger pt size and extended leading to add impact and drive user attention in order to ensure that the user notes down their password given Status can not assist in it's recovery.

@benjthayer Notice that **all** onboarding screens, even before entering a password have the bigger font-size, except that one view where the password needs to be entered twice. This does look like UI bug to me

**Comment by PascalPrecht** [comment]
Just checked the designs as well, and indeed the one view has a smaller font-size there too.
It feels weird to be very honest. But if that is really intentional.... well then that's what it is.

I thought it'd be better if we're consistent everywhere. Every time I go through the onboarding flow, the smaller font size throws me off a bit.

Maybe it's just me. Feel free to ignore this issue then @noeliaSD

**Comment by benjthayer** [comment]
@PascalPrecht I agree, the sudden change in pt size without any additional treatment feels a little odd. I can see what the designer has done - one uses caption text, the other body and logically that makes sense given what is trying to be achieved in each but there is certainly some finessing that could be done. I'd personally be in favour of using the 15pt body throughout the create password flow as the design is generally spacious but feels very condensed in those screens. Given I'm fairly new to the team, it would be best to discuss such changes with @John-44 before proceeding.

**Comment by noeliaSD** [comment]
@PascalPrecht your view is also understandable, that's why I've asked the design team! I will keep it open until @John-44 answers something!

**Comment by benjthayer** [comment]
Here are a couple of explorations we could explore which align the pt size of the copy below the header of each page - it also aligns the first form element and the lower continue button. I would be in favor of something like this. There is an argument that the copy at the top of both pages is important so better to use the body pt size rather than the caption. Caption is more appropriate for the copy relating to password strength. @PascalPrecht @noeliaSD 

 <img width="1232" alt="🚧Create a password-1" src="https://user-images.githubusercontent.com/110033914/194026966-12ac5cd1-170e-43e4-9608-05b4172d71c1.png">
<img width="1232" alt="🚧Create a password" src="https://user-images.githubusercontent.com/110033914/194026970-126d3c1f-eb00-4543-85c4-c2d82a5aeb4b.png">
