### ISSUE TITLE
View Profile from contact request shows "send contact request" not "accept request"

### ISSUE THREAD

**Issue by Khushboo-dev-cpp** [status-im/status-desktop#7476]
# Bug Report

## Description

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/60327365/191540865-13131fbf-840d-4280-93db-664a312f9d4a.png">

## Steps to reproduce

From the contact request notification open the popup for the requests
click on more and then click on "view profile"

#### Expected behavior
Should see "accept request" button on the popup

#### Actual behavior
user sees the "send contact request" button

### Additional Information

- Status desktop version:
- Operating System:

**Comment by John-44** [comment]
The profile shown in this issue screenshot is the old profile dialogue, this should be fixed in the context of the new profile dialogue designs shown here https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?node-id=2%3A10

Also don't forget the user states in the context dialogues, as they use the same state from the profile dialogues https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1657%3A184346

**Comment by micieslak** [comment]
It will be resolved along with the new profile dialog issue: https://github.com/status-im/status-desktop/issues/7360
