### ISSUE TITLE
After re-joining community channels are empty

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#7512]
# Bug Report

## Description

After re-joining community channels are empty
## Steps to reproduce

1) join community
2) leave community
3) join community

#### Expected behavior
channels are **not** empty

#### Actual behavior
channels are empty

---

https://user-images.githubusercontent.com/33099791/191760524-0f0021bc-f77f-428e-8b77-d323778d9508.mp4

**Comment by iurimatias** [comment]
I believe this might be the classic that certain channels are marked as fetched, so rejoining them doesn't refetch

**Comment by jrainville** [comment]
Alright, so indeed it's a mix of fetching not being triggered + we delete the chat and messages from the DB when we leave.

The fetch is easy to fix.

Having the messages still in the DB would help a  lot though, since otherwise we need to rely on the store nodes and they are not super reliable and are way slower. I tested removing the message deletion and it worked.

@cammellos what would you suggest in this case? When a user leaves a community, could we keep the old messages in the DB? Maybe only the last X messages so when we rejoin it doesn't look empty? Or it's better to delete?

**Comment by cammellos** [comment]
@jrainville I think either are fine,
The only thing that it might be a bit jarring for the user if we keep old messages is that it might look like there are no new messages if you join again, unless we explicitly show that we are fetching messages, if the community is empty is a bit clearer that messages are being fetched, but I think either ways is fine.
