### ISSUE TITLE
enable featured communities with wakuconnect

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7534]
### Description

note: apparently there is code for this already but if not we'll need to do it using https://wakuconnect.dev/

- [x] deploy Directory and Voting contract to optimism goerli
- ~~update DApp's dependencies (js-waku, usedapp, etc.)~~ moved to https://github.com/status-im/community-dapp/issues
- [x] #9662
- ~~status-go: implement featured communities service with voting counting logic~~ (not relevant anymore)
- [x] #10565

**Comment by John-44** [comment]
original author of the code confirmed it's there in Discord chat

**Comment by osmaczko** [comment]
[Community directory curator dApp for Status](https://github.com/status-im/status-community-dapp) can't connect to peers, see image:
![image](https://user-images.githubusercontent.com/33099791/203587281-cd624896-75a7-4afa-8a8f-0318ce832ac2.png)

The dapp is not compatible anymore with the fleet because it is using a super old js-waku. Updating js-waku to latest is non trivial as the API has changed and the documentation has not been updated.

**Comment by fryorcraken** [comment]
@John-44 as stated by @osmaczko, the js-waku library should be updated to a more recent version. js-waku@0.30.0 should be good enough.

If you encounter any problem once it's updated, please open an issue on the js-waku repo and I can look at it.

What is your timeline? We are revamping js-waku docs so it will be easier to update once our docs are up to date.

**Comment by felicio** [comment]
WIP: https://github.com/status-im/status-community-dapp/pull/1

**Comment by felicio** [comment]
@osmaczko you should no longer be blocked by the `js-waku` update. Please, see the pull request above and once you hook up the contract and have some data to work with I could help you further.

Also, going forward

1. @iurimatias would you make the repo public or at least accessible to all internally?
2. @osmaczko could you update desktop's QtWebEngine (browser)?
3. consider bootstrapping with `status` fleet instead of `wakuv2`
4. consider replacing `setInterval(get, 10000)` for Filter protocol and use Store only on initial load
5. consider encrypting votes
6. handle connection failures and disconnects

Cc @John-44

**Comment by anastasiyaig** [comment]
@jrainville @iurimatias what is the state of it?

**Comment by osmaczko** [comment]
Waits for https://github.com/status-im/community-dapp/issues/2
