### ISSUE TITLE
text input is displayed when choosing contacts for new chat

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7706]
## Description

The chat input is displayed, and typing something and then pressing enter doesn't do anything. The behaviour should be to either open the chat when a message is sent or to not display the chat input. This should be confirmed in the design.

<img width="1043" alt="Screen Shot 2022-10-02 at 8 07 01 PM" src="https://user-images.githubusercontent.com/176720/193482576-ff7f63cd-3bf1-4651-93c2-a77ce17e7921.png">

**Comment by benjthayer** [comment]
@noeliaSD @John-44 
When the user is adding/removing contacts to the chat, the UI is in a modal state given they have to confirm/reject before proceeding. If we didnt have the confirm/reject controls, we could simply dismiss the list of contacts when the user re-focused the chat input - allowing them to send the message - this feels a little more intuitive.

However, if we want to retain the confirm/reject controls, we need to inform the user somehow that they can't proceed until they have selected either confirm or reject. The best way I can see to do that is to put the chat bar into a disabled (but still visible state). The user may want to review their message while they choose the recipient so I think its better to show it in a disabled state than to hide it altogether.

Those are just my thoughts! It would definitely be worth getting a consensus with others before proceeding to ensure there are no issues with that solution.

The only issue with this solution I can see is that the user cannot simultaneously be editing the message and selecting recipients at the same time. However, the user can always go back and change the recipient list at any time during their writing/editing of the message so that may be a non-issue.

**Comment by noeliaSD** [comment]
> @noeliaSD @John-44 When the user is adding/removing contacts to the chat, the UI is in a modal state given they have to confirm/reject before proceeding. If we didnt have the confirm/reject controls, we could simply dismiss the list of contacts when the user re-focused the chat input - allowing them to send the message - this feels a little more intuitive.
> 
> However, if we want to retain the confirm/reject controls, we need to inform the user somehow that they can't proceed until they have selected either confirm or reject. The best way I can see to do that is to put the chat bar into a disabled (but still visible state). The user may want to review their message while they choose the recipient so I think its better to show it in a disabled state than to hide it altogether.
> 
> Those are just my thoughts! It would definitely be worth getting a consensus with others before proceeding to ensure there are no issues with that solution.
> 
> The only issue with this solution I can see is that the user cannot simultaneously be editing the message and selecting recipients at the same time. However, the user can always go back and change the recipient list at any time during their writing/editing of the message so that may be a non-issue.

Thank you for your feedback @benjthayer ! 

Waitting confirmation from @John-44 to disable `chatinput` when we are editing chat members.

**Comment by benjthayer** [comment]
This was discussed briefly at the Istanbul offsite - the final decision was to put the chat bar into a disabled (but still visible state), allowing the user to review their message at the same time as choosing the recipient/s. cc @John-44

**Comment by benjthayer** [comment]
After review with John, the final decision was to implement the original design intent.

That is: when a user types their message, hitting enter, should automatically create the chat and send the message to the recipients currently in the To: field. When doing so, the 'To' input field and Confirm/Reject buttons should be removed.

It is not necessary to disable the input. The user hitting enter on the message is effectively them confirming the current state of the recipient/members and sending the message.

The only time the user cannot send a message is when they have not yet selected their first member/recipient - which makes sense as you have no-one to send the message to yet.
