### ISSUE TITLE
Invalid PIN saved to keychain when enabling biometrics on account using keycard

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-desktop#7729]
# Bug Report

## Description

It is possible to set up biometrics with a different PIN to that used for a Keycard. If this is done attempting to log in using TouchId results in an invalid PIN error.

![image](https://user-images.githubusercontent.com/50769329/193687852-56952cad-0cfe-47b7-bac4-b8a88a7427e1.png)
![image](https://user-images.githubusercontent.com/50769329/193690239-5407177d-3d17-4186-b1de-673ee7255326.png)

## Steps to reproduce

1. Generate seed phrase for keycard
2. Select "I prefer to use my PIN" instead of enabling TouchId
3. Go into settings and enable biometrics
4. Set PIN to different value than Keycard
5. Log out and attempt to log in using TouchId

#### Expected behavior

1. Enabling Biometrics after setup should store correct pin to keychain

#### Actual behavior

2. Invalid pin stored on keychain

### Additional Information

- Status desktop version: 0.7 rc1 (dogfooding)
- Operating System: Mac

**Comment by saledjenic** [comment]
@anastasiyaig is this something still applicable? I've tried and somehow see that togging `Biometric login and transaction authentication` is somehow broken. Also not sure if we need to allow keychain pin change from the profile settings at all, but even if we want to allow this, a keycard on which a profile keypair is stored on must be present, and also we need to run the change pin flow in that case.

Also there is a new option coming to my mind now... that we can ask user to store pin to a keychain if user is changing a pin for a keycard where profile keypair is migrated. But in that case what should we do if user has more than one keycard for his profile keypair and each keycard has a different pin?!?!

**Comment by saledjenic** [comment]
@glitchminer please check this one and let me know it you can reproduce it?

**Comment by anastasiyaig** [comment]
@glitchminer could u please check this one today?

**Comment by glitchminer** [comment]
@glitchminer @saledjenic this bug is still valid in 0.9-RC5.

Steps to reproduce:

1. Create new account: Generate seed phrase for keycard
2. At the prompt, select "I prefer to use my PIN" instead of enabling TouchId
3. Go into profile settings and enable biometrics toggle
4. Click on save
5. The user is then prompted to set a PIN. This can be different to the PIN set for the keycard
6. Log out and attempt to log in using TouchId. If the PIN set in the previous step is different to the keycard then using touch id will count as a failed PIN attempt.

**Comment by John-44** [comment]
> But in that case what should we do if user has more than one keycard for his profile keypair and each keycard has a different pin?!?!

@saledjenic only the pin linked to a 'profile' keycard should be stored in the secure enclave and unlocked by biometrics.  

Regarding the case where the user has duplicated a  keycard, if they go to change the pin on one of the duplicated keycards perhaps we should amend the flow so that they are prompted to insert their 2nd keycard so the pin on the 2nd keycard is changed at the same time.  Of course we can't force the user to do this, so they can still end up in the situation where they have different PINs on each keycard, but this would at least reduce the incidence of this happening.

At the end of the day, we can't prevent the user entering a wrong pin (inc. doing this via biometrics).  After a user uses biometrics to unlock a keycard PIN and if fails, we should then switch biometrics off and prompt the user to manually enter the correct pin.  I think we have flows designed for this.

Sorry, this isn't a complete answer.  Perhaps something we should discuss?

**Comment by saledjenic** [comment]
@glitchminer I found one more issue while I was working on this and it was here most likely form the beginning. The following scenario:
- user switch on biometrics and enter a correct password
- keychain popup appears 
- user doesn't approve storing to a keychain, but cancels everything

as a result of this user gets nothing stored to the keychain, but the biometrics toggle is on, what is wrong. That's fixed now.

Also user is able to store only the correct pin now.

Instead of that ugly popup we had before, authentication popup is used in both cases (for regular and for keycard user) for this activity now.
