### ISSUE TITLE
Reply-to-messages sometimes don't show up

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#7754]
Look at this screenshot:

![Screenshot from 2022-10-05 10-23-20](https://user-images.githubusercontent.com/445106/194015226-0bfb5871-5b0f-4567-9bb6-2d8a2dcec463.png)

See how I'm replying to a few messages which don't seem to be around (there's a blue circle which indicates there's no information to render).

I think there's a few things that should be explored here:

1. First of all, if we have a case where we render a reply-to-message component, but the actual information seems to be missing (like in the screenshot above), we should probably show at least a text or something that says something like "Message couldn't be loaded"
2. Still need to investigate the core issue here, but my assumption is that, given that we only load the last 20 messages when entering a channel the first time (after bootstrap), the reply-to-messages are simply not available in memory yet. Maybe we need to tweak the message querying that we, despite a limit of 20, still add all reply-to-messages regardless

**Comment by jrainville** [comment]
I mostly fixed the issue here, but there is one thing I found that I need info before going ahead. (Draft PR https://github.com/status-im/status-desktop/pull/8886)

I think I found a bug with message deletion + replies in status-go. Basically, if you reply to a message, and that original message is deleted, if you then restart the app, we still get the `QuotedMessage` as the original message, nothing about it being deleted. What this creates is a situation where the original message is no longer showed in the message list, but the reply still shows that message. I assume this is a bug, but maybe we want to keep the context of the reply? @cammellos @John-44

**Comment by John-44** [comment]
@jrainville If a message is deleted, any replies to that message should (instead of showing the original message message text above the reply) show "Message deleted" as the original message text above the reply.

**Comment by cammellos** [comment]
> I mostly fixed the issue here, but there is one thing I found that I need info before going ahead. (Draft PR #8886)
> 
> I think I found a bug with message deletion + replies in status-go. Basically, if you reply to a message, and that original message is deleted, if you then restart the app, we still get the `QuotedMessage` as the original message, nothing about it being deleted. What this creates is a situation where the original message is no longer showed in the message list, but the reply still shows that message. I assume this is a bug, but maybe we want to keep the context of the reply? @cammellos @John-44

Yes, as John mentioned, once you delete a message, replies as well should be gone
