### ISSUE TITLE
can't see contact request from removed user

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7791]
# Bug Report

## Steps to reproduce

1. add a mutual contact, have other one accept
2. restart app
3. remove the contact (while the other contact doesn't do anything)
4. have contact send verification request

result: contact request is received
expected result: contact should not be able to send a verification request in the first place

5. restart app

result: cannot see contact request anymore

6. go to settings -> messaging contacts

result: cannot see contact request

**Comment by jrainville** [comment]
I tried this and even though I fixed a small issue, I don't see, with our current signals, a way to fix the 4th point.

The reason is that we don't send a signal when we remove the contact. I'm guessing this is for privacy?

Should we change that or leave it as is? The user A (the one that removed the contact) doesn't receive a request, this was already fixed in master. cc @iurimatias @John-44 @cammellos

**Comment by cammellos** [comment]
> I tried this and even though I fixed a small issue, I don't see, with our current signals, a way to fix the 4th point.
> 
> The reason is that we don't send a signal when we remove the contact. I'm guessing this is for privacy?
> 
> Should we change that or leave it as is? The user A (the one that removed the contact) doesn't receive a request, this was already fixed in master. cc @iurimatias @John-44 @cammellos

We should have that feature, you should use the `RetractContactRequest` endpoint, and that should notify the other end, could you try please?

**Comment by jrainville** [comment]
Oh perfect. I'll try right away. Thanks

**Comment by jrainville** [comment]
@cammellos thanks, it worked
