### ISSUE TITLE
Add CI script to prevent StatusQ having dependencies to status-desktop

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#7854]
### Description

When `StatusQ` was a submodule it was physically impossible to make dependencies to `status-dekstop`. Post integration[ it is easy and tempting](https://github.com/status-im/status-desktop/pull/7517#discussion_r978567425) to make the dependency bidirectional, making the concept of `StatusQ` pointless.

It comes from the scope of: https://github.com/status-im/status-desktop/issues/7548 - the solution proposal is there as well.

### Possible solution
- add CI check that validates StatusQ builds (and runs) successfully in Release mode. The release version takes resources from `StatusQ/*`, making it impossible to use anything from the parent directory.

UPDATE:
The ticket has been split into two parts:
1. https://github.com/status-im/status-desktop/issues/8071 - utility app for checking imports
2. This one - adding CI script

**Comment by micieslak** [comment]
Maybe I'm missing something, but I have a notion that we didn't lose anything when it comes to control over `StatusQ` dependencies when merging into `status-desktop`.

For example let's take `StatusColorSelector.qml`. If we add import from `status-desktop`, e.g. `import utils 1.0` it can be easily unnoticed (now and before merge as well) because:
   - when used in `status-desktop` the import is just available
   - `sandbox` in general will work, because pages are loaded on demand from source code files. Only if given page uses improper import directly or indirectly, there will be an error written to the console out, e.g. (`module "utils" is not installed`). But even when broken page is chosen, the app will continue to work and won't exit with the error code.
   - `sandbox` would exit immediately with error code only when component with improper import is used directly by `sandbox` application, e.g. `StatusButton`. It's not applicable to components accessed in pages, as discribed above.
   - the library itself is not compiled to any form of library, so it's not possible to check anything when compiling - there is no compilation
  
Any of those circumstances changed after merging `StatusQ` to `status-desktop` so there is a problem with effective detection of improper dependencies but the merge itself didn't introduce any regression.

The only reasonable approach that comes to my mind now is to have at least very basic qml (even just only importing components) unit tests for all components provided by that library.

@osmaczko @caybro @alexandraB99 Please verify and share your thoughts :)

**Comment by micieslak** [comment]
Similar story with imports like `../../../StatusQ/src/Components`, it was also possible to overlook it before, bc people had `StatusQ` configured from `status-desktop` tree (not as a standalone clone) for convenience. But this case is very obvious, hard to overlook when writing and during code review, I hope.

**Comment by osmaczko** [comment]
> Maybe I'm missing something, but I have a notion that we didn't lose anything when it comes to control over StatusQ dependencies when merging into status-desktop.

We lost the physical boundary, now it is tempting to use files from the parent directory. It is not an accident that the first dependency to status-desktop was created after StatusQ was moved.

> - when used in status-desktop the import is just available

That's true but some (most?) ppl were using StatusQ as a standalone repository. The chance to spot not loading pages or not running Sandbox was high, now it is easy to miss, cause everyone is running Sandbox from status-desktop.

> - sandbox in general will work, because pages are loaded on demand from source code files...
>
> - sandbox would exit immediately with error code only when component with improper import is used directly by sandbox application...

That's also true. The first point I didn't take into consideration and that makes the proposed solution incomplete. Nevertheless proposed solution would catch some of the issues, for example:
```
diff --git a/ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml b/ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml
index abb20d6b4..a2073b0ee 100644
--- a/ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml
+++ b/ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml
@@ -7,6 +7,8 @@ import StatusQ.Core 0.1
 import StatusQ.Core.Theme 0.1
 import StatusQ.Controls 0.1
 
+import utils 1.0 as SD
+
 /*!
      \qmltype StatusTagSelector
      \inherits Item

```
```
$ ./Sandbox
QQmlApplicationEngine failed to load component
qrc:/main.qml:516:13: Type DemoApp unavailable
qrc:/DemoApp.qml:193:9: Type StatusAppChatView unavailable
qrc:/demoapp/StatusAppChatView.qml:260:13: Type CreateChatView unavailable
qrc:/demoapp/CreateChatView.qml:25:9: Type StatusTagSelector unavailable
qrc:/StatusQ/Components/StatusTagSelector.qml:10:1: module "utils" is not installed
```

> the library itself is not compiled to any form of library, so it's not possible to check anything when compiling - there is no compilation

Of course, compiling is not enough, we need to run the app and scan the error code.

> The only reasonable approach that comes to my mind now is to have at least very basic qml (even just only importing components) unit tests for all components provided by that library.

The solution I believe that requires the least manual work is to load every page statically, through the main component. It could look like this:

main.qml
```
StatusWindow {
    SanityCheck {}
    ...
}
```

SanityCheck.qml
```
Item {
    visible: false
    
    StatusAccountsSelectorPage {}
    StatusAddressPage {}
    ...
    
    Buttons {}
    Controls {}
    ...
}
```

Or even create `SanityCheck.qml` as a root component of a separate application which we will compile and run on CI to see if there is no dependency to status-desktop. We can even go one step further and write a script that generates `SanityCheck.qml`.

**Comment by osmaczko** [comment]
Ok, please forget about the last proposal. I figured out something much easier and more generic. We need a script that iterates through `ui/StatusQ/src/*.qml` files and runs them through qmlscene.

Example:
- StatusTagSelector.qml with proper imports runs ok
```
$ qmlscene -I src src/StatusQ/Components/StatusTagSelector.qml
file:///home/osmaczny/Dev/status/status-desktop/ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml:210: TypeError: Cannot read property 'count' of undefined
```
- StatusTagSelector.qml with `import utils 1.0 as SD` exits immediately
```
$ qmlscene -I src src/StatusQ/Components/StatusTagSelector.qml
file:///home/osmaczny/Dev/status/status-desktop/ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml:10 module "utils" is not installed
```

- StatusTagSelector.qml with `import "../../../../imports/utils"` exits immediately (although this may run without an issue in some cases, that is, when imported stuff e.g. "utils" does not depend on modules - this is super unlikely and we can take that risk I guess)
```
$ qmlscene -I src src/StatusQ/Components/StatusTagSelector.qml
file:///home/osmaczny/Dev/status/status-desktop/ui/StatusQ/src/StatusQ/Components/StatusTagSelector.qml:-1 Type Utils unavailable
file:///home/osmaczny/Dev/status/status-desktop/ui/imports/utils/Utils.qml:5 module "shared" is not installed
```

**Comment by micieslak** [comment]
Nice try, but SortFilterProxyModel is breaking that idea :(
