### ISSUE TITLE
Community -> Recovered account: community that user has left, is recovered in new installation

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#7858]
### Description

1. create a community
2. make sure u are still admin :)
3. back up your seed phrase
4. leave the community
5. recover the account again from scratch

As result, the community is shown again in the list, even the user has left the community

**Comment by igor-sirotin** [comment]
As discussed with @saledjenic, postponing this issue until https://github.com/status-im/status-desktop/issues/8315

**Comment by iurimatias** [comment]
moved to 2.29 due to lack of space in this milestone

**Comment by jrainville** [comment]
In theory, you can't leave a community if you are the owner, but it's worth checking still that if you leave the community, it doesn't show up again, since you can leave once you transfer the owner token.

IMO, hacking the UI to make the Leave Community button show and testing that way should be good, unless we have a block on the backend that doesn't let us leave, but I doubt it.
