### ISSUE TITLE
Wallet -> Keycard: can't create accounts if the main account was restored in using an existing keycard account

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-desktop#7867]
## Steps to reproduce

Follow the onboarding process and restore an existing keycard account

1. I already use Status
2. Login with Keycard
3. Enable Wallet
4. Click Add Account, fill in the data and authenticate using card
5. Click Add Account

#### Expected behaviour

6. The new generated account is added to the list of wallet accounts

#### Actual behavior

7. Nothing happens, card is 

### Additional Information

- Status desktop version: `de2c421b5e7e1a88fe08953ac2ab7a68197beb4a`
- Operating System: MacOS

**Comment by saledjenic** [comment]
@stefandunca it should be `FlowType.FirstRunOldUserKeycardImport`, you will run into that, after running the app, if you follow the steps `I already use Status` -> `Login with Keycard`, that flow is the same one as if you follow `I already use Status` -> `Enter a seed phrase`, and that is here from the beginning, from the very first start. Initially that flow (not the keycard one, cause it came later and relay on what we had in that moment) was wrongly implemented, also that flow requires synchronization in order to work correctly. I was warning few times about it.

All in all we can not easily fix that, that requires a lot of additional things to be sync correctly, but lot of them are not ready/developed yet.
