### ISSUE TITLE
Delete channel is not propagated to members

### ISSUE THREAD

**Issue by endulab** [status-im/status-desktop#8000]
Member of the community does not see that the channel was deleted by the admin.

Technical details:
The chat, which is deleted, is still in member's database.
status-go should remove the chat automatically.
What is strange, community nim service receives community with correct number of chats by status_go.getJoinedComunities()
Probably correct action should be handled in messenger_communities.go:: handleCommunityDescription() - see line 1477 and comment "Currently removal is not supported".
Need to discuss this fix with mobile team.

**Comment by PascalPrecht** [comment]
Investigated this.
So turns out this is properly propagated and also updated in the community member's database.
The problem is that:

a) we don't handle chat removals in desktop, so they don't disappear at runtime, even though they've been removed
b) we don't remove the chats from the chats table in the database, which is why they would still show up after restart, even if 1) wouldn't apply

I'll send a PR to fix this.

**Comment by PascalPrecht** [comment]
Here's a fix in status-go https://github.com/status-im/status-go/pull/2973
Will send a PR that addresses proper removal in desktop
