### ISSUE TITLE
Remove system tag usage for contacts and rely on contact request state enum instead

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#8183]
As a follow up to #8179 we should not be relying on system tags to figure out a contact's (request) state.
The linked PR introduces the `ContactRequestState` enum which should be relied on instead.

So this task is about removing the usage/dependence on `hasAddedUs`, `added`, etc and replace them with corresponding `ContactRequestState` values.

**Comment by PascalPrecht** [comment]
As mentioned in https://github.com/status-im/status-desktop/pull/8179#issuecomment-1310406647 this needs clarification from UX/UI.

In desktop, changing to exclusively using ContactRequestState will cause "breaking" UI changes (re-sent contact requests won't show up anymore because the requestState will not be updated if it was dismissed/rejected once).

Need to check if this is desired.

**Comment by PascalPrecht** [comment]
Putting this on backlog for now

**Comment by jrainville** [comment]
Do we still use those system tags @MishkaRogachev ? Should we close this?

**Comment by MishkaRogachev** [comment]
> Do we still use those system tags @MishkaRogachev ? Should we close this?

We can close it, here is the pr fixing that: https://github.com/status-im/status-desktop/pull/10613
