### ISSUE TITLE
Chat -> Communities: Message replies are sometimes not shown in chat

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#8216]
Take a look at the screenshot below:

![Screenshot from 2022-11-14 10-09-38](https://user-images.githubusercontent.com/445106/201620280-5391db16-128b-4128-a250-0a2c27c060f3.png)

The first message "Yeah I get the same" is a message I've replied to.
However, that reply does not show up for me in the chat.

See my other messages where I say "I just replied to..." 
There should be a message reply to @jrainville 's "Yeah I get the same" message.

This is something I've experienced a few times already. Sometimes, when replying to messages, my message with the reply doesn't show up in the chat. There were times where they did show up for others though. So it's likely a local problem.

**Comment by anastasiyaig** [comment]
I can see your reply @PascalPrecht when being on master from 14-nov-2022, commit e8b9760c4ffcad99cf4df7e4e278ef732332ad48

<img width="682" alt="image" src="https://user-images.githubusercontent.com/82375995/201627393-77d7d2d4-66bd-4e50-abbd-aeae498cf3b2.png">

**Comment by PascalPrecht** [comment]
Given that other users do see my reply, this seems to be a UI issue.

**Comment by John-44** [comment]
I run into this issue quite frequently.  I post a reply to a message, and after posting I can't see my reply, but everybody else can see my reply.

Could we increase the priority of this issue to critical because it makes the chat functionality feel unreliable?  Also (if possible) could a fix for this issue go into the final 0.8 release that we will be pushing out on the 1st December?

**Comment by jrainville** [comment]
This should be fixed by https://github.com/status-im/status-desktop/pull/8275

Try latest master or RC4.
