### ISSUE TITLE
parallelize squish tests

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#8317]
### Description

We need to parallelize the squish tests in the CI to use the various execution licenses available

**Comment by jrainville** [comment]
See the throttle option here https://github.com/status-im/status-desktop/blob/master/ci/Jenkinsfile.uitests#L33-L39

**Comment by jakubgs** [comment]
Waaaaait, do we have the new licenses? I don't recall us installing them.

**Comment by alaibe** [comment]
@jakubgs I have been ping today that we have new licenses, 10 in total. Do u need something to install them?

**Comment by jakubgs** [comment]
Yes, this is not automatic. This is Squish, why would you expect anything to just work?

**Comment by jakubgs** [comment]
I have updated the `node-01.do-ams3.squish.ci` server with the new config that has more licenses:
```
ExecutionLicenses=10
TesterLicenses=10
```
It should work now:
```
admin@node-01.do-ams3.squish.ci:/docker/squish % grep licenses /var/log/docker/squish-server/docker.log
2022-12-05T20:15:20.306 Info: Starting licenseserver 6.7.2
2022-12-05T20:15:20.309 Info: Serving 10 tester and 10 execution licenses on TCP port 49345
```

**Comment by alaibe** [comment]
Is it enough, to have only 1 machine updated? That could cause problem if two machine run the test while having the old license?

**Comment by jakubgs** [comment]
Why do you think the second one should be updated?

**Comment by jakubgs** [comment]
To clarify some confusion here based on questions from @alaibe in Status:

There are two types of servers here:
 
* CI servers that run CI jobs/builds, managed by Jenkins. Example: `linux-01.he-eu-hel1.ci.devel`
  - These hosts have a [Squish runner package installed](https://github.com/status-im/infra-ci/tree/master/ansible/roles/squish-runner).
  - They have a [license server address configured](https://github.com/status-im/infra-ci/blob/7b32da22e798bdd98187a7fecb2d8f52f9cd9daf/ansible/group_vars/ci-slave-linux.yml#L7).
  - They do NOT have a Squish license server config.
* Squish License server(s), which should be just one, but two exist. Example: `node-01.do-ams3.squish.ci`
  - The second server only exists because Squish people were too lazy to combine licenses when issuing them.
  - These servers have the [license config deployed](https://github.com/status-im/infra-ci/tree/master/ansible/roles/squish-license-server) based on what FrogLogic provided us with.
  - The new license config combines both execution and tester licenses, 10 of each.
  - Second server should not and will not exist in the future once Squish answers why they did not delete it.
