### ISSUE TITLE
[Community Permissions] Add reactions switch in `New permission` page

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#8501]
### Description
Add reactions switch in `New permission` page:

![Screenshot 2022-11-29 at 15 11 51](https://user-images.githubusercontent.com/97019400/204552022-646e016d-2b98-4125-815c-b86f1e0b5535.png)

Here figma file: 
https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=21127%3A480834&t=A6nq8f7QhOYqGI9Z-0

**Comment by noeliaSD** [comment]
It will also need design [here](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2934%3A484715&t=Gdr5HhtgLtoUYkE3-0) to reflect this permision option since as you can see in the following screenshot, the user cannot see if he/she has reactions permission or not:
![Screenshot 2022-11-29 at 15 18 11](https://user-images.githubusercontent.com/97019400/204553259-0f3d3eb0-7316-4a17-b6b6-c04a964b7b14.png)

@pedro-et could you provide a design for this? Thanks

**Comment by noeliaSD** [comment]
Once we have the design, it will be also necessary to add the new design in `Permissions` page, so, create a separate task or just do it also here.

**Comment by John-44** [comment]
@noeliaSD @pedro-et this issue should be closed because the ability for users with 'view only' permissions to react to a message should be set at channel level, not at permissions level.  e.g. a community owner or admin should be able to enable the ability for users with view only permissions to react to messages in a channel in the "Create new channel" and "Edit channel" dialogues.  @xAlisher has designs for this (and a new issue should be created for this)

**Comment by noeliaSD** [comment]
Closed bc of @John-44 comment and the design team @pedro-et @xAlisher will add a new issue when the new designs in `Create new channel` and `Edit channel`are ready.
