### ISSUE TITLE
[StatusChatInput] when pasting a text leading spaces are removed

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-desktop#8538]
expected
```
    |\__/,|   (`\
  _.|o o  |_   ) )
-(((---(((--------
```
actual
```
|__/,| (`.|o o | ) )
-(((---(((--------
```

**Comment by flexsurfer** [comment]
ok seems like its not only about leading spaces, discord removes leading spaces as well, but other part is better, in status it removes new line as well and leading spaces in the next lines
in discord it looks like 

```
|\__/,|   (`\
  _.|o o  |_   ) )
-(((---(((--------
```
so there are no leading spaces only the first line, bit overall it looks ok

**Comment by alexandraB99** [comment]
@benjthayer could you please give some input here? should we just follow up with what discord does?

**Comment by benjthayer** [comment]
I think we should definitely retain line breaks if we can as that would be expected behavior. Would need for @John-44 to confirm on retaining leading spaces. From a user perspective, again it feels like retaining those would be ideal - when I copy and paste something, I expect the pasted variant to be a carbon copy of the original. However, there may be some scenarios where removing leading spaces may be beneficial but I'm not sure what those would be.

**Comment by caybro** [comment]
This should be fixed with https://github.com/status-im/status-desktop/pull/8945

**Comment by alexandraB99** [comment]
Re-opened as is still pending confirmation from @John-44

**Comment by caybro** [comment]
> Also I can still see
> ```
> |__/,| (`.|o o | ) )
> -(((---(((--------
> ```

In latest master? It should be fixed already

**Comment by caybro** [comment]
Alright, I can still reproduce :/ This particular pasted text has underscores and a backtick, which results in the msg being interpreted and formatted (underline, code block). Different issue then, I'll unlink the PR

**Comment by iurimatias** [comment]
still an issue

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature
