### ISSUE TITLE
Activity center: message that was replied to, is missing

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#8710]
### Description

**Version:** `release candidate 8.1`

<img width="1748" alt="Screenshot 2022-12-09 at 13 31 27" src="https://user-images.githubusercontent.com/82375995/206683147-ba659741-0ceb-4c2b-9bc0-a22f94e42d66.png">

**Comment by 0x-r4bbit** [comment]
Seems to be a dupe of https://github.com/status-im/status-desktop/issues/8595

There's a commit in #8595 and the issue was closed due to non-reproducability.
Has this ever been proeprly fixed?

I think @MishkaRogachev mentioned once that this will be fixed with this AC work. Not sure if that has already landed

/cc'ing @jrainville has he closed  #8595

**Comment by caybro** [comment]
Seems to work for me in master:
![image](https://user-images.githubusercontent.com/5377645/206687375-444f0ee7-0798-448c-9f35-051ef4344fb0.png)

**Comment by anastasiyaig** [comment]
it works in master, we need to cherry pick to 8.1 , it is annoying

**Comment by 0x-r4bbit** [comment]
Thank you for verifying @anastasiyaig !
And yes, I agree.

**Comment by anastasiyaig** [comment]
It wont be cherry-picked because it is very hard to do for AC overall. Will be delivered in 0.9.0 (and is already fixed in master)
