### ISSUE TITLE
Message box buttons do not work in group chat creation screen

### ISSUE THREAD

**Issue by shamisem** [status-im/status-desktop#8730]
# Bug Report

## Description
If you're creating a group chat and want to use an emoji, GIF or sticker in your first message, you won't be able to do so as these buttons do not respond to clicks. Once the chat is created, all three buttons are back to working as expected.

If it helps, I remember this wasn't happening in the previous version of Status.

## Steps to reproduce

1. From the left sidebar, go to **Chat** (Messages).
2. Click **Start chat**.
3. Select two or more of your contacts.
4. In the message box, click the emoji (or GIF, or sticker) icon.

#### Expected behavior
An emoji (or GIF, or sticker) selection window appears.

#### Actual behavior
Nothing happens. All three buttons are hoverable, but none respond to clicking.

### Additional Information

- Status desktop version: 0.8.0
- Operating System: macOS Monterey 12.5 (21G72)

**Comment by caybro** [comment]
can't reproduce in master

**Comment by mprakhov** [comment]
After a quick look:
The issue is reproducible: you must add members but not create a chat.
But there is another problem: even if you'll send a simple message (which you can do) - chat will be created, but the message will not be added.

@jrainville should I fix only the message box buttons issue and register another bug with the first message for the chat which was not created at the moment of sending the message or take a look at both problems (buttons + first message)?
P.S. I would prefer to have a separate ticket as the scope of work for me unclear for the found problem

**Comment by jrainville** [comment]
To simplify the tracking and testing, I created a separate ticket here @mprakhov https://github.com/status-im/status-desktop/issues/8991
