### ISSUE TITLE
[Performance] Use the QML profiler and post data for analysis

### ISSUE THREAD

**Issue by alexandraB99** [status-im/status-desktop#8792]

**Comment by alexjba** [comment]
The profiler data can be found here:
https://drive.google.com/file/d/11pQq03484jgxaZs45L3yGIyc-yLU7kpK/view?usp=sharing

Here is the screen recoding of the steps taken in the app that leads to this profiler data:

https://user-images.githubusercontent.com/47811206/208410419-e2aeff22-640d-47ac-98dc-b3f985bfba9f.mov

**Comment by alexjba** [comment]
There are some initial observations in this data that could pose some interest in terms of QML performance.
1. General observation: nim access is slow even if we don't need to reach the network or database.

2. The first phase is the startup and login phase. Here things look ok and the QML execution is pretty fragmented. The only delay I could notice comes from qml Singletons bindings and creation(probably the Singletons try to reach the backend for some data and hence the delay).
Possible investigation -> Singleton creation and bindings used at startup

3. In the second phase the activity is moved in the backend. This is after user login action. The only activity in this phase is reevaluation of mainModuleInst and globalUtilsInst in Utils.qml. This should not happed as these modules are provided as root context even before loading main.qml.
Possible investigation -> Why the mainModuleInst and globalUtilsInst binding is reevaluated. Broken bindings in widely used nim modules could cascade into the app.

4. The third phase (and the most intensive) is the post login. 
Possible investigation -> pixmap caching error on lots of images. The caching process takes about 25 seconds and ends in error.
-> break the execution as much as possible into smaller tasks and free the main loop as often as it can in order to keep the app responsive (there are lots of js executions that take more than 0.5seconds. Ex: StatusNavBarTabButton.qml:50 is blocking the main thread for between 0.5 to 2.5 seconds, LanguageView.qml:71 for 0.7 sec)

**Comment by alexjba** [comment]
Looks like the pixmap cache errors are generated by wrong file extension. We try to load jpeg images with svg extensions:

qrc:/StatusQ/src/assets/img/icons/data:image/jpeg;base64,/9j/2wCEAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSgBBwcHCggKEwoKEygaFhooKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKP/AABEIAFAAUAMBIgACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AKZpjVIarX0y21rLMxUBFJyTgV0GBjeJ9aGk26rGhkuJchFHb3rgLi6bcbnUmuDKxyCen5Utncy3+ovcXlwGkY8A84/D0qrqNneahO5hTegOAyqMVxVKl3rsdUKbS0Ma/wBQkuJSxZsdulVvNk7kn3rufCXw71PWpf3kLQxd2YV02q/CKS0twyXiFsfdK4rF4inF2ubLD1Gr2PIzPwCetdF4b8UXNrcRw3MjT2zHGDyw+hqvrXhuexzvAwDjIrnjEY24OCK2hNPWLMJwadpI9vR1kRXU5VhkUprnPBGpNe6WI5WBlh+U/TtXRV2Rd1c52rHRGuZ+IOw+G5vM3feXbt7HPeumNUtVsotQsZrWcHZIMHHUUSV1YE7M4n4X+CLjxNeTtI5ht4cAnHJzzXvejfDHTbGFGkZpivY9K4H4DXC2dvqaXMiqElC72OM44r2i38SabJmKG5jkcDkKc4rwajlKo0+h7lJKMFbqJb6fBZWwSGMKoHYVxPi6UqWXv2rq/EviG207T2kZlAxXievePXubwrb2LSIM/MT/AErF03L4TWNRQ1kYniiHeNoXPBNeUagCl1IpGCGIxXoOqeJPNm3TWzRpnGQK4zxG0M96Z7YnY4+bIxg124ZSho0cWLlGeqZrfDuUrqc0fZ48/iK9Crivh/aeUZJZgqu4BQE84rta9Ok046HnVE09TojTGp9MNamZztstxYS3zQWeVZgSUPJcnnPoMYrQtPDfiC71eJnkijsnwQykhuevHWuk8LW7yarLtiSaOSPDxs2OexFd7tuo9PZLe0jtjtKiQtuIz6DGP1rxMS5RqOJ7WFUZU4yPEfGXhq5g0BNZm1OefE0kMcLklQgYqGyT14rJ8M+FRqenTieGZ5JMBWVgNo9q9N8fS6VaeE7SxWdJFhHlkA7sYHJNcT4N1zybpLK2vpEtmHysY1yD6cjNZurJrQ3VCCepjan4NmsAm6Flj3KuGbO7nP8ASsLxZap9jt1jQBhJjAHWvTPErlJAXmaZz0dnJ/IdB+Arj7+KORC8gzt+Yex9aiFaV02wqUY2aS3MjQCJb602go0eQw/CuxNYuhWKxzNPtIwMDPc9zWya9fBr93fueVjpXqcvZHQ0hpaa3Sus4y/4euxZ6tDISdp+U/jXZ654hg01Irm9YiFOi+przgnByOtdVYRWviG2t49QRZVhcM8bd8d/pXlZjSelVfM9PL6yV6bOO8Qxp4p1NpfIlWzQkhbePdvz7iuDutHvbO5kGn21ynPyg9RX0R4mspfsOdOuYbeMDJQJ2H0rhrw2Wn24mvLpp7hh8q4AUVwKq0tD0+SElfqcNE98unrHqn+uDYU55xgUy7G2ym9dhOfwp8sxurpm3ZGePanBA42v0Y4P0pRXvESehes1MdnArkFggyffFOapCAqhR0AwKiavpErHzm50WaaafGjyuEjVnc9FUZJresvBmt3iB1tDEp6GU7f060Npbjscw9bPhazu7q9D2+6OCMEzTY+VVAyc12Gi/DKV5Fk1e6VUByYouSfbNdbfabFP4Y1SDTkWCPymggCjgY7/AImsas04tLU0pxfMnseJ+MbvV9OuGilSQxk/u5F+6wrgby31DUJo5GVhEvAyelfQGlvFq+hW7TorNs2SKR0YcEfmDXDeJtKjgvCsCtjr7CvBjJR2R7zi5aNnDQ2y2cG0nLnqaguXKwuVJDAHBFbd1p74yelYupxGGFz7UJ3dxuNlYPDuoPf28glO548fN6j3rSNR+BNHa30aW6uFx9sciMH+6O/5ip5o2iYhhXu0KnMrPc8GtBRlof/Z.svg
