### ISSUE TITLE
[StatusChatInput] Undo hotkeys does not undo text formatting (bold/italic/etc)

### ISSUE THREAD

**Issue by mprakhov** [status-im/status-desktop#8819]
# Bug Report

## Description

If I select any text and want to make it bold/italic etc, and then decide to undo these changes, the left special symbol is not removed (need to undo twice)

## Steps to reproduce

1. Input any text
2. Select some word and make it bold/italic etc
3. Undo changes

#### Expected behavior

Bold/italic formatting is removed

#### Actual behavior

The special symbol from the left is not removed. Need to undo it twice

### Additional Information

- Status desktop version: 0.8.1
- Operating System: macos

https://user-images.githubusercontent.com/117639195/207888369-032c466d-9aeb-4544-a54f-ea0b6f7cdfe7.mov

**Comment by shinnok** [comment]
Here's what I found out so far:

# The problem

The culprit is that we can't do the word substitution (wrapping in **) in a single step, _atomically_. The current solution does:
https://github.com/status-im/status-desktop/blob/7d0d321b35e60f2c70c70d36ee32efc070bf2f40/ui/imports/shared/status/StatusChatInput.qml#L526-L527

Which in turn does `messageInputField.insert()` twice, for the prefix ** and the postfix **. This is registered as two edits by the `QTextEdit` undo history, thus when undo-ing via the `⌘+Z`, the need to press twice to undo what we perceive as a single action (pressing `⌘+B`).

# The solution?

In short, I couldn't find a workaround that behaves better than the current situation. Here's what I tried:

## Disabling the Undo history for a moment

There's no API for this. Trying to _disable_ the Undo tree, for the duration of the two step edit, via alternative means like `Control.enabled = false` or setting `readOnly` to true, does nothing or results in text artifacts.	 

```qml
     messageInputField.readOnly = true
     insertInTextInput(messageInputField.selectionStart, wrapWith);
     insertInTextInput(messageInputField.selectionEnd, wrapWith);
     messageInputField.readOnly = false
```

## Remove, then insert

This is the same behavior as the current implementation, only that instead of undoing each ** pair in turn, first `⌘+Z` press will undo the entire `**word**`, leaving _blank_ in instead and second press bring back `word` (without the wrapping **). I don't think it's better than the current implementation behavior (undoing each ** pair in turn).

```qml
       let selStart = messageInputField.selectionStart
       let word = messageInputField.selectedText
       messageInputField.remove(messageInputField.selectionStart, messageInputField.selectionEnd);
       messageInputField.insert(selStart, wrapWith + word + wrapWith);
       messageInputField.select(newSelectionStart, newSelectionEnd)
```

## Overwriting the entire text document

The last obvious thing to try, is to completely replace `TextEdit.text` with a version that has the substitution done outside the QML control interface.

```qml
        var unformattedText = messageInputField.getText(0, messageInputField.length)
        let word = messageInputField.selectedText
        var left = unformattedText.substring(0, messageInputField.selectionStart)
        var right = unformattedText.substring(messageInputField.selectionEnd, messageInputField.text.length)
        messageInputField.text = left + wrapWith + word +  wrapWith + right
        messageInputField.select(newSelectionStart, newSelectionEnd)
```

Unfortunately, assigning to `TextEdit.text` clears the entire Undo tree thus far, so history is not available anymore, pressing `⌘+Z` results in nothing.

# The conclusion

As I'm out of ideas to try around the limitation of the API (not being able to do this prefix/postfix substitution in a fell swoop), I'll put this on hold until I or somebody else comes with suggestions. Maybe @alexandraB99 can pitch in here or advertise this to extra 👀 .

**Comment by igor-sirotin** [comment]
I think this could be workarounded with clipboard.
1. Given that the text to wrap is selected:
1. Get the selected text
2. Wrap it as needed
3. Copy wrapped text to clipboard
4. Paste the wrapped text to text input

This I think will be a single history operation.

Though this will affect system clipboard content. But maybe this could be workarounded somehow?

**Comment by osmaczko** [comment]
> I think this could be done using clipboard.
> 
> 1. Given that the text to wrap is selected:
> 2. Get the selected text
> 3. Wrap it as needed
> 4. Copy wrapped text to clipboard
> 5. Paste the wrapped text to text input
> 
> This I think will be a single history operation.
> 
> Though this will affect system clipboard content. But maybe this could be workarounded somehow?

@igor-sirotin I think this is the same as "Overwriting the entire text document".

@shinnok thanks for investigation. I also don't see a way to solve that in easy way, given TextEdit doesn't provide API for atomic word substitution. The hard way would be to create extended TextEdit in C++ and implement it ourselves.

**Comment by igor-sirotin** [comment]
>  same as "Overwriting the entire text document"

@osmaczko, hmm, why is that?
We won't overwrite the `.text` property, only use `TextEdit`'s copy/paste methods. 
This should keep the actions history, like if you would manually select some text and then paste another text instead of selected.

**Comment by osmaczko** [comment]
> @osmaczko, hmm, why is that?
> We won't overwrite the `.text` property, only use `TextEdit`'s copy/paste methods.
> This should keep the actions history, like if you would manually select some text and then paste another text instead of selected.

Right, sorry, I misunderstood. TextEdit's paste() method is indeed a way to atomically substitute a word, I missed the paste is working on selections as well. That's still a massive workaround/hack.. :sweat_smile:

**Comment by jrainville** [comment]
@shinnok if you can, try Igor's suggestion. If it still doesn't work, I'll just remove this issue from you. The StatusChatInput can be quite annoying sometimes.

**Comment by caybro** [comment]
This is a tricky one... and as Patryk said, we'd most likely need our own custom C++ component; not only for this but would be also benefical for other replacements we are doing there atm (mentions, emoji, etc). All of those are also not handled properly when it comes to undo/redo

**Comment by igor-sirotin** [comment]
Just to mention again: 
copy/paste workaround will replace the existing clipboard content. This should also be taken into account.
A solution that would replace system clipboard content is not appropriate I think.

**Comment by jrainville** [comment]
FYI, I unassigned and "unprioritized". The solution is not simple enough to justify doing it now for such a small issue.

**Comment by iurimatias** [comment]
closing as this will be part of a wider rethink of this feature

**Comment by igor-sirotin** [comment]
@iurimatias I think it would be better to link those issues to the "wider rethink of this feature".
Otherwise we might forget about it when re-implementing the chat input.

**Comment by iurimatias** [comment]
That was done. All these issues were linked on close already
