### ISSUE TITLE
Enable copy messageID and envelopeHash on Debug mode

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-desktop#8863]
The messageID and envelopeHash are useful information for debugging message loss in WakuV2. 
Currently the process to obtain the message ID and the envelope hash is cumbersome as we need to go inside geth.log or inside the DB or temporarily modify the database to see the message ID

To solve this, the following changes must be done:
1. Modify status-go user_messages table to add a column to store the envelope hash
2. When inserting the message in the table in the message handler, insert also the envelope hash
3. The functions to retrieve messages should also return the envelope hash.
4. If DEBUG mode is enabled on desktop, in the context menu for the messages the following options must be added:
- Copy messageID
- Copy envelopeHash

cc: @cammellos for his feedback, in case he has concerns about storage use or privacy concerns due to storing the envelopeHash. Perhaps this is something that should be done only if debug mode is enabled?

**Comment by cammellos** [comment]
@richard-ramos I generally rather keep debug/production separate, so having it in the logs would be my preference rather than writing it in the database, for us in mobile logs are more accessible than databases, but I understand if that's really needed on desktop.

The envelope Hash that I saw being used is the `Sha256` of the `proto.Marshal(WakuMessage)`, is that correct?
if that's correct, the issue is that a single message could have multiple hashes, since it might be re-transmitted multiple times, refreshing the timestamp & therefore the hash, unless I am mistaking.
