### ISSUE TITLE
Clarify search behavior for multiple choice lists

### ISSUE THREAD

**Issue by micieslak** [status-im/status-desktop#8879]
## Description

Lists like those in provided examples always display selected items, even when search string is not matching. This behavior should be discussed and clarified. Adequate designs should be provided.

![Screenshot from 2022-12-21 21-14-54](https://user-images.githubusercontent.com/20650004/208999477-685cbce5-7dc1-4097-bd7d-e2f807b9d8e9.png)

![Screenshot from 2022-12-21 21-44-29](https://user-images.githubusercontent.com/20650004/208999523-45285d59-905c-43b3-9a35-ec67be20ba32.png)

**Comment by alexandraB99** [comment]
cc @benjthayer

**Comment by benjthayer** [comment]
Thanks @micieslak @alexandraB99 discussing with design team - will get back to you asap.

**Comment by micieslak** [comment]
> Hi @micieslak , @alexandraB99 confirmed with the design team that the following rules should apply to these components.
> 
> 1. Where there is a primary CTA such as 'Add', this should be augmented with the number of items selected if that CTA is directly related to the application/sending/submission etc of the selected items. So in the top component example, selecting a checklist item should result in +1 being appended to the 'Add' label.. For example, if the user selects 1 item, the button label should read 'Add 1'. The count on the button should increase/decrease based on checklist item selection/deselection. This is important as it clarifies to the user how many selections they currently have when some/all of those selections might be out of view due to scrolling of the list / searching.
> 2. Selected items should only be shown when the user is searching the list if there are matching strings in that value. If not, those selected items should be hidden until the search is changed to include matching strings or cleared.

Thanks @benjthayer for explanation. It applies nicely to the first screen I posted but it remains in contradiction to what we have for invite popup:

![Screenshot from 2023-05-11 12-10-25](https://github.com/status-im/status-desktop/assets/20650004/2a6c8668-cb28-4f01-b702-6613f7fe8f8d)

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=2990-353179&t=ZroCPZZNm3oxj8e2-0

According to the design, selected items are always visible in search results. Do we want to just remove them from search result? Should "Next" button contain some information how many items are selected?

**Comment by benjthayer** [comment]
Hi @micieslak yes in the above case `Invite Contacts to CryptoKitties` in order to be consistent, `simon` would not be present in the list as it does not contain a string matching that entered by the user. 

The next button wouldn't be augmented with the number of users selected on this occasion given the `Next` action doesn't directly relate to user selected. It just takes the user onwards in the jouney. I've edited those screens slightly to align to this.

<img width="1524" alt="Screenshot 2023-05-11 at 11 24 29" src="https://github.com/status-im/status-desktop/assets/110033914/4b43d83c-50cc-4acf-8578-dd78bd2fa73a">

https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?type=design&node-id=2927-344073&t=Os6iVseYwCZb4YRQ-4

Hope that sounds ok from your perspective and makes sense? :)
