### ISSUE TITLE
Chat history: Refactor LinksMessageView

### ISSUE THREAD

**Issue by alexjba** [status-im/status-desktop#9101]
### Description
This component is used in the MessageView delegate. This delegate needs to be as simple as possible and we need to avoid any backend calls when creating/binding the delegate.

LinksMessageView is doing a lot of data parsing and it's also calling the backend for extra information. The purpose of this task is to analyse the component and refactor it in order to achieve:

- [ ] Improved creation time
- [ ] Improved component design

**Comment by alexjba** [comment]
The main performance offenders found in this component is the `getSourceComponent` due to lots of data parsing and backend calls and the `onLinkPreviewDataWasReceived`. 
IMO @jrainville had a good idea here in how to improve the performance: https://github.com/status-im/status-desktop/pull/9031#discussion_r1066225191

Moving the entire data processing in the backend is definitely an improvement in both creation time and component design.

**Comment by mprakhov** [comment]
Suggestion: 
1. User sends a link
2. Message shows the link only
3. status-go do a validation and load image/gif in memory/temp folder
4. status-go returns the image in bytes or filename
5. signal to slot `onLinkPreviewDataWasReceived`
6. `onLinkPreviewDataWasReceived` unfurl the link
7. Message hide the link and show the image

**Comment by micieslak** [comment]
If moving js code to something more performant will improve performance, we probably should go this direction.
But I see several issues here.

Moving some ui-related logic to backend may hinder testability. Ideally we should be able to run UI components (separated components, more complex views and event the whole app). Therefore the backend should be limited to do only network-related operations and expose data to frontend in a possibly simple form. Then it's easy to mock that backend. If backend contains UI logic, mocking backend requires duplicating that logic to have UI components working without real backend.

So if some operations should be rewritten to something faster than js, imo we should consider moving it to C++ and keep it as a part of UI, independent from the backend (which could be limited mainly to networking then). If for any reason it's more beneficial to keep that logic in GO (e.g. for sharing with mobile client), maybe we should consider creating separate library for that. That library could be used also in UI's testing environment, with no need of mocking of this part.

@alexjba please let me know what you think about that. I'm not too much in the topic so I could easily miss something.

**Comment by alexjba** [comment]
@micieslak there is also this issue #9084 and @mprakhov suggested the status-go validation approach taking this into consideration. 
From my understanding (@mprakhov please correct me if I got it wrong) on status-go there will be two changes:
1. Download the preview data for all whitelisted links (now we download the preview data only for some links. For other links we send the url in the UI)
2. Validate the preview before sending it to the UI

In the UI we will use the raw data/filename provided by status-go. And we could easily mock this.

IMO this change is good and it will help us better design the component.

**Comment by micieslak** [comment]
@alexjba Sounds very good, thanks for explanation!

**Comment by jrainville** [comment]
@micieslak another point, I don't think this is UI logic we move to the backend. It's the opposite. This is all logic that **should have** been in the backend from the start, because it's data fetching. It wasn't done like that because we were noob (aka me, I did that code lol) and because the setting to show the links was only QML side before.

@alexjba when/if you work on this, remember to check the setting to show links first before fetching data.
This is very important. Some people do specifically do not want to show the links so they don't show their IP address to sites.

Also, make sure to the use the thread tasks that already exist. Querying from some sites was already slow, so if we wait on the backend fetch before showing anything, it's gonna create a very bad UX. So if possible, when creating the message, we just show the link with no data, then we populate the link data when we finish fetching it with events and signals.
