### ISSUE TITLE
Can't connect to store node until app restart

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-desktop#9114]
# Bug Report

## Description

Sometimes, if the app fails to connect to the store node at the start of the app, then it will not happen until restart.

## Steps to reproduce

1. Start the app
2. Observe "mailserver interactions" under Node Management section
3. Wait for a few minutes
4. If it connects to the mailserver, repeat from step 1

### Additional Information

- Status desktop version: master (ea0db55361d93787fc393b402016448b91b18ec4)
- Operating System: Ubuntu 22.04

### Notes
Most likely it is a bug in status-go's mailserver cycle event handler.

**Comment by osmaczko** [comment]
CC: @richard-ramos

**Comment by anastasiyaig** [comment]
<img width="1106" alt="Screenshot 2023-01-23 at 11 47 27" src="https://user-images.githubusercontent.com/82375995/214002279-69cbe522-f450-4ae3-9160-7dc9307cecf6.png">

**Comment by richard-ramos** [comment]
What I have seen while investigating this issue is that the mailserver cycle is indeed working and a mailserver selected and requests sent however the node management tab failed to receive logs
![image](https://user-images.githubusercontent.com/1106587/215162464-9a0e4e61-e319-4357-a744-9b67c90899b8.png)
Notice in the image how there's a mailserver active in the terminal logs, but the mailserver interactions area is empty (logs below are empty as well). Sometimes I get logs, but they fail to update, so I always refer to the information in the terminal instead.

This problem in combination with the banner not closing automatically after some seconds gives the impression of never being able to connect to a mailserver.

**Comment by richard-ramos** [comment]
@osmaczko if you got some time tomorrow, please attempt to reproduce this issue in latest master. There has been a couple of changes related to mailservers that should have improved the reliability of mailservers.  (In addition to these changes, in the messaging section of settings you should be able to see the current active mailserver).

It should roughly take 45s-1m to connect to a diff mailserver in case of failures.
