### ISSUE TITLE
Implement GPG signing for Linux packaged build

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/status-desktop#913]
This *should* make the build tamper proof (hopefully).

Additionally, revise the Linux packaged build routine so that the AppImage is zip'd along with plain text file/s indicating the cheksum (MD5 and/or SHA-3) of the `.AppImage` file.

**Comment by jakubgs** [comment]
I guess this is a duplicate: https://github.com/status-im/infra-ci/issues/25

Looks like this might be necessary for the DappGet thing people are working on:
https://github.com/3esmit/distributor-dapp

And since we now publish Linux images in a Tarball ever since https://github.com/status-im/status-desktop/pull/2655 was merged signing with GPG should be easy.

**Comment by 0kok0** [comment]
@jakubgs let's keep https://github.com/status-im/infra-ci/issues/25 for signature generation and this ticket for signature verification

**Comment by 0kok0** [comment]
@michaelsbradleyjr  having redundant ways for desktop to pull public keys, in addition to pgp servers would be dope, we could use keybase here https://keybase.io/docs/api/1.0/call/user/lookup

**Comment by jakubgs** [comment]
Now that we've merged the signing PR in https://github.com/status-im/status-desktop/pull/3185 what's left is:

1. Publish the public keys for development and release on the site
2. Add the public keys to the `status-desktop` repo
3. Update docs to show users how to validate the signature
