### ISSUE TITLE
Investigate Mac CPU issues issues

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9490]
### Description

On Mac, users experience a crazy amount of CPU usage, even with the app in the background, whereas Linux and even Windows don't have that issue.

The only 2 things that come to mind that are different on Mac are the Frame (to have the Mac buttons and such at the top), and the OS notifications (we have custom DOtherSide code for those on Mac).

Try to comment those out and see if the app still uses as much CPU in the background. We are aiming for close to 0 when the app is in the background and no messages are being received.

The goal of this issue is just to get information. We can decide after what to do with those depending on the findings.

**Comment by borismelnik** [comment]
@jrainville I test it and seems like it doesn't help :( 
There is maybe a problem with Qt specifically in current platform implementation. We can fix it if we start using analyzer tools for app. I tried to run it with Xcode analyzer but failed - it stuck on running state or after attaching to running process.
One think in OS notifications code looks weird:
`
void OSNotification::showNotificationMacOs(QString title, QString message, 
    QString identifier)
{
    if (!m_notificationHelper)
        return;

    NSUserNotification* notification = [[NSUserNotification alloc] init];
    notification.title = title.toNSString();
    notification.informativeText = message.toNSString();
    notification.soundName = NSUserNotificationDefaultSoundName;
    notification.hasActionButton = false;
    notification.identifier = identifier.toNSString();
    
    NSUserNotificationCenter* center = NSUserNotificationCenter.defaultUserNotificationCenter;
    center.delegate = m_notificationHelper->delegate;
    [center deliverNotification:notification];
    [notification release];
}
`

there `center.delegate` is initialized when every notification was shown, but I think its the same instance every time so no memory leaks.

Any new ideas? :)

**Comment by caybro** [comment]
@alexjba has a lot of good news here :)

**Comment by alexjba** [comment]
I guess we're working on the same thing #8139
So these are my findings so far:
1. ~90% of the CPU usage wile the app is in the background is consumed by status-go. I've shared some profiling data here #8139 that can be analysed using `Instruments`.
2. While the app is in foreground min 10% of CPU is consumed by the renderer. This usually happens when we animate things on the screen. Most common are the StatusChatInput cursor and the busy indicator in the message history.

4. Now on the bright side, the app can be compiled natively for M1 and the performance is better. It was the first time I've seen the app consuming 7% CPU while actually using the app 🎉 . Usually I've seen it around 15-20%. One thing to note here is that the arm build I'm using is slowed down by the [Address sanitizer](https://clang.llvm.org/docs/AddressSanitizer.html). Unfortunately status-go will freeze with the normal nim compilation flags and the only workaround I've found is to enable the `Address sanitizer`. See https://github.com/golang/go/issues/48437
