### ISSUE TITLE
[windows] Security alert when uploading a picture

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9539]
### Description

Was reported in community channel:

`Whenever anyone posts a picture, I get a security alert`

![image_14-02-2023_11-05-06](https://user-images.githubusercontent.com/82375995/218675651-9db99b31-872a-442c-9136-59f848c4a46f.png)

**Comment by anastasiyaig** [comment]
@John-44 tagging u to add details

**Comment by John-44** [comment]
@anastasiyaig thanks for reporting.

Some more details regarding this issue:

- I don't think this issue is necessarily related to uploading an image.  Both myself and @imagiMary consistently have this Windows OS certificate security dialogue pop up after launching Status.  It consistently pops up 3 to 5 minutes *every time* after launching Status (e.g. reproducing this issue is easy).

- Both myself and @imagiMary are running Windows 10, and Status Desktop 0.9

- As this issue seems to affect every Windows user (but is not critical), fixing it should be high priority.

**Comment by w-rachel** [comment]
I see the alert whenever I enter a channel where someone has posted a new image. I am also running Windows 10 and Status Desktop 0.9.

**Comment by caybro** [comment]
@jakubgs any idea? anything to do with our certificates?

**Comment by anastasiyaig** [comment]
@glitchminer can u check it as well please?

**Comment by jakubgs** [comment]
@caybro I highly doubt that. If the issue was the certificate we sign the app with it would fail at startup.

This is clearly related to the request that fetches the image.

**Comment by richard-ramos** [comment]
Maybe a problem with the self signed certificate installed here? 
https://github.com/status-im/status-desktop/blob/master/src/nim_status_client.nim#L98-L99

**Comment by glitchminer** [comment]
> @glitchminer can u check it as well please?

Tested on Windows 11 with 0.10 RC7 and had one instance of the app becoming unresponsive after selecting an image. After restarting it seemed possible to send images without issue.

**Comment by caybro** [comment]
> Maybe a problem with the self signed certificate installed here? https://github.com/status-im/status-desktop/blob/master/src/nim_status_client.nim#L98-L99

ftr, it's this file here: https://github.com/status-im/status-desktop/blob/master/cacert.pem

**Comment by caybro** [comment]
and it's installed via Makefile (on Windows only) here: https://github.com/status-im/status-desktop/blob/master/Makefile#L568

**Comment by glitchminer** [comment]
Closing, unable to reproduce using nightly on W11. Joined a new community and received image in a new channel without alert.
