### ISSUE TITLE
Access to community without membership request

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-desktop#9636]
# Bug Report

There is a possibility to get acces to the community with enabled "request to join required" without even sending request to join

## Description
<img width="994" alt="Screenshot 2023-02-24 at 14 15 34" src="https://user-images.githubusercontent.com/2522130/221153231-cbe81e4a-ee24-4b2b-9cf3-0ac94e37c830.png">

<img width="1387" alt="Screenshot 2023-02-24 at 14 13 17" src="https://user-images.githubusercontent.com/2522130/221153261-90b38756-0d4d-40b5-bd3c-4aa027df0ea5.png">

## Steps to reproduce

1. Receive invitation to the community with "request to join required" enabled
2. Visit community

#### Expected behavior

No access to the community without accepted membership request

#### Actual behavior

Access to the community data: channels, messages, notifications (mentions & replies) 

<img width="1126" alt="Screenshot 2023-02-24 at 14 18 42" src="https://user-images.githubusercontent.com/2522130/221154060-49a87dcb-7ec5-4832-9c7d-8b36f3e8806b.png">

### Additional Information

- Status desktop version: master

**Comment by jrainville** [comment]
I think this is intended. It will be changed/fixed with community permissions. cc @John-44

**Comment by John-44** [comment]
> I think this is intended. It will be changed/fixed with community permissions. cc @John-44

@jrainville @MishkaRogachev @0x-r4bbit @endulab @mprakhov @borismelnik 

If a community is a 'Open community' (aka a 'Public community') then:
- The community as a whole should **not be encrypted**, only channels that are not *viewable* without token permissions should be encrypted.
- It should be possible for somebody who is not a member of the community to: A) read the titles of all categories and channels in an open community including the titles (only) of encrypted channels and B) view the contents of all channels that are viewable without holding tokens (Note that I'm saying "viewable without holding tokens", because a channel that has a token permission to "view and post" **AND** a second permission to *view only without holding any tokens* set should be viewable to users who are not members of the community and should not be encrypted).

If a community is a 'Closed community' (aka a 'Private community') then:
- The community as a whole should be encrypted.
- If somebody is not a member of the community, they should not be able to see any of the categories and channels, and they should not be able to see the contents of any of the channels. 

A 'Open community' (aka a 'Public community') is a community zero token permissions to 'become a member' of the community set,  An 'Open community' may have token permissions to 'become an admin' of the community set.

A 'Closed community' (aka a 'Private community') is a community with one or more token permissions to 'become a member' of the community set.

When we introduce the token based permissions, we should remove the "Encrypt community" option from the Create community and Edit community screens.  This is because encryption of a whole community or individual channels inside an otherwise non-encrypted community should be switched on and off as needed depending on the token permissions that are set, as per the logic above.

Happy to do a call to discuss if this would be useful, this is an important topic!

**Comment by John-44** [comment]
Also not that "request to join required" being enabled or disabled should have no bearing on any of the above.  This is an entirely seperate mechanism from the token based permissions, and changing this setting does not change a community into an 'Open community' or a 'Closed community'.

It is entirely possible (and expected) that some 'Open communities' will have "request to join required"  enabled and other Open communities will have "request to join required" disabled.  Similarly It is entirely possible (and expected) that some 'Closed communities' will have "request to join required" disabled and other Closed communities will have "request to join required" enabled.

**Comment by jrainville** [comment]
Ok, that checks out with my understanding, but it clarifies some points.

This means that this issue is not actually an issue as per you second comment.

The notifications part is weird though, but that's an edge case. That means you joined the community, got mentioned, left, then re-spectated. I wouldn't bother with that for now.

Closing.
