### ISSUE TITLE
[Community Permissions] ENS icon `@` color is not changed according to the user availability in `JoinCommunityView`

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-desktop#9766]
### Description
ENS icon `@` color should be red if user doesn't match the criteria. Now it is always displayed as blue color:

![image](https://user-images.githubusercontent.com/97019400/223413431-f9c6b663-c2e1-4142-a764-8597108ffedd.png)

**Comment by alexjba** [comment]
@benjthayer Can you please help us with the red version of `@` icon? 
We only have this [blue version](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba⎜Desktop?node-id=22734-503405&t=IOegplIx5hQUm6W1-0)

**Comment by caybro** [comment]
> @benjthayer Can you please help us with the red version of `@` icon? We only have this [blue version](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22734-503405&t=IOegplIx5hQUm6W1-0)

You can recolor the icon on the fly, using the same color as the text next to it

**Comment by alexjba** [comment]
> > @benjthayer Can you please help us with the red version of `@` icon? We only have this [blue version](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22734-503405&t=IOegplIx5hQUm6W1-0)
> 
> You can recolor the icon on the fly, using the same color as the text next to it

With `ColorOverlay`?
The UI component is generic and the image is provided by the model. IMO this is a good approach and I'm not sure it's better to add the `ColorOverlay` for this specific use case.

**Comment by caybro** [comment]
> > > @benjthayer Can you please help us with the red version of `@` icon? We only have this [blue version](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22734-503405&t=IOegplIx5hQUm6W1-0)
> > 
> > 
> > You can recolor the icon on the fly, using the same color as the text next to it
> 
> With `ColorOverlay`? The UI component is generic and the image is provided by the model. IMO this is a good approach and I'm not sure it's better to add the `ColorOverlay` for this specific use case.

StatusIcon has this built-in

**Comment by alexjba** [comment]
> > > > @benjthayer Can you please help us with the red version of `@` icon? We only have this [blue version](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=22734-503405&t=IOegplIx5hQUm6W1-0)
> > > 
> > > 
> > > You can recolor the icon on the fly, using the same color as the text next to it
> > 
> > 
> > With `ColorOverlay`? The UI component is generic and the image is provided by the model. IMO this is a good approach and I'm not sure it's better to add the `ColorOverlay` for this specific use case.
> 
> StatusIcon has this built-in

Nice, thanks! I'll give it a try.

**Comment by alexjba** [comment]
@caybro We can do it, but it's a small refactoring to support this. IMO it's a useful refactoring because currently we support only homogeneous model data in terms of image type for the `StatusItemSelector`.

I have two options here:
1. To use another red .svg image when the user doesn't own an ens name. The image is provided by `HoldingsSelectionModel` based on availability.
2. To use the generic `username` icon and add color. As @caybro pointed out, it's supported by `StatusIcon`, but we're currently using `StatusRoundImage` for holdings icons because we use the same configuration for all items in the model. One option is to provide a model role `isIcon` to the `HoldingsSelectionModel`. This role will be used to configure `StatusListItemTag` to create an Icon instead of an Image. On top of this we need to revisit https://github.com/status-im/status-desktop/commit/b85450a3deceee1b02d8aa5b8ac15f48c8ca79ec and replace the `useIcons` property with a model role `isIcon`.

@noeliaSD @micieslak Adding you here as you've worked a lot on these components. WDYT of the second option? Would it be useful in other use cases? Since the model is providing the image source for holdings or other tags I find it natural for it to also provide the image type as opposed to configure it based on the view where the components are used.

**Comment by caybro** [comment]
> @caybro We can do it, but it's a small refactoring to support this. IMO it's a useful refactoring because currently we support only homogeneous model data in terms of image type for the `StatusItemSelector`.
> 
> I have two options here:
> 
> 1. To use another red .svg image when the user doesn't own an ens name. The image is provided by `HoldingsSelectionModel` based on availability.
> 2. To use the generic `username` icon and add color. As @caybro pointed out, it's supported by `StatusIcon`, but we're currently using `StatusRoundImage` for holdings icons because we use the same configuration for all items in the model. One option is to provide a model role `isIcon` to the `HoldingsSelectionModel`. This role will be used to configure `StatusListItemTag` to create an Icon instead of an Image. On top of this we need to revisit [b85450a](https://github.com/status-im/status-desktop/commit/b85450a3deceee1b02d8aa5b8ac15f48c8ca79ec) and replace the `useIcons` property with a model role `isIcon`.
> 
> @noeliaSD @micieslak Adding you here as you've worked a lot on these components. WDYT of the second option? Would it be useful in other use cases? Since the model is providing the image source for holdings or other tags I find it natural for it to also provide the image type as opposed to configure it based on the view where the components are used.

StatusRoundIcon ;)

**Comment by noeliaSD** [comment]
> 2\. b85450a

It sounds a good idea from my point of view. Go for it! And yeah, I think that it is probably something we will need / reuse in the future.
