### ISSUE TITLE
Optimize NFT minting contracts to reduce gas usage 

### ISSUE THREAD

**Issue by John-44** [status-im/status-desktop#9943]
**This is an improvement for the 0.12 release**

-- Change request --

@jrainville recently mentioned that the NFT contract that a community owner deploys to mint a token via the community admin UI requires a lot of gas to deploy.

This issue is to optimise the contract to reduce the amount of gas needed to deploy the NFT contract.  

One approach could be to split the contract into multiple contracts.  Currently the UI lets users change the following contract settings prior to deployment:

- soulbound/not soulbound
- unlimited supply/specific finite supply
- remotely destructible / not remotely destructible 

Instead of having one large contract that handles all these permutations, one optimisation idea would be to instead have a number of contracts, each optimised for a specific permutation e.g.

1. A soulbound, unlimited supply, remotely destructible contract
2. A soulbound, specific finite supply, remotely destructible contract
3. A soulbound, unlimited supply, not remotely destructible contract
4. A soulbound, specific finite supply, not remotely destructible contract
5. A not soulbound, unlimited supply, remotely destructible contract
6. A not soulbound, specific finite supply, remotely destructible contract
7. A not soulbound, unlimited supply, not remotely destructible contract
8. A not soulbound, specific finite supply, not remotely destructible contract

And then depending on what options the community owner choses in the UI, a different contract would be deployed.  

This is just one idea for optimising the gas usage of our NFT contract, other changes that can also further reduce gas usage are also welcome :-)

cc'ing @gravityblast @jrainville @iurimatias

**Comment by endulab** [comment]
A few thoughts:
Probably we can't manipulate smart contracts because we need to keep OpenZeppelin implementation in order to work correctly with OpenSea, and other vendors. We need to keep standards.
We can optimize smart contract compilation, however then we need to check: deployment cost and all other operations cost (airdrop, burning), because optimisation has impact on them.
A sensible approach is to make such optimization in the end when we have all functionalities implemented. Then we can compare costs.
Deployment on Optimism is not so expensive.
