### ISSUE TITLE
3-word phrases in authentication modal look off in darkmode

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-desktop#9983]
Check this screenshot:

![Screenshot from 2023-03-22 13-16-08](https://user-images.githubusercontent.com/445106/226902800-d8a92bf9-bb08-4b1c-a12b-bf3bf282bb79.png)

Notice the 3 "tags" in the input. They are pitch black which doesn't look right.

**Comment by caybro** [comment]
The image is funky too :D

**Comment by 0x-r4bbit** [comment]
Wow I didn't even pay attention to that haha

**Comment by alexjba** [comment]
@benjthayer How should the 3-word phrases look like in dark mode?
In light mode it's white with no border: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6598-76577&t=HmIPqZQnprvASMCy-0

Also, could you please help me get [this illustration](https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=6598-76577&t=HmIPqZQnprvASMCy-0) with transparent background so that we can use it in dark mode?

**Comment by benjthayer** [comment]
Hey @alexjba @0x-r4bbit @caybro 

I believe the dark theme variant of this screen should look like this (colour values listed in the attached screen). 

Regarding the illustrations, hopefully you have access to the Drive now, just for completeness - adding here too:
https://drive.google.com/drive/folders/1UBmELQJf6ufrqwj0qjd5-5fElijLSdXe

<img width="1370" alt="Screenshot 2023-03-29 at 14 49 02" src="https://user-images.githubusercontent.com/110033914/228559319-74a63ce0-ed7e-46b6-a314-8dd32b087337.png">

Hope that helps! :)

**Comment by benjthayer** [comment]
Hey @alexjba the keychain image has been send over by Tubik with transparent backing - I've uploaded it to the shared Drive:
https://drive.google.com/file/d/1s0KpHIuu-96tDuUKLUkW5QFeqh3j2S-D/view?usp=share_link

![keychain_70](https://user-images.githubusercontent.com/110033914/228855862-ef335d21-273f-4e86-91ce-39ab76840d83.png)

**Comment by caybro** [comment]
@alexjba just don't take this gigantic one :D the smaller ones will do
